<?php
//
// File:    view_by_category.php
// License: GNU GPL
//
require_once('./settings.php');
$page_title = ':: category view';
include_once("$wb_inc_dir/header.php");


	// Parse the passed vars into something useful also check for nulls
	$the_category = $_GET['the_category'];

	// Connect to the RDBMS and select the database.
	$db = DB_connect($site, $user, $pass);
	DB_select_db($database, $db);

    // select posts in the database that match the category
    // should paginate this in the future
    $result = DB_query("select * 
        from $tblPosts
        where category = '$the_category' 
        order by year DESC, month DESC, day DESC", $db);

	// output the current shows        
	echo("<!-- generated by wheatblog: start -->\n\n");

	/* echo("<div class='indent2'>\n");
	echo("<span class='cnt-subhead'>Filter: View by Category</span><br />\n");
	echo("[category: " . "$the_category" . "] ");
	echo("[<a href='$blog_index_page_name'>remove</a>]\n");
	echo("</div>\n"); */

	while($row = DB_fetch_array($result))
	{
		$the_id       = $row['id'];
		$the_day      = $row['day'];
		$the_month    = $row['month'];
		$the_date     = $row['date'];
		$the_year     = $row['year'];
		$the_category = $row['category'];
		$the_locked   = $row['locked'];

		// Parse out the category id into its string value
		$result2 = DB_query("select *   
			from $tblCategories   
			where id = '$the_category'", $db);

		while($row2 = DB_fetch_array($result2))
			$the_category_name = $row2['category'];

		$the_showpref = $row['showpref'];
		$the_title    = $row['title'];
		$the_body     = $row['body'];
		$comments     = $row['comments'];

		// Post body
		# removed interpolation	
		# inserted markup for better formatting control	
        
		echo '<div class="subcontent">'."\n";
		echo '<div class="post-heading">'."\n"; # heading is important, needs to be seperate
		echo '<h3 class="post-title">'.$the_title.'</h3>'."\n";
		echo '<h4 class="post-date">'.$the_day.', '.$the_month.'.'.$the_date.'.'.$the_year.'</h4>'."\n";
		echo '</div>'."\n";  # closes div.post-heading
		echo '<div class="post-body">'.$the_body.'</div>'."\n\n";

		// Post category
		# removed interpolation
       
		echo '<div class="post-menu">'."\n".'<ul class="postnav">'."\n"; #links are now unordered list
		
		echo '<li title="Current Category"><a href="view_by_category.php?the_category='.$the_category.'">'.$the_category_name. '</a></li>'."\n";

		// Post comments
		# removed interpolation
		
	 	if ( $the_locked ) { 
		echo '<li title="Sorry, This post is Locked."><span class="lock">Comments ('.$comments.')</span></li>'."\n";
		
		} else {
	   	echo '<li title="Add a Comment"><a href="view_by_permalink.php?the_id='.$the_id.'">Comments ('.$comments.')</a></li>'."\n";
        
		}
		echo "\n".'</ul>'."\n".'</div>'."\n";  # closes list and div.post-menu
		echo '</div>'."\n\n"; # closes div.indent
	}


include_once("$wb_inc_dir/footer.php");
?>
