<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>Shows</title>
    <link rel="stylesheet" type="text/css" href="showlister.css">
  <head>
  <body>

<?php
    // read in the connection settings
    require("showlister_settings.inc.php");
    require("showlister_methods.inc.php");

    // connect to the RDBMS
    $db = mysql_connect("$site","$user","$pass") 
        or die_now("<h2>Could not connect to database server</h2><p>Check passwords and sockets</p>");

    // select the database
    mysql_select_db("$database",$db) 
        or die_now("<h2>Could not select database $database</h2><p>Check database name</p>");

    // select all the shows in the database
    $result = mysql_query("select show_id, month, day, year, location, details, venue
        from $database_table order by year, month, day",$db) 
        or die_now("<h2>Could not select shows</h2>");

    // output the current shows        
    echo("<div class='box'>\n<h3>Shows</h3>\n</div>\n<div class='box'>\n");
    echo("<table border='1' width='80%'>\n");
    echo("\t<tr>\n\t\t<td>date</td>\n\t\t<td>venue</td>\n\t\t<td>location</td>\n\t</tr>\n");
    while($row = mysql_fetch_array($result)) {
        $the_id = $row["show_id"];
        $the_month = $row["month"];
        $the_day = $row["day"];
        $the_year = $row["year"];
        $the_location = $row["location"];
        $the_details = $row["details"];
        $the_venue = $row["venue"];

        // shows
        echo("\t<tr>\n\t\t<td>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>" . "$the_venue" . "</td>\n");
        echo("\t\t<td>" . "$the_location" . "</td>\n\t</tr>\n");
        echo("\t<tr>\n\t\t<td colspan='3'>" . "$the_details" . "</td>\n");
    }
    echo("\t</tr>\n</table>\n</div>\n");
?>
    <div class='box'>
        generated by <a href="http://showlister.sourceforge.net">showlister</a>
        <?php showlister_version(); ?>
    </div>

    <div class='box'>
    About this sample page:<br>
    This sample page displays every show in the database, ordered by date, but 
    ignores all artist information.  This page puts the "details" information 
    on it's own line.  This page is suitable for sites that contain 
    show informatin about only one artist and that need extra room to explain 
    details of the events.  
    </div>
  </body>
</html>