<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>Shows</title>
    <link rel="stylesheet" type="text/css" href="showlister.css">
  <head>
  <body>

<?php
    // read in the connection settings
    require("showlister_settings.inc.php");
    require("showlister_methods.inc.php");

    // connect to the RDBMS
    $db = mysql_connect("$site","$user","$pass") 
        or die_now("<h2>Could not connect to database server</h2><p>Check passwords and sockets</p>");

    // select the database
    mysql_select_db("$database",$db) 
        or die_now("<h2>Could not select database $database</h2><p>Check database name</p>");

    // first artist:  select all the shows in the database
    $result = mysql_query("select show_id, month, day, year, location, details, venue, artist_id
        from $database_table 
        where artist_id = '1'
        order by year, month, day",$db) 
        or die_now("<h2>Could not select shows</h2>");

    // first artist:  output the current shows        
    echo("<div class='box'>\n<h3>first artist</h3>\n</div>\n<div class='box'>\n");
    echo("<table border='1' width='80%'>\n");
    echo("\t<tr>\n\t\t<td>date</td>\n\t\t<td>venue</td>\n\t\t<td>location</td>\n\t\t<td>details</td>\n\t\t</tr>\n");
    while($row = mysql_fetch_array($result)) {
        $the_id = $row["show_id"];
        $the_month = $row["month"];
        $the_day = $row["day"];
        $the_year = $row["year"];
        $the_location = $row["location"];
        $the_details = $row["details"];
        $the_venue = $row["venue"];

        // shows
        echo("\t<tr>\n\t\t<td>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>" . "$the_venue" . "</td>\n");
        echo("\t\t<td>" . "$the_location" . "</td>\n");
        echo("\t\t<td>" . "$the_details" . "</td>\n");
    }
    echo("\t</tr></table>\n</div>\n");
    
    // ====================================================

    // second artist:  select all the shows in the database
    $result = mysql_query("select show_id, month, day, year, location, details, venue, artist_id
        from $database_table 
        where artist_id = '2'
        order by year, month, day",$db) 
        or die_now("<h2>Could not select shows</h2>");

    // second artist:  output the current shows        
    echo("<div class='box'>\n<h3>second artist</h3>\n</div>\n<div class='box'>\n");
    echo("<table border='1' width='80%'>\n");
    echo("\t<tr>\n\t\t<td>date</td>\n\t\t<td>venue</td>\n\t\t<td>location</td>\n\t\t<td>details</td>\n\t\t</tr>\n");
    while($row = mysql_fetch_array($result)) {
        $the_id = $row["show_id"];
        $the_month = $row["month"];
        $the_day = $row["day"];
        $the_year = $row["year"];
        $the_location = $row["location"];
        $the_details = $row["details"];
        $the_venue = $row["venue"];

        // shows
        echo("\t<tr>\n\t\t<td>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>" . "$the_venue" . "</td>\n");
        echo("\t\t<td>" . "$the_location" . "</td>\n");
        echo("\t\t<td>" . "$the_details" . "</td>\n");
    }
    echo("\t</tr></table>\n</div>\n");
?>
    <div class='box'>
        generated by <a href="http://showlister.sourceforge.net">showlister</a>
        <?php showlister_version(); ?>
    </div>

    <div class='box'>
    About this sample page:<br>
    This sample page displays every show in the database, ordered by date, by 
    the artist whose artist id equals '1' and the repeats the process for the 
    artist whose artist id equals '2'.  This method allows you to group shows 
    by artist and seperate them graphically on the page
    
    If you don't artists in your  
    database with ids equal to 1 and 2 (or if you do, but they have no shows), 
    you won't see any shows here.  
    
    </div>
  </body>
</html>