<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>Shows</title>
    <link rel="stylesheet" type="text/css" href="showlister.css">
  <head>
  <body>

<?php
    // read in the connection settings
    require("showlister_settings.inc.php");
    require("showlister_methods.inc.php");
    
    // connect to the RDBMS
    $db = mysql_connect("$site","$user","$pass") 
        or die_now("<h2>Could not connect to database server</h2><p>Check passwords and sockets</p>");

    // select the database
    mysql_select_db("$database",$db) 
        or die_now("<h2>Could not select database $database</h2><p>Check database name</p>");

    // select all artists in the database
    $result = mysql_query("select artist_id, artist_name, artist_email, artist_url
        from $database_table_artists order by artist_name",$db) 
        or die_now("<h2>Could not select artists</h2>");

    // output the current artist        
    echo("<div class='box'>\n<h3>Artists</h3>\n</div>\n<div class='box'>\n");
    echo("<table width='90%'>\n");
    echo("\t<tr>\n\t\t<td>name</td>\n\t\t<td>email</td>\n\t\t<td>url</td>\n\t\t</tr>\n");
    while($row = mysql_fetch_array($result)) {
        $the_id = $row["artist_id"];
        $the_artist_name = $row["artist_name"];
        $the_artist_email = $row["artist_email"];
        $the_artist_url = $row["artist_url"];

        // artists
        echo("\t<tr>\n");
        echo("\t\t<td>" . "<a href='" . "$the_artist_url" . "'>" . "$the_artist_name" . "</a></td>\n");
        echo("\t\t<td>" . "<a href='mailto:" . "$the_artist_email" . "'>" . "$the_artist_email" . "</a></td>\n");
        echo("\t\t<td>" . "<a href='" . "$the_artist_url" . "'>" . "$the_artist_url" . "</a></td>\n");
    }
    echo("\t</tr></table>\n</div>\n");
?>
    <div class='box'>
        generated by <a href="http://showlister.sourceforge.net">showlister</a>
        <?php showlister_version(); ?>
    </div>

    <div class='box'>
      About this sample page<br>
      This page lists all artists in the database, ordered by name.  Artists 
      names and URLs are rendered as links.  Artists emails are rendered as 
      mailto links.  
    </div>
  </body>
</html>