<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>Shows</title>
    <link rel="stylesheet" type="text/css" href="showlister.css">
  <head>
  <body>

<?php
    // read in the connection settings
    require("showlister_settings.inc.php");
    require("showlister_methods.inc.php");
    
    // connect to the RDBMS
    $db = mysql_connect("$site","$user","$pass") 
        or die_now("<h2>Could not connect to database server</h2><p>Check passwords and sockets</p>");

    // select the database
    mysql_select_db("$database",$db) 
        or die_now("<h2>Could not select database $database</h2><p>Check database name</p>");

    // select all the shows in the database
    $result = mysql_query("select show_id, month, day, year, location, details, venue, artist_id
        from $database_table 
        where artist_id = '5'
        order by year, month, day",$db) 
        or die_now("<h2>Could not select shows</h2>");

    // output the current shows        
    echo("<div class='box'>\n<h3>Shows</h3>\n</div>\n<div class='box'>\n");
    echo("<table border='1' width='80%'>\n");
    echo("\t<tr>\n\t\t<td>date</td>\n\t\t<td>venue</td>\n\t\t<td>location</td>\n\t\t<td>details</td>\n\t\t</tr>\n");
    while($row = mysql_fetch_array($result)) {
        $the_id = $row["show_id"];
        $the_month = $row["month"];
        $the_day = $row["day"];
        $the_year = $row["year"];
        $the_location = $row["location"];
        $the_details = $row["details"];
        $the_venue = $row["venue"];

        // shows
        echo("\t<tr>\n\t\t<td>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>" . "$the_venue" . "</td>\n");
        echo("\t\t<td>" . "$the_location" . "</td>\n");
        echo("\t\t<td>" . "$the_details" . "</td>\n");
    }
    echo("\t</tr></table>\n</div>\n");
?>
    <div class='box'>
        generated by <a href="http://showlister.sourceforge.net">showlister</a>
        <?php showlister_version(); ?>
    </div>

    <div class='box'>
    About this sample page:<br>
    This sample page displays every show in the database, ordered by date, by 
    the artist whose artist id equals '5'.  If you don't have an artist in your  
    database with an id equal to 5 (or if you do, but the artist has no shows), 
    you won't see any shows here.

    <br>&nbsp;<br>

    If you use showlister to manage shows for more than one band, you'd create 
    a separate page like this one for each band.  In the code for this page, 
    look for line 24 (where artist_id = '5') and change it for the artist 
    you need.     
    </div>
  </body>
</html>