<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>Shows</title>
    <link rel="stylesheet" type="text/css" href="showlister.css">
  <head>
  <body>

<?php
    // read in the connection settings
    require("showlister_settings.inc.php");
    require("showlister_methods.inc.php");

    // connect to the RDBMS
    $db = mysql_connect("$site","$user","$pass") 
        or die_now("<h2>Could not connect to database server</h2><p>Check passwords and sockets</p>");

    // select the database
    mysql_select_db("$database",$db) 
        or die_now("<h2>Could not select database $database</h2><p>Check database name</p>");

    // select all the shows in the database
    $result = mysql_query("select show_id, month, day, year, location, details, venue
        from $database_table order by year, month, day",$db) 
        or die_now("<h2>Could not select shows</h2>");

    // set up the table        
    echo("<div class='box'>\n<h3>Shows</h3>\n</div>\n<div class='box'>\n");
    echo("<table border='1' width='80%'>\n");
    echo("\t<tr>\n\t\t<td>date</td>\n\t\t<td>venue</td>\n\t\t<td>location</td>\n\t\t<td>details</td>\n\t\t</tr>\n");

	// print the next five shows
    // thanks to Lee Mikles (lee@getcohesive.com) for contributing the 
    // first version of this code
	  $cur_month = date("n");
	  $cur_day = date("d");
      $cur_year = date("Y");
	  $event_count=1;

    // echo out the next five shows
    while(($row = mysql_fetch_array($result)) and ($event_count <= 5)) {
      $the_id = $row["show_id"];
      $the_month = $row["month"];
      $the_day = $row["day"];
      $the_year = $row["year"];
      $the_location = $row["location"];
      $the_details = $row["details"];
      $the_venue = $row["venue"];

      if (($the_year > $cur_year)) {
        // echo shows in future years
        echo("\t<tr>\n");
        echo("\t\t<td>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>$the_venue</td>\n");
        echo("\t\t<td>$the_location</td>\n");
        echo("\t\t<td>$the_details ($cur_year)</td>\n");
        $event_count++;
      }
      if (($the_month > $cur_month) and ($the_year = $cur_year)) {
        // echo shows in future months of current year
        echo("\t<tr>\n");
        echo("\t\t<td bgcolor='orange'>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>$the_venue</td>\n");
        echo("\t\t<td>$the_location</td>\n");
        echo("\t\t<td>$the_details ($cur_year)</td>\n");
        $event_count++;
      }
      if (($the_month = $cur_month) and ($the_day >= $cur_day) and ($the_year = $cur_year)) {
        // echo shows in current month, today and later
        echo("\t<tr>\n");
        echo("\t\t<td bgolor='navy'>$the_month" . "/" . "$the_day" . "/" . "$the_year" . "</td>\n");
        echo("\t\t<td>$the_venue</td>\n");
        echo("\t\t<td>$the_location</td>\n");
        echo("\t\t<td>$the_details ($cur_year)</td>\n");
        $event_count++;
      }
	  }
    // close the table
    echo("\t</tr></table>\n</div>\n");
?>
    <div class='box'>
        generated by <a href="http://showlister.sourceforge.net">showlister</a>
        <?php showlister_version(); ?>
    </div>

    <div class='box'>
    About this sample page:<br>
    This page checks dates, prints the next five shows, and does not show old shows.
    </div>
  </body>
</html>