<?                                                                                                                                                                                                                                                                                                                                                                           
$ip = $_SERVER['REMOTE_ADDR'];                                                                                                                                                                                                                                                                                                                                               
$errorpage[nologin]='<center>You are not <a href="admin.php">logged in</a></center>';                                                                                                                                                                                                                                                                                        
$fndtime=array(year,month,day,hour,minute,second,AP);                                                                                                                                                                                                                                                                                                                        
$keytime=array(Y,M,jS,g,i,s,A);                                                                                                                                                                                                                                                                                                                                              
function bandicon($data,$img=false,$si=false){                                                                                                                                                                                                                                                                                                                               
if($data[1] &&  $data[3] !== off){                                                                                                                                                                                                                                                                                                                                           
$dl = explode("|",$data[3]);                                                                                                                                                                                                                                                                                                                                                 
$ahits=explode('()', $data[6]);                                                                                                                                                                                                                                                                                                                                              
$b_lmt = time()-$dl[1]*$dl[2];                                                                                                                                                                                                                                                                                                                                               
$hi=0;                                                                                                                                                                                                                                                                                                                                                                       
$within=0;                                                                                                                                                                                                                                                                                                                                                                   
while($hi++ < count($ahits) ){                                                                                                                                                                                                                                                                                                                                               
$usr = explode("|",$ahits[$hi]);                                                                                                                                                                                                                                                                                                                                             
if($usr[3]>$b_lmt)$within++;                                                                                                                                                                                                                                                                                                                                                 
if($within == $dl[0]){  $limit=true;  break;}                                                                                                                                                                                                                                                                                                                                
}// end loop                                                                                                                                                                                                                                                                                                                                                                 
$icon = '<img ';                                                                                                                                                                                                                                                                                                                                                             
if($limit){                                                                                                                                                                                                                                                                                                                                                                  
$icon .=  "src=\"downstat_art/bandactive.gif\" border=0 alt=\"Bandwidth is over the limit\" $img";                                                                                                                                                                                                                                                                           
}else{// if limit                                                                                                                                                                                                                                                                                                                                                            
if($dl[4])$icon .=  "src=\"downstat_art/bandhasactivated.gif\" border=0 alt=\"Bandwidth has been over the limit\" $img"; else $icon .= "src=\"downstat_art/band.gif\" border=0 alt=\"Bandwidth is set\" $img";                                                                                                                                                               
}// if !limit                                                                                                                                                                                                                                                                                                                                                                
$icon .= ' >';                                                                                                                                                                                                                                                                                                                                                               
}else{                                                                                                                                                                                                                                                                                                                                                                       
if($si)$icon .= '<img src="downstat_art/band.gif" '.$img.' border=0>';                                                                                                                                                                                                                                                                                                       
}// if data[3]                                                                                                                                                                                                                                                                                                                                                               
return $icon;                                                                                                                                                                                                                                                                                                                                                                
}//                                                                                                                                                                                                                                                                                                                                                                          
function mailicon($br,$extra,$alwayson){                                                                                                                                                                                                                                                                                                                                     
$hits = count(explode('()',$br[6]))-1;                                                                                                                                                                                                                                                                                                                                       
if($br[4] == off){                                                                                                                                                                                                                                                                                                                                                           
if(!$alwayson){return "<img src=\"downstat_art/hit_email.gif\" border=0 $extra >"; }                                                                                                                                                                                                                                                                                         
}elseif($hits < $br[4]){                                                                                                                                                                                                                                                                                                                                                     
return "<img src=\"downstat_art/hit_email.gif\" border=0 $extra >";                                                                                                                                                                                                                                                                                                          
}elseif($hits > $br[4]){                                                                                                                                                                                                                                                                                                                                                     
return "<img src=\"downstat_art/emailover.gif\" border=0 $extra >";                                                                                                                                                                                                                                                                                                          
}else{                                                                                                                                                                                                                                                                                                                                                                       
if(!$alwayson){return "<img src=\"downstat_art/hit_email.gif\" border=0 $extra >"; }                                                                                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                                                                                                                                                            
}// end of function mailicon                                                                                                                                                                                                                                                                                                                                                 
function copytoboard($fileid,$Wd=false){                                                                                                                                                                                                                                                                                                                                     
global $brs,$page;                                                                                                                                                                                                                                                                                                                                                           
if($Wd)$Wd=" ".$Wd;                                                                                                                                                                                                                                                                                                                                                          
return "<a HREF=# onclick=\"clipboardData.setData('Text',this.tga),alert('The download address for $fileid has been copied to your clipboard.')\" tga=\"".str_replace($page, '', 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'])."download.php?".$brs[7]."=$fileid \"><img alt=\"Copy the download address to clipboard\" src=downstat_art/copy.gif border=0>$Wd</a> ";
}                                                                                                                                                                                                                                                                                                                                                                            
function fileactions($br,$fileline){                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                             
if($br[2]==Trash)$wf_delhist='<a href="admin.php?restore='.$fileline.'"><img src="downstat_art/restore.gif" border="0" alt="Restore this file from trash"></a>'; else 	 $wf_delhist='<a href="admin.php?delhist='.$fileline.'"><img src="downstat_art/del_hist.gif" border=0 alt="Place this file in trash"></a>';                                                           
$list['actions']=$wf_delhist.'<a href="admin.php?deletefile='.$fileline.'"><img src="downstat_art/del.gif" border="0" alt="Delete this file off of the database"></a>'.copytoboard($br[0]).'<a href="'.$br[0].'"><img src="downstat_art/select.gif" border="0" alt="Open this file"></a>';                                                                                   
if($br[3] && $br[3] !== off) $list['icons'].= bandicon($br);//'<img src="downstat_art/band.gif"> ';                                                                                                                                                                                                                                                                          
if($br[4] && $br[4] !== off && $br[6] <= $br[4])$list['icons'].= mailicon($br,false,true);                                                                                                                                                                                                                                                                                   
if($br[5] && $br[5] !== off)$list['icons'].= '<img src="downstat_art/lock.gif" border="0" >';                                                                                                                                                                                                                                                                                
return $list;                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                            
/// If function doesnt work, make sure that $timeinput,$sntxin is setup in script                                                                                                                                                                                                                                                                                            
# list($timeinput,$sntxin,$iphost,$alwaysdisplay,$whereto,$thenum)=explode("^^",$lines[1]);                                                                                                                                                                                                                                                                                  
function datezone($in=false,$sntx=false,$tog=false){                                                                                                                                                                                                                                                                                                                         
global $timeinput,$stroftime,$keytime,$fndtime,$sntxin;    
                                                                                                                                                                                                                                                                                                              
if($in == false)$in= time();                                                                                                                                                                                                                                                                                                                                                 
$stroftime = str_replace($fndtime,$keytime,$sntxin);                                                                                                                                                                                                                                                                                                                         
if($sntx == false)$sntx= $stroftime;                                                                                                                                                                                                                                                                                                                                         
if(!$tog ){                                                                                                                                                                                                                                                                                                                                                                  
$dte=explode(':',ereg_replace("(\-|\+)",'',$timeinput));                                                                                                                                                                                                                                                                                                                     
$sec= ($dte[0]*3600)+($dte[1]*60);                                                                                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                                                                            
if(strstr($timeinput, '-')){                                                                                                                                                                                                                                                                                                                                                 
if($sntx == THROUGH) return $in-$sec;                                                                                                                                                                                                                                                                                                                                        
return date($sntx,$in-$sec);                                                                                                                                                                                                                                                                                                                                                 
}else{                                                                                                                                                                                                                                                                                                                                                                       
if($sntx == THROUGH) return $in+$sec;                                                                                                                                                                                                                                                                                                                                        
return date($sntx,$in+$sec);                                                                                                                                                                                                                                                                                                                                                 
}                                                                                                                                                                                                                                                                                                                                                                            
}// end of function datezone                                                                                                                                                                                                                                                                                                                                                 
function words($number, $word,$extra=false){                                                                                                                                                                                                                                                                                                                                 
if(!$number)$number=0;                                                                                                                                                                                                                                                                                                                                                       
if($extra){  $b1="<$extra>"; $b2="</$extra>"; }                                                                                                                                                                                                                                                                                                                              
if($number == 1){ return $b1.$number.$b2." $word"; }else{ return $b1.$number.$b2." $word"."s"; }                                                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                                                                                                                                                            
function showastime($inputseconds,$intime=false){                                                                                                                                                                                                                                                                                                                            
if(!$intime)$intime=datezone(false,"THROUGH",false);                                                                                                                                                                                                                                                                                                                         
if($intime==TIME)$intime=time();                                                                                                                                                                                                                                                                                                                                             
$howlong = round( ($intime - $inputseconds) );                                                                                                                                                                                                                                                                                                                               
if("$howlong" < "60"){ $secelap = $howlong; $trange = "Second";  }                                                                                                                                                                                                                                                                                                           
if("$howlong" > "60"){ $secelap = round($howlong / 60); $trange = "Minute"; }                                                                                                                                                                                                                                                                                                
if("$howlong" > "3600"){ $secelap = round($howlong / 3600); $trange = "Hour"; }                                                                                                                                                                                                                                                                                              
if("$howlong" > "86400"){ $secelap = round($howlong / 86400); $trange = "Day"; }                                                                                                                                                                                                                                                                                             
if("$howlong" > "604800"){ $secelap = round($howlong / 604800); $trange = "Week"; }                                                                                                                                                                                                                                                                                          
return " ".words($secelap ,$trange)." Ago";                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                            
function str_short($in,$length=50,$mm=false){                                                                                                                                                                                                                                                                                                                                
if(strlen($in) >$length):                                                                                                                                                                                                                                                                                                                                                    
if($mm){                                                                                                                                                                                                                                                                                                                                                                     
$in= substr("$in", 0, ($length-3))."...";                                                                                                                                                                                                                                                                                                                                    
}else{                                                                                                                                                                                                                                                                                                                                                                       
$in= "...".substr("$in", $length-50, ($length-3));                                                                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                                                                            
endif;                                                                                                                                                                                                                                                                                                                                                                       
return $in;                                                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                            
function selected($n,$key){                                                                                                                                                                                                                                                                                                                                                  
if((date("n") == $n && !$key) or $key == $n ){ echo selected; }                                                                                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                                                                                                                            
function getip($ip){                                                                                                                                                                                                                                                                                                                                                         
global $iphost;                                                                                                                                                                                                                                                                                                                                                              
$a= '<a href="global.php?mode=host&lookuphost='.$ip.'">';                                                                                                                                                                                                                                                                                                                    
if($iphost == IP){                                                                                                                                                                                                                                                                                                                                                           
$a .=$ip;                                                                                                                                                                                                                                                                                                                                                                    
 }else{                                                                                                                                                                                                                                                                                                                                                                      
  if(!($wip= @gethostbyaddr($ip)))$wip=$ip;                                                                                                                                                                                                                                                                                                                                  
   $a .= $wip;                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                        
return  $a.'</a>';                                                                                                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                                                                            
function check($key, $value){                                                                                                                                                                                                                                                                                                                                                
if($key==$value)echo checked;                                                                                                                                                                                                                                                                                                                                                
}// check()                                                                                                                                                                                                                                                                                                                                                                  
?>                                                                                                                                                                                                                                                                                                                                                                           
