<?php
/*
plugin-name: Dansk overs&aelig;ttelse til FLog
plugin-url: http://flog.frac.dk
plugin-version: 1.1.1
plugin-description: Overs&aelig;tter FLog til Dansk
author-name: Goatie
author-url: http://atg.frac.dk/
*/
$GLOBALS['FLog_strings']['da'] = array(
			'admin.home'            => 'Hjem',
			'admin.home.version'    => 'Version: %0',
			'admin.home.posts'      => 'Poster: %0',
			'admin.home.pages'      => 'Sider: %0',
			'admin.home.comments'   => 'Kommentarer: %0',
			'admin.home.links'      => 'Links: %0',
			'admin.home.cats'       => 'Kategorier: %0',
			'admin.home.users'      => 'Brugere: %0',

			'admin.plugins'         => 'Plugins',
			'admin.plugins.name'    => 'Navn',
			'admin.plugins.author'  => 'Forfatter',
			'admin.plugins.version' => 'Version',
			'admin.plugins.description' => 'Beskrivelse',
			'admin.plugins.action'  => 'Handling',
			'admin.plugins.enable'  => 'Aktiver',
			'admin.plugins.disable' => 'Deaktiver',

			'admin.themes' => 'Temaer',
			'admin.themes.name' => 'Navn',
			'admin.themes.author' => 'Forfatter',
			'admin.themes.version' => 'Version',
			'admin.themes.description' => 'Beskrivelse',
			'admin.themes.action' => 'Handling',
			'admin.themes.select' => 'V&aelig;lg',
			'admin.themes.default.name' => 'FLog Standard',
			'admin.themes.default.description' => 'FLog\'s standard tema',

			'admin.logintext'       => 'Du er logget ind som <em>%0</em>. [<a href="%1">Log Ud</a> | <a href="%2">Bes&oslash;g Side</a>]',
			'admin.logout'          => 'Log Ud',

			'admin.login'           => 'Log Ind',
			'admin.login.fail'      => 'Forkert brugernavn eller kodeord.',
			'admin.login.logout'    => 'Du er nu logget ud.',
			'admin.login.username'  => 'Brugernavn:',
			'admin.login.password'  => 'Kodeord:',
			'admin.login.remember'  => 'Husk Mig',
			'admin.login.submit'    => 'Log Ind',
			'admin.login.reset'     => 'Nulstil',

			'admin.config.general' => 'Generel Konfiguration',
			'admin.config.general.blog' => 'Blog',
			'admin.config.general.blog.name' => 'Blog Navn:',
			'admin.config.general.blog.tagline' => 'Tagline:',
			'admin.config.general.blog.footer' => 'Footer:',
			'admin.config.general.blog.language' => 'Sprog:',
			'admin.config.general.meta' => 'Meta',
			'admin.config.general.meta.description' => 'Beskrivelse:',
			'admin.config.general.meta.author' => 'Forfatter:',
			'admin.config.general.meta.keywords' => 'N&oslash;gleord:',
			'admin.config.general.display' => 'Visning',
			'admin.config.general.display.postsort' => 'Post sorterings orden:',
			'admin.config.general.display.postsort.asc' => 'Stigende',
			'admin.config.general.display.postsort.desc' => 'Faldende',
			'admin.config.general.display.commentsort' => 'Kommentar sorterings orden:',
			'admin.config.general.display.commentsort.asc' => 'Stigende',
			'admin.config.general.display.commentsort.desc' => 'Faldende',
			'admin.config.general.display.numposts' => 'Antal poster der vises p&aring; en gang:',
			'admin.config.general.display.feedposts' => 'Antal poster der vises i RSS og Atom feeds:',
			'admin.config.general.time' => 'Dato/Tid',
			'admin.config.general.time.now' => 'Nuv&aelig;rende <acronym title="Coordinated Universal Time">UTC</acronym> er: %0 %1.',
			'admin.config.general.time.offset' => 'Afvigning fra UTC (i timer):',
			'admin.config.general.time.dateformat' => 'Dato format (samme format som <a href="http://www.php.net/date">PHP\'s <code>date</code> funktion</a>):',
			'admin.config.general.time.timeformat' => 'Tids format (igen, samme som <a href="http://www.php.net/date"><code>date</code></a>):',
			'admin.config.general.submit' => 'Godkend',
			'admin.config.general.error.database' => 'Kunne ikke skrive til database.',
			'admin.config.general.message.success' => 'Konfiguration gemt.',

			'admin.config.display' => 'Visnings Konfiguration',
			'admin.config.display.display' => 'Visning',
			'admin.config.display.display.postsort' => 'Post sorterings orden:',
			'admin.config.display.display.postsort.asc' => 'Stigende',
			'admin.config.display.display.postsort.desc' => 'Faldende',
			'admin.config.display.display.commentsort' => 'Kommenter sorterings orden:',
			'admin.config.display.display.commentsort.asc' => 'Stigende',
			'admin.config.display.display.commentsort.desc' => 'Faldende',
			'admin.config.display.display.linksort' => 'Link sorterings orden:',
			'admin.config.display.display.linksort.asc' => 'Stigende',
			'admin.config.display.display.linksort.desc' => 'Faldende',
			'admin.config.display.display.linktype' => 'Links side:',
			'admin.config.display.display.linktype.all' => 'Enkelt Side',
			'admin.config.display.display.linktype.cats' => 'Kategorier',
			'admin.config.display.display.linktype.archive' => 'Arkiv',
			'admin.config.display.display.numposts' => 'Antal poster der vises p&aring; en gang:',
			'admin.config.display.display.feedposts' => 'Antal poster der vises i RSS og Atom feeds:',
			'admin.config.display.display.numlinks' => 'Antal links der vises p&aring; en gang:',
			'admin.config.display.display.feedlinks' => 'Antal links der vises i RSS og Atom feeds:',
			'admin.config.display.submit' => 'Godkend',
			'admin.config.display.error.database' => 'Kunne ikke skrive til database.',
			'admin.config.display.message.success' => 'Konfiguration gemt.',

			'admin.config.discussion' => 'Diskussions Konfiguration',
			'admin.config.discussion.comments' => 'Kommentarer',
			'admin.config.discussion.comments.markup' => 'Markup:',
			'admin.config.discussion.comments.markup.choice' => '(Tillad bruger at v&aelig;lge)',
			'admin.config.discussion.comments.markup.none' => '(X)HTML',
			'admin.config.discussion.comments.staletimeout' => 'Antal dage f&oslash;r l&aring;sning af gamle diskussioner (nul eller tomt felt for at deaktivere):',
			'admin.config.discussion.comments.oldtimeout' => 'Antal dage efter postnings dato f&oslash;r l&aring;sning af diskussioner (nul eller tomt felt for at deaktivere):',
			'admin.config.discussion.comments.anonymous' => 'Tillad kommentarer fra anonyme brugere',
			'admin.config.discussion.comments.blockip' => 'Bloker kommentarer fra ulogiske IPer',
			'admin.config.discussion.comments.blockreferrer' => 'Bloker kommentarer fra d&aring;rlige henvisninger',
			'admin.config.discussion.comments.modall' => 'Moderer alle kommentarer',
			'admin.config.discussion.comments.modrepeat' => 'Moderer kommentarer fra postere som ikke har mindst en godkendt kommentar',
			'admin.config.discussion.comments.emailmod' => 'E-mail post forfatter hver gang en kommentar er modereret',
			'admin.config.discussion.comments.emailall' => 'E-mail post forfatter hver gang en kommentar er postet',
			'admin.config.discussion.comments.maxsize' => 'Maximum st&oslash;rrelse af kommentarer (i bytes, nul eller tomt felt for at deaktivere):',
			'admin.config.discussion.submit' => 'Godkend',
			'admin.config.discussion.error.database' => 'Kunne ikke skrive til database.',
			'admin.config.discussion.message.success' => 'Konfiguration gemt.',

			'admin.config.permissions' => 'Adgangs Konfiguration',
			'admin.config.permissions.global' => 'Admin (nul eller tomt felt for at tillade alle brugere)',
			'admin.config.permissions.global.plugins' => 'Aktiver/Deaktiver Plugins:',
			'admin.config.permissions.global.themes' => 'Skift Temaer:',
			'admin.config.permissions.write' => 'Skriv (nul eller tomt felt for at tillade alle brugere)',
			'admin.config.permissions.write.posts' => 'Skriv Poster:',
			'admin.config.permissions.write.pages' => 'Skriv Sider:',
			'admin.config.permissions.manage' => 'H&aring;ndtering (nul eller tomt felt for at tillade alle brugere)',
			'admin.config.permissions.manage.posts' => 'H&aring;ndter Poster:',
			'admin.config.permissions.manage.pages' => 'H&aring;ndter Sider:',
			'admin.config.permissions.manage.comments' => 'H&aring;ndter Kommentarer:',
			'admin.config.permissions.manage.categories' => 'H&aring;ndter Kategorier:',
			'admin.config.permissions.manage.users' => 'H&aring;ndter Brugere (alle brugere kan &aelig;ndre deres egne informationer):',
			'admin.config.permissions.manage.links' => 'H&aring;ndter Links:',
			'admin.config.permissions.manage.files' => 'H&aring;ndter Filer:',
			'admin.config.permissions.config' => 'Konfiguration (nul eller tomt felt for at tillade alle brugere)',
			'admin.config.permissions.config.general' => 'Generel Konfiguration:',
			'admin.config.permissions.config.display' => 'Visnings Konfiguration:',
			'admin.config.permissions.config.discussion' => 'Diskussions Konfiguration:',
			'admin.config.permissions.config.permissions' => 'Adgangs Konfiguration:',
			'admin.config.permissions.submit' => 'Godkend',
			'admin.config.permissions.error.database' => 'Kunne ikke skrive til database.',
			'admin.config.permissions.message.success' => 'Konfiguration gemt.',

			'admin.manage.users' => 'H&aring;ndter Brugere',
			'admin.manage.users.id' => 'ID',
			'admin.manage.users.username' => 'Brugernavn',
			'admin.manage.users.name' => 'Navn',
			'admin.manage.users.url' => 'URL',
			'admin.manage.users.email' => 'E-mail',
			'admin.manage.users.rank' => 'Rang',
			'admin.manage.users.action' => 'Handling',
			'admin.manage.users.edit' => 'Rediger',
			'admin.manage.users.edit.confirm' => 'Rediger',
			'admin.manage.users.edit.cancel' => 'Annuller',
			'admin.manage.users.delete' => 'Slet',
			'admin.manage.users.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.users.delete.confirm' => 'Ja',
			'admin.manage.users.delete.cancel' => 'Nej',
			'admin.manage.users.new' => 'Opret Ny Bruger',
			'admin.manage.users.new.username' => 'Brugernavn:',
			'admin.manage.users.new.password' => 'Kodeord (to gange):',
			'admin.manage.users.new.rank' => 'Rang:',
			'admin.manage.users.new.submit' => 'Opret',
			'admin.manage.users.password' => '&AElig;ndre Kodeord',
			'admin.manage.users.password.oldpassword' => 'Gammelt Kodeord:',
			'admin.manage.users.password.newpassword' => 'Nyt Kodeord (to gange):',
			'admin.manage.users.password.submit' => '&AElig;ndre',
			'admin.manage.users.error.database' => 'Kunne ikke skrive til database.',
			'admin.manage.users.error.setrank' => 'Du kan ikke s&aelig;tte en brugers rang til at v&aelig;re mindre end eller lig din egen.',
			'admin.manage.users.error.newrank' => 'Du kan ikke oprette en bruger med en rang som er mindre end eller lig din egen.',
			'admin.manage.users.error.usernametaken' => 'Det valgte brugernavn bliver allerede brugt.',
			'admin.manage.users.error.invalidusername' => 'Det valgte brugernavn er ugyldigt. Brugernavne skal v&aelig;re mellem to (2) og seksten (16) tegn og m&aring; kun indeholde sm&aring; bogstaver, tal, bindestreg og understreg (a&ndash;z, 0&ndash;9, -, _).',
			'admin.manage.users.error.newpasswordmatch' => 'De indtastede kodeord matcher ikke sammen.',
			'admin.manage.users.error.wrongpassword' => 'Du har indtastet et ukorrekt kodeord',
			'admin.manage.users.error.changepasswordmatch' => 'De nye kodeord du har indtastet matcher ikke sammen.',
			'admin.manage.users.message.editsuccess' => 'Brugeren er redigeret.',
			'admin.manage.users.message.editcancel' => 'Redigering annulleret.',
			'admin.manage.users.message.deletesuccess' => 'Brugeren er slettet.',
			'admin.manage.users.message.deletecancel' => 'Sletning annulleret.',
			'admin.manage.users.message.newsuccess' => 'Brugeren er oprettet.',
			'admin.manage.users.message.passwordsuccess' => 'Dit kodeord er &aelig;ndret.',

			'admin.manage.cats' => 'H&aring;ndter Kategorier',
			'admin.manage.cats.id' => 'ID',
			'admin.manage.cats.name' => 'Navn',
			'admin.manage.cats.description' => 'Beskrivelse',
			'admin.manage.cats.showblog' => 'Blog',
			'admin.manage.cats.showlinks' => 'Side',
			'admin.manage.cats.showlinks.yes' => 'Ja',
			'admin.manage.cats.showlinks.no' => 'Nej',
			'admin.manage.cats.posts' => 'Poster',
			'admin.manage.cats.links' => 'Links',
			'admin.manage.cats.action' => 'Handling',
			'admin.manage.cats.edit' => 'Rediger',
			'admin.manage.cats.edit.confirm' => 'Rediger',
			'admin.manage.cats.edit.cancel' => 'Annuller',
			'admin.manage.cats.delete' => 'Slet',
			'admin.manage.cats.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.cats.delete.confirm' => 'Ja',
			'admin.manage.cats.delete.cancel' => 'Nej',
			'admin.manage.cats.new' => 'Opret Ny Kategori',
			'admin.manage.cats.new.name' => 'Navn:',
			'admin.manage.cats.new.description' => 'Beskrivelse:',
			'admin.manage.cats.new.showblog' => 'Antal Links der skal vises i Blog (Kun Link Kategorier, nul eller tomt felt for at deaktivere):',
			'admin.manage.cats.new.showlinks' => 'Vis denne kategori p&aring; Links siden (Kun Links Kategorier).',
			'admin.manage.cats.new.submit' => 'Opret Kategori',
			'admin.manage.cats.new.submitlink' => 'Opret Link Kategori',
			'admin.manage.cats.recalc' => 'Omregn Totaler',
			'admin.manage.cats.error.database' => 'Kunne ikke skrive til database.',
			'admin.manage.cats.message.editsuccess' => 'Kategorien er redigeret.',
			'admin.manage.cats.message.editcancel' => 'Redigering annulleret.',
			'admin.manage.cats.message.deletesuccess' => 'Kategorien er slettet.',
			'admin.manage.cats.message.deletecancel' => 'Sletning annulleret.',
			'admin.manage.cats.message.newsuccess' => 'Kategorien er oprettet.',

			'admin.manage.posts' => 'H&aring;ndter Poster',
			'admin.manage.posts.id' => 'ID',
			'admin.manage.posts.title' => 'Titel',
			'admin.manage.posts.time' => 'Dato',
			'admin.manage.posts.time.display' => '%0',
			'admin.manage.posts.author' => 'Forfatter',
			'admin.manage.posts.cats' => 'Kategorier',
			'admin.manage.posts.comments' => 'Kommentarer',
			'admin.manage.posts.status' => 'Status',
			'admin.manage.posts.status.draft' => 'kladde',
			'admin.manage.posts.status.delay' => 'uds&aelig;ttelse',
			'admin.manage.posts.status.both' => 'klade | uds&aelig;ttelse',
			'admin.manage.posts.action' => 'Handling',
			'admin.manage.posts.edit' => 'Rediger',
			'admin.manage.posts.delete' => 'Slet',
			'admin.manage.posts.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.posts.delete.confirm' => 'Ja',
			'admin.manage.posts.delete.cancel' => 'Nej',
			'admin.manage.posts.each' => 'Antal poster per side:',
			'admin.manage.posts.each.submit' => 'Skift',
			'admin.manage.posts.recalc' => 'Omregn Kommentarer',
			'admin.manage.posts.error.database' => 'Kunne ikke skrive til database.',
			'admin.manage.posts.message.deletesuccess' => 'Posten er slettet.',
			'admin.manage.posts.message.deletecancel' => 'Sletning annulleret.',

			'admin.manage.comments' => 'H&aring;ndter Kommentarer',
			'admin.manage.comments.id' => 'ID',
			'admin.manage.comments.post' => 'Post',
			'admin.manage.comments.name' => 'Navn',
			'admin.manage.comments.email' => 'E-mail',
			'admin.manage.comments.text' => 'Tekst',
			'admin.manage.comments.time' => 'Dato',
			'admin.manage.comments.time.display' => '%0',
			'admin.manage.comments.status' => 'Status',
			'admin.manage.comments.status.moderated' => 'modereret',
			'admin.manage.comments.action' => 'Handling',
			'admin.manage.comments.approve' => 'Godkend',
			'admin.manage.comments.edit' => 'Rediger',
			'admin.manage.comments.edit.name' => 'Navn:',
			'admin.manage.comments.edit.email' => 'E-mail:',
			'admin.manage.comments.edit.url' => 'URL:',
			'admin.manage.comments.edit.markup' => 'Markup:',
			'admin.manage.comments.edit.markup.none' => '(X)HTML',
			'admin.manage.comments.edit.text' => 'Tekst:',
			'admin.manage.comments.edit.preview' => 'Forevisning',
			'admin.manage.comments.edit.previewbox' => 'Forevisning',
			'admin.manage.comments.edit.submit' => 'Rediger',
			'admin.manage.comments.edit.cancel' => 'Annuller',
			'admin.manage.comments.delete' => 'Slet',
			'admin.manage.comments.delete.message' => 'Er du sikker p&aring; du vil slette denne kommentar?',
			'admin.manage.comments.delete.confirm' => 'Ja',
			'admin.manage.comments.delete.cancel' => 'Nej',
			'admin.manage.comments.each' => 'Antal kommentarer per side:',
			'admin.manage.comments.each.submit' => 'Skift',
			'admin.manage.comments.showtext' => 'Vis fuld tekst for:',
			'admin.manage.comments.showtext.mod' => 'modererede kommentarer',
			'admin.manage.comments.showtext.all' => 'alle kommentarer',
			'admin.manage.comments.showtext.none' => 'vis ikke fuld tekst',
			'admin.manage.comments.showtext.submit' => 'Skift',
			'admin.manage.comments.error.database' => 'Kunne ikke skrive til database.',
			'admin.manage.comments.message.approve' => 'Kommentaren er godkendt.',
			'admin.manage.comments.message.editsuccess' => 'Kommentaren er redigeret.',
			'admin.manage.comments.message.editcancel' => 'Redigering annulleret',
			'admin.manage.comments.message.deletesuccess' => 'Kommentaren er slettet.',
			'admin.manage.comments.message.deletecancel' => 'Sletning annulleret.',

			'admin.manage.pages' => 'H&aring;ndter Sider',
			'admin.manage.pages.id' => 'ID',
			'admin.manage.pages.title' => 'Titel',
			'admin.manage.pages.url' => 'URL',
			'admin.manage.pages.action' => 'Handling',
			'admin.manage.pages.edit' => 'Rediger',
			'admin.manage.pages.edit.confirm' => 'Rediger',
			'admin.manage.pages.edit.cancel' => 'Annuller',
			'admin.manage.pages.delete' => 'Slet',
			'admin.manage.pages.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.pages.delete.confirm' => 'Ja',
			'admin.manage.pages.delete.cancel' => 'Nej',
			'admin.manage.pages.up' => '&#8593;',
			'admin.manage.pages.down' => '&#8595;',
			'admin.manage.pages.show' => 'Vis',
			'admin.manage.pages.hide' => 'Gem',
			'admin.manage.pages.new' => 'Opret Ny Side',
			'admin.manage.pages.new.title' => 'Titel:',
			'admin.manage.pages.new.url' => 'URL (efterlad tom for at lave en seperator):',
			'admin.manage.pages.new.where' => 'Inds&aelig;t Efter:',
			'admin.manage.pages.where.top' => '(Top)',
			'admin.manage.pages.where.separator' => '%0',
			'admin.manage.pages.where.link' => '%0',
			'admin.manage.pages.where.page' => '%0',
			'admin.manage.pages.new.submit' => 'Opret',
			'admin.manage.pages.error.database' => 'Database fejl.',
			'admin.manage.pages.message.editsuccess' => 'Siden er redigeret.',
			'admin.manage.pages.message.editcancel' => 'Redigering annulleret.',
			'admin.manage.pages.message.deletesuccess' => 'Siden er slettet.',
			'admin.manage.pages.message.deletecancel' => 'Sletning annulleret.',
			'admin.manage.pages.message.show' => 'Siden er tilf&oslash;jet til menuen.',
			'admin.manage.pages.message.hide' => 'Siden er fjernet fra menuen.',
			'admin.manage.pages.message.newentry' => 'Siden er oprettet.',

			'admin.manage.links' => 'H&aring;ndter Links',
			'admin.manage.links.id' => 'ID',
			'admin.manage.links.title' => 'Titel',
			'admin.manage.links.url' => 'URL',
			'admin.manage.links.time' => 'Dato',
			'admin.manage.links.time.display' => '%0',
			'admin.manage.links.author' => 'Forfatter',
			'admin.manage.links.cats' => 'Kategorier',
			'admin.manage.links.status' => 'Status',
			'admin.manage.links.status.sticky' => 'sticky',
			'admin.manage.links.action' => 'Handling',
			'admin.manage.links.edit' => 'Rediger',
			'admin.manage.links.delete' => 'Slet',
			'admin.manage.links.edit.now' => 'Nu',
			'admin.manage.links.edit.sticky' => 'Sticky',
			'admin.manage.links.edit.confirm' => 'Rediger',
			'admin.manage.links.edit.cancel' => 'Annuller',
			'admin.manage.links.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.links.delete.confirm' => 'Ja',
			'admin.manage.links.delete.cancel' => 'Nej',
			'admin.manage.links.each' => 'Antal links per side:',
			'admin.manage.links.each.submit' => 'Skift',
			'admin.manage.links.new' => 'Opret Nyt Link',
			'admin.manage.links.new.title' => 'Titel:',
			'admin.manage.links.new.url' => 'URL:',
			'admin.manage.links.new.cats' => 'Kategorier:',
			'admin.manage.links.new.sticky' => 'Sticky',
			'admin.manage.links.new.submit' => 'Opret',
			'admin.manage.links.error.database' => 'Kunne ikke skrive til database.',
			'admin.manage.links.message.createsuccess' => 'Linket er oprettet.',
			'admin.manage.links.message.editsuccess' => 'Linket er redigeret.',
			'admin.manage.links.message.editcancel' => 'Redigering annulleret.',
			'admin.manage.links.message.deletesuccess' => 'Linket er slettet.',
			'admin.manage.links.message.deletecancel' => 'Sletning annulleret.',

			'admin.manage.files' => 'H&aring;ndter Filer',
			'admin.manage.files.currentdir' => 'Nuv&aelig;rende Mappe: <kbd>%0</kbd>',
			'admin.manage.files.filename' => 'Navn',
			'admin.manage.files.filesize' => 'St&oslash;rrelse',
			'admin.manage.files.action' => 'Handling',
			'admin.manage.files.rename' => 'Omd&oslash;b',
			'admin.manage.files.rename.confirm' => 'Omd&oslash;b',
			'admin.manage.files.rename.cancel' => 'Annuller',
			'admin.manage.files.delete' => 'Slet',
			'admin.manage.files.delete.message' => 'Er du sikker p&aring; du vil slette <em>%0</em>?',
			'admin.manage.files.delete.confirm' => 'Ja',
			'admin.manage.files.delete.cancel' => 'Nej',
			'admin.manage.files.upload' => 'Upload',
			'admin.manage.files.upload.filename' => 'Filnavn:',
			'admin.manage.files.upload.submit' => 'Upload',
			'admin.manage.files.newdir' => 'Opret Ny Mappe',
			'admin.manage.files.newdir.dirname' => 'Mappe Navn:',
			'admin.manage.files.newdir.submit' => 'Opret',
			'admin.manage.files.message.newdirsuccess' => 'Mappe Oprettet.',
			'admin.manage.files.message.uploadsuccess' => 'Fil Uploaded.',
			'admin.manage.files.message.renamefilesuccess' => 'Fil Omd&oslash;bt.',
			'admin.manage.files.message.renamedirsuccess' => 'Mappe Omd&oslash;bt.',
			'admin.manage.files.message.renamecancel' => 'Rename Cancelled.',
			'admin.manage.files.message.deletecancel' => 'Seltning Annulleret.',
			'admin.manage.files.message.deletedirsuccess' => 'Mappe Slettet.',
			'admin.manage.files.message.deletefilesuccess' => 'Fil Slettet.',
			'admin.manage.files.error.dirname' => 'Ugyldigt Mappe Navn.',
			'admin.manage.files.error.newdirfail' => 'Kunne ikke oprette mappe.',
			'admin.manage.files.error.badfile' => 'Fil Fejl. Se venligst efter om st&oslash;rrelsen p&aring; din fil er mindre end '.ini_get('upload_max_filesize').'.',
			'admin.manage.files.error.uploadfail' => 'Kunne ikke Uploade Fil',
			'admin.manage.files.error.badfilename' => 'Ugyldigt Filnavn.',
			'admin.manage.files.error.renamefilefail' => 'Kunne ikke Omd&oslash;be Fil.',
			'admin.manage.files.error.baddirname' => 'Ugyldigt Mappe Navn.',
			'admin.manage.files.error.renamedirfail' => 'Kunne ikke Omd&oslash;be Mappe.',
			'admin.manage.files.error.deletefilefail' => 'Kunne ikke slette Fil.',
			'admin.manage.files.error.deletedirfail' => 'Kunne ikke slette Mappe. Se venligst efter om mappen er tom.',
			'admin.manage.files.error.readdir' => 'Kunne ikke l&aelig;se fra Mappe.',

			'admin.write.posts' => 'Skriv Poster',
			'admin.write.posts.edit' => 'Rediger Post',
			'admin.write.posts.title' => 'Titel:',
			'admin.write.posts.markup' => 'Markup:',
			'admin.write.posts.markup.none' => '(X)HTML',
			'admin.write.posts.cats' => 'Kategorier',
			'admin.write.posts.time' => 'Dato/Tid:',
			'admin.write.posts.time.now' => 'S&aelig;t til Nu',
			'admin.write.posts.comments' => 'Tillad Kommentarer',
			'admin.write.posts.draft' => 'Kladde',
			'admin.write.posts.delay' => 'Uds&aelig;t Post',
			'admin.write.posts.text' => 'Tekst:',
			'admin.write.posts.preview' => 'Forevisning',
			'admin.write.posts.submit' => 'Godkend',
			'admin.write.posts.previewbox' => 'Forevisning',
			'admin.write.posts.message.editsuccess' => 'Din post er redigeret.',
			'admin.write.posts.message.success' => 'Din post er tilf&oslash;jet.',
			'admin.write.posts.message.success.view' => '<a href="%0">Vis denne post</a>',
			'admin.write.posts.message.success.edit' => '<a href="%0">Rediger denne post</a>',
			'admin.write.posts.message.success.more' => '<a href="%0">Skriv en anden post</a>',
			'admin.write.posts.message.success.manage' => '<a href="%0">H&aring;ndter poster</a>',
			'admin.write.posts.error.database' => 'Database fejl.',
			'admin.write.posts.error.permissions' => 'Du har ikke tilladelse til at redigere denne post.',
			'admin.write.posts.error.notfound' => 'Post ikke fundet.',

			'admin.write.pages' => 'Skriv Sider',
			'admin.write.pages.edit' => 'Rediger Side',
			'admin.write.pages.title' => 'Titel:',
			'admin.write.pages.markup' => 'Markup:',
			'admin.write.pages.markup.none' => '(X)HTML',
			'admin.write.pages.id' => 'ID:',
			'admin.write.pages.where' => 'Inds&aelig;t Efter:',
			'admin.write.pages.where.none' => '(Usynlig)',
			'admin.write.pages.where.top' => '(Top)',
			'admin.write.pages.where.separator' => '%0',
			'admin.write.pages.where.link' => '%0',
			'admin.write.pages.where.page' => '%0',
			'admin.write.pages.text' => 'Tekst:',
			'admin.write.pages.preview' => 'Forevisning',
			'admin.write.pages.submit' => 'Godkend',
			'admin.write.pages.previewbox' => 'Forevisning',
			'admin.write.pages.message.editsuccess' => 'Din side er redigeret.',
			'admin.write.pages.message.success' => 'Din side er tilf&oslash;jet.',
			'admin.write.pages.message.success.view' => '<a href="%0">Vis denne side</a>',
			'admin.write.pages.message.success.edit' => '<a href="%0">Rediger denne side</a>',
			'admin.write.pages.message.success.more' => '<a href="%0">Skriv en anden side</a>',
			'admin.write.pages.message.success.manage' => '<a href="%0">H&aring;ndter sider</a>',
			'admin.write.pages.error.database' => 'Database fejl.',
			'admin.write.pages.error.id' => 'ID allerede i brug.',
			'admin.write.pages.error.notfound' => 'Side ikke fundet.',
			'admin.write.pages.error.noid' => 'Du skrev ikke noget ID.',

			'admin.stats.overall' => 'Samlede Statestikker',
			'admin.stats.overall.browsers' => 'Browsere',
			'admin.stats.overall.systems' => 'Styre Systemer',
			'admin.stats.overall.posts' => 'Poster',
			'admin.stats.overall.pages' => 'Sider',
			'admin.stats.overall.total' => 'Total: %0 / %1',
			'admin.stats.overall.year' => 'Dette &Aring;r: %0 / %1',
			'admin.stats.overall.month' => 'Denne M&aring;ned: %0 / %1',
			'admin.stats.overall.day' => 'Idag: %0 / %1',
			'admin.stats.overall.hour' => 'Denne Time: %0 / %1',

			'admin.stats.graphs' => 'Statistik Diagrammer',
			'admin.stats.graphs.hours' => 'Timer:',
			'admin.stats.graphs.days' => 'Dage:',
			'admin.stats.graphs.months' => 'M&aring;neder:',
			'admin.stats.graphs.months.01' => 'Jan',
			'admin.stats.graphs.months.02' => 'Feb',
			'admin.stats.graphs.months.03' => 'Mar',
			'admin.stats.graphs.months.04' => 'Apr',
			'admin.stats.graphs.months.05' => 'Maj',
			'admin.stats.graphs.months.06' => 'Jun',
			'admin.stats.graphs.months.07' => 'Jul',
			'admin.stats.graphs.months.08' => 'Aug',
			'admin.stats.graphs.months.09' => 'Sep',
			'admin.stats.graphs.months.10' => 'Okt',
			'admin.stats.graphs.months.11' => 'Nov',
			'admin.stats.graphs.months.12' => 'Dec',
			'admin.stats.graphs.years' => '&Aring;r:',

			'admin.stats.recent' => 'Seneste Bes&oslash;gende',
			'admin.stats.recent.time' => 'Tid',
			'admin.stats.recent.time.display' => '%0, %1',
			'admin.stats.recent.ip' => 'IP',
			'admin.stats.recent.browser' => 'Browser',
			'admin.stats.recent.system' => 'Styre System',
			'admin.stats.recent.hits' => 'Kliks',

			'admin.menu.home'             => 'Hjem',
			'admin.menu.plugins'          => 'Plugins',
			'admin.menu.themes'           => 'Temaer',
			'admin.menu.logout'           => 'Log Ud',
			'admin.menu.manage'           => 'H&aring;ndter',
			'admin.menu.manage.posts'       => 'Poster',
			'admin.menu.manage.pages'       => 'Sider',
			'admin.menu.manage.links'       => 'Links',
			'admin.menu.manage.cats'        => 'Kategorier',
			'admin.menu.manage.comments'    => 'Kommentarer',
			'admin.menu.manage.users'       => 'Brugere',
			'admin.menu.manage.files'       => 'Filer',
			'admin.menu.config'           => 'Konfiguration',
			'admin.menu.config.general'     => 'Generel',
			'admin.menu.config.discussion'  => 'Diskussion',
			'admin.menu.config.display'     => 'Visning',
			'admin.menu.config.permissions' => 'Adgang',
			'admin.menu.write'            => 'Skriv',
			'admin.menu.write.posts'        => 'Poster',
			'admin.menu.write.pages'        => 'Sider',
			'admin.menu.stats'            => 'Statistikker',
			'admin.menu.stats.overall'      => 'Samlede',
			'admin.menu.stats.graphs'       => 'Diagrammer',
			'admin.menu.stats.recent'       => 'Bes&oslash;gende',

			'comment.email.moderated.subject' => 'Nogen har kommenteret din post.',
			'comment.email.moderated' => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) har kommenteret din post, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%5">Godkend</a> | <a href="%6">Rediger</a> | <a href="%7">Slet</a> ]</p>',
			'comment.email.approved.subject' => 'Nogen har kommenteret din post.',
			'comment.email.approved'  => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) har kommenteret din post, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%6">Rediger</a> | <a href="%7">Slet</a> ]</p>',

			// ---------------------------------------------------------------

			'theme.!default.post.nocomments' => 'Ingen kommentarer',
			'theme.!default.post.onecomment' => '1 kommentar',
			'theme.!default.post.numcomments' => '%0 kommentarer',

			'theme.!default.post.header' => 'Postet af %0 den %1 klokken %2',
			'theme.!default.post.header.anon' => 'Postet den %0 klokken %1',

			'theme.!default.index.next' => 'N&aelig;ste &#8594;',
			'theme.!default.index.prev' => '&#8592; Forrige',

			'theme.!default.page404' => '404: Side Ikke Fundet',
			'theme.!default.page404.message' => 'Siden du kiggede efter eksisterer ikke.',

			'theme.!default.post404' => '404: Post Ikke Fundet',
			'theme.!default.post404.message' => 'Posten du kiggede efter eksisterer ikke.',

			'theme.!default.nav' => 'Navigation',
			'theme.!default.nav.home' => 'Hjem',
			'theme.!default.nav.cats' => 'Kategorier',
			'theme.!default.nav.links' => 'Links',
			'theme.!default.nav.archives' => 'Arkiver',
			'theme.!default.nav.archives.posts' => 'Poster',
			'theme.!default.nav.archives.links' => 'Links',

			'theme.!default.linkback' => 'Drevet af <a href="http://www.fluffington.com/" style="color:inherit;text-decoration:inherit;">FLog</a>',

			'theme.!default.commentform' => 'Kommenter Denne Post',
			'theme.!default.commentform.name' => 'Navn (kr&aelig;ves):',
			'theme.!default.commentform.email' => 'E-mail (kr&aelig;ves, bliver ikke vist):',
			'theme.!default.commentform.url' => 'URL:',
			'theme.!default.commentform.markup' => 'Markup:',
			'theme.!default.commentform.markup.none' => '(X)HTML',
			'theme.!default.commentform.text' => 'Tekst:',
			'theme.!default.commentform.text.markup' => 'Text (%0):',
			'theme.!default.commentform.preview' => 'Forevisning',
			'theme.!default.commentform.submit' => 'Godkend',
			'theme.!default.commentform.previewbox' => 'Forevisning',
			'theme.!default.commentform.error.namemail' => 'Du skal skrive dit navn og din e-mail adresse.',
			'theme.!default.commentform.error.anonymous' => 'Anonyme brugere har ikke tilladelse til at poste kommentarer.',
			'theme.!default.commentform.error.ip' => 'Din kommentar blev blokeret fordi din IP adresse ikke er den samme som blev brugt da formularen blev hentet.',
			'theme.!default.commentform.error.referrer' => 'Din kommentar blev blokeret pga. en d&aring;rlig henvisning.',
			'theme.!default.commentform.error.allowcomments' => 'Kommentarer er ikke tilladt i denne post.',
			'theme.!default.commentform.error.blocked' => 'Din kommentar blev blokeret.',
			'theme.!default.commentform.error.database' => 'Database fejl.',
			'theme.!default.commentform.error.maxsize' => 'Din kommentar har overskredet den tilladte maximumsl&aelig;ngde p&aring; %0 tegn.',
			'theme.!default.commentform.message.moderated' => 'Din kommentar er blevet modereret. Den vil fremkomme s&aring; snart en moderator godkender den.',
			'theme.!default.commentform.message.posted' => 'Din kommentar er blevet postet.',

			'theme.!default.error.database' => 'Database fejl.',
			'theme.!default.error.allowcomments' => 'Kommentarer er ikke tilladt i denne post.',
			'theme.!default.error.maxsize' => 'Din kommentar har overskredet den tilladte maximumsl&aelig;ngde p&aring; %0 bytes.',
			'theme.!default.error.anonymous' => 'Anonyme brugere har ikke tilladelse til at poste kommentarer.',
			'theme.!default.error.ip' => 'Din kommentar blev blokeret fordi din IP adresse ikke er den samme som blev brugt da formularen blev hentet. Hvis du er bag en proxy og har modtaget denne besked ved en fejl, s&aring; pr&oslash;v venligst igen.',
			'theme.!default.error.referrer' => 'Din kommentar blev blokeret pga. en d&aring;rlig henvisning.',
			'theme.!default.error.nameemail' => 'Du skal indtaste et navn og en gyldig e-mail adresse.',
			'theme.!default.message.moderated' => 'Din kommentar er blevet modereret. Den vil blive synlig for andre s&aring; snart en moderator har set og godkendt den.',
			'theme.!default.message.posted' => 'Din kommenter er blevet postet.',

			'theme.!default.archive.message' => 'Arkiv for %0',
			'theme.!default.archive.message.cat' => '%1, arkiv for %0',
			'theme.!default.archive.links.message' => 'Link arkiv for %0',
			'theme.!default.archive.links.message.cat' => '%1, link arkiv for %0',
			'theme.!default.archive.posts' => 'Post Arkiv',
			'theme.!default.archive.links' => 'Link Arkiv',
			'theme.!default.archive.view' => 'vis',
			'theme.!default.archive.months.01' => 'Januar',
			'theme.!default.archive.months.02' => 'Februar',
			'theme.!default.archive.months.03' => 'Marts',
			'theme.!default.archive.months.04' => 'April',
			'theme.!default.archive.months.05' => 'Maj',
			'theme.!default.archive.months.06' => 'Juni',
			'theme.!default.archive.months.07' => 'Juli',
			'theme.!default.archive.months.08' => 'August',
			'theme.!default.archive.months.09' => 'September',
			'theme.!default.archive.months.10' => 'Oktober',
			'theme.!default.archive.months.11' => 'November',
			'theme.!default.archive.months.12' => 'December',
			'theme.!default.archive.time.display' => '%1',

	);

$GLOBALS['FLog_lang_list']['da'] = 'Dansk (Goatie)';

?>
