<?php
/*
plugin-name: French Language Plug-in
plugin-url: http://www.musicalboxquebec.com
plugin-version: 1.1.1
plugin-description: Traduction francaise compatible avec la version 1.0.1 de Flog
author-name: Pierre Plamondon (MusicalBox)
author-url: http://www.musicalboxquebec.com
*/

$GLOBALS['FLog_strings']['fr'] = array(
			'admin.home'            => 'Accueil',
			'admin.home.version'    => 'Version: %0',
			'admin.home.posts'      => 'Articles: %0',
			'admin.home.pages'      => 'Pages: %0',
			'admin.home.comments'   => 'Commentaires: %0',
			'admin.home.links'      => 'Liens: %0',
			'admin.home.cats'       => 'Cat&eacute;gories: %0',
			'admin.home.users'      => 'Utilisateurs: %0',

			'admin.plugins'         => 'Plugins',
			'admin.plugins.name'    => 'Nom',
			'admin.plugins.author'  => 'Auteur',
			'admin.plugins.version' => 'Version',
			'admin.plugins.description' => 'Description',
			'admin.plugins.action'  => 'Action',
			'admin.plugins.enable'  => 'Activer',
			'admin.plugins.disable' => 'D&eacute;sactiver',
			
			'admin.themes' => 'Th&egrave;mes',
			'admin.themes.name' => 'Nom',
			'admin.themes.author' => 'Auteur',
			'admin.themes.version' => 'Version',
			'admin.themes.description' => 'Description',
			'admin.themes.action' => 'Action',
			'admin.themes.select' => 'S&eacute;lectionner',
			'admin.themes.default.name' => 'FLog par d&eacute;faut',
			'admin.themes.default.description' => 'Th&egrave;me par d&eacute;faut de FLog',
			
			'admin.logintext'       => '<em>%0</em> est pr&eacute;sentement connect&eacute;. [<a href="%1">D&eacute;connexion</a> | <a href="%2">Visiter le Site</a>]',
			'admin.logout'          => 'D&eacute;connexion',
			
			'admin.login'           => 'Connexion',
			'admin.login.fail'      => 'Nom d\'utilisateur ou mot de passe invalide.',
			'admin.login.logout'    => 'Vous &ecirc;tes d&eacute;connect&eacute; de la page d\'administration.',
			'admin.login.username'  => 'Nom d\'utilisateur:',
			'admin.login.password'  => 'Mot de passe:',
			'admin.login.remember'  => 'Se souvenir de moi',
			'admin.login.submit'    => 'Entrer',
			'admin.login.reset'     => 'Effacer',
			
			'admin.config.general' => 'Configuration G&eacute;n&eacute;rale',
			'admin.config.general.blog' => 'Blog',
			'admin.config.general.blog.name' => 'Nom du Blog:',
			'admin.config.general.blog.tagline' => 'Sous-titre:',
			'admin.config.general.blog.footer' => 'Bas de Page:',
			'admin.config.general.blog.language' => 'Langage:',
			'admin.config.general.meta' => 'Balises Meta',
			'admin.config.general.meta.description' => 'Description:',
			'admin.config.general.meta.author' => 'Auteur:',
			'admin.config.general.meta.keywords' => 'Mots-cl&eacute;s:',
			'admin.config.general.display' => 'Affichage',
			'admin.config.general.display.postsort' => 'Choisir l\'ordre des articles:',
			'admin.config.general.display.postsort.asc' => 'Ascendant',
			'admin.config.general.display.postsort.desc' => 'Descendand',
			'admin.config.general.display.commentsort' => 'Choisir l\'ordre des commentaires:',
			'admin.config.general.display.commentsort.asc' => 'Ascendant',
			'admin.config.general.display.commentsort.desc' => 'Descendant',
			'admin.config.general.display.numposts' => 'Nombre d\articles &agrave; afficher &agrave; la fois:',
			'admin.config.general.display.feedposts' => 'Nombre d\articles &agrave; afficher sur RSS et Atom feeds:',
			'admin.config.general.time' => 'Date/Heure',
			'admin.config.general.time.now' => 'L\'heure actuelle <acronym title="Coordinated Universal Time">UTC</acronym> est: %0 %1.',
			'admin.config.general.time.offset' => '&Eacute;cart avec l\'UTC (en heures):',
			'admin.config.general.time.dateformat' => 'Format de la date (Voir: <a href="http://www.php.net/date">PHP\'s <code>date</code> function</a>):',
			'admin.config.general.time.timeformat' => 'Format de l\'heure (Voir: <a href="http://www.php.net/date"><code>date</code></a>):',
			'admin.config.general.submit' => 'Envoyer',
			'admin.config.general.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.config.general.message.success' => 'Configuration sauvegard&eacute;.',
			
			'admin.config.display' => 'Afficher la Configuration',
			'admin.config.display.display' => 'Affichage',
			'admin.config.display.display.postsort' => 'Afficher les articles par ordre:',
			'admin.config.display.display.postsort.asc' => 'Ascendant',
			'admin.config.display.display.postsort.desc' => 'Descendant',
			'admin.config.display.display.commentsort' => 'Afficher les commentaires par ordre:',
			'admin.config.display.display.commentsort.asc' => 'Ascendant',
			'admin.config.display.display.commentsort.desc' => 'Descendant',
			'admin.config.display.display.linksort' => 'Afficher les liens par ordre:',
			'admin.config.display.display.linksort.asc' => 'Ascendant',
			'admin.config.display.display.linksort.desc' => 'Descendant',
			'admin.config.display.display.linktype' => 'Page de Liens:',
			'admin.config.display.display.linktype.all' => 'Page Unique',
			'admin.config.display.display.linktype.cats' => 'Cat&eacute;gories',
			'admin.config.display.display.linktype.archive' => 'Archive',
			'admin.config.display.display.numposts' => 'Nombre d\'articles &agrave; afficher &agrave; la fois:',
			'admin.config.display.display.feedposts' => 'Nombre d\'articles &agrave; afficher sur RSS et Atom feeds:',
			'admin.config.display.display.numlinks' => 'Nombre de liens &agrave; afficher &agrave; la fois:',
			'admin.config.display.display.feedlinks' => 'Nombre de liens &agrave; afficher sur RSS et Atom feeds:',
			'admin.config.display.submit' => 'Envoyer',
			'admin.config.display.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.config.display.message.success' => 'Configuration sauvegard&eacute;.',
			
			'admin.config.discussion' => 'Configuration des Discussion ',
			'admin.config.discussion.comments' => 'Commentaires',
			'admin.config.discussion.comments.markup' => 'Type de balises &agrave; utiliser:',
			'admin.config.discussion.comments.markup.choice' => '(Laisser le choix)',
			'admin.config.discussion.comments.markup.none' => '(X)HTML',
			'admin.config.discussion.comments.staletimeout' => 'Nombre de jours avant de v&eacute;rouiller une discution<br/>(z&eacute;ro ou vide pour d&eacute;sactiver):',
			'admin.config.discussion.comments.oldtimeout' => 'Nombre de jours apr&egrave;s la publication d\'un article avant de v&eacute;rouiller une discution<br/>(z&eacute;ro ou vide pour d&eacute;sactiver):',
			'admin.config.discussion.comments.anonymous' => 'Permettre les commentaires des utilisateurs anonymes',
			'admin.config.discussion.comments.blockip' => 'Block comments from inconsistent IPs',
			'admin.config.discussion.comments.blockreferrer' => 'Block comments from bad referrers',
			'admin.config.discussion.comments.modall' => 'Tous les commentaires doivent &ecirc;tre approuv&eacute;s',
			'admin.config.discussion.comments.modrepeat' => 'Les commentaires d\'utilisateurs qui n\'ont pas d&eacute;j&agrave; re&ccedil;u au moins UNE approbation doivent &ecirc;tre approuv&eacute;s',
			'admin.config.discussion.comments.emailmod' => 'Envoyer un courriel &agrave; l\'auteur d\'un article lorsqu\'un commentaire est en attente d\'approbation',
			'admin.config.discussion.comments.emailall' => 'Envoyer un courriel &agrave; l\'auteur d\'un article lorsqu\'un commentaire est post&eacute;',
			'admin.config.discussion.comments.maxsize' => 'Taille maximum des commentaires (en bytes, zero ou vide pour d&eacute;sactiver):',
			'admin.config.discussion.submit' => 'Envoyer',
			'admin.config.discussion.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.config.discussion.message.success' => 'Configuration sauvegard&eacute;.',
			
			'admin.config.permissions' => 'Configuration des Permissions',
			'admin.config.permissions.global' => 'Sections Plugin et Th&egrave;mes (z&eacute;ro ou vide pour donner l\'acc&egrave;s &agrave; tous les utilisateurs)',
			'admin.config.permissions.global.plugins' => 'Activer/D&eacute;sactiver les Plugins:',
			'admin.config.permissions.global.themes' => 'Changer les Th&egrave;mes:',
			'admin.config.permissions.write' => 'Section &Eacute;crire (z&eacute;ro ou vide pour donner l\'acc&egrave;s &agrave; tous les utilisateurs)',
			'admin.config.permissions.write.posts' => '&Eacute;crire des Articles:',
			'admin.config.permissions.write.pages' => 'Composer des Pages:',
			'admin.config.permissions.manage' => 'Section Gestion (z&eacute;ro ou vide pour donner l\'acc&egrave;s &agrave; tous les utilisateurs)',
			'admin.config.permissions.manage.posts' => 'G&egrave;rer les Articles:',
			'admin.config.permissions.manage.pages' => 'G&egrave;rer les Pages:',
			'admin.config.permissions.manage.comments' => 'G&egrave;rer les Commentaires:',
			'admin.config.permissions.manage.categories' => 'G&egrave;rer les Cat&eacute;gories:',
			'admin.config.permissions.manage.users' => 'G&egrave;rer les Utilisateurs (tous les utilisateurs peuvent modifier leurs infos):',
			'admin.config.permissions.manage.links' => 'G&egrave;rer les Liens:',
			'admin.config.permissions.manage.files' => 'G&egrave;rer les Fichiers:',
			'admin.config.permissions.config' => 'Section Configuration (z&eacute;ro ou vide pour donner l\'acc&egrave;s &agrave; tous les utilisateurs)',
			'admin.config.permissions.config.general' => 'G&eacute;n&eacute;ral:',
			'admin.config.permissions.config.display' => 'Affichage:',
			'admin.config.permissions.config.discussion' => 'Discussion:',
			'admin.config.permissions.config.permissions' => 'Permissions:',
			'admin.config.permissions.submit' => 'Envoyer',
			'admin.config.permissions.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.config.permissions.message.success' => 'Configuration sauvegard&eacute;.',
			
			'admin.manage.users' => 'Gestion des Utilisateurs',
			'admin.manage.users.id' => 'ID',
			'admin.manage.users.username' => 'Nom d\'utilisateur',
			'admin.manage.users.name' => 'Nom',
			'admin.manage.users.url' => 'Site Internet',
			'admin.manage.users.email' => 'Courriel',
			'admin.manage.users.rank' => 'Rang',
			'admin.manage.users.action' => 'Action',
			'admin.manage.users.edit' => 'Modifier',
			'admin.manage.users.edit.confirm' => 'Modifier',
			'admin.manage.users.edit.cancel' => 'Cancel',
			'admin.manage.users.delete' => 'Supprimer',
			'admin.manage.users.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer <em>%0</em>?',
			'admin.manage.users.delete.confirm' => 'Oui',
			'admin.manage.users.delete.cancel' => 'Non',
			'admin.manage.users.new' => 'Cr&eacute;er un nouvel utilisateur',
			'admin.manage.users.new.username' => 'Nom d\'utilisateur:',
			'admin.manage.users.new.password' => 'Mot de passe (deux fois):',
			'admin.manage.users.new.rank' => 'Rang:',
			'admin.manage.users.new.submit' => 'Cr&eacute;er',
			'admin.manage.users.password' => 'Changer le mot de passe',
			'admin.manage.users.password.oldpassword' => 'Ancien mot de passe:',
			'admin.manage.users.password.newpassword' => 'Nouveau mot de passe (2 fois):',
			'admin.manage.users.password.submit' => 'Changer',
			'admin.manage.users.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.manage.users.error.setrank' => 'Vous ne pouvez pas changer le rang d\'un utilisateur pour un rang sup&eacute;rieur ou &eacute;gal &agrave; votre rang.',
			'admin.manage.users.error.newrank' => 'Vous ne pouvez pas cr&eacute;er un utilisateur avec un rang sup&eacute;rieur ou &eacute;gal &agrave; votre rang.',
			'admin.manage.users.error.usernametaken' => 'Le nom d\'utilisateur que vous avez choisi n\'est pas disponible.',
			'admin.manage.users.error.invalidusername' => 'Le nom d\'utilisateur que vous avez choisi est invalide. Il doit contenir entre deux (2) et seize (16) caract&egrave;res : des chiffres, des lettres en minuscule, des tirets et des barres de soulignement (a&ndash;z, 0&ndash;9, -, _).',
			'admin.manage.users.error.newpasswordmatch' => 'Les mots de passe que vous avez entr&eacute; ne sont pas identiques.',
			'admin.manage.users.error.wrongpassword' => 'Vous avez entr&eacute; un mot de passe incorrect',
			'admin.manage.users.error.changepasswordmatch' => 'Les nouveaux mots de passe que vous avez entr&eacute; ne sont pas identiques.',
			'admin.manage.users.message.editsuccess' => 'L\'utilisateur a &eacute;t&eacute; modifi&eacute;.',
			'admin.manage.users.message.editcancel' => 'Modification annul&eacute;e.',
			'admin.manage.users.message.deletesuccess' => 'L\'utilisateur a &eacute;t&eacute; supprim&eacute;.',
			'admin.manage.users.message.deletecancel' => 'Suppression annul&eacute;e.',
			'admin.manage.users.message.newsuccess' => 'L\utilisateur a &eacute;t&eacute; cr&eacute;&eacute;.',
			'admin.manage.users.message.passwordsuccess' => 'Votre mot de passe a &eacute;t&eacute; chang&eacute;.',
			
			'admin.manage.cats' => 'Gestion des Cat&eacute;gories',
			'admin.manage.cats.id' => 'ID',
			'admin.manage.cats.name' => 'Nom',
			'admin.manage.cats.description' => 'Description',
			'admin.manage.cats.showblog' => 'Blog',
			'admin.manage.cats.showlinks' => 'Page',
			'admin.manage.cats.showlinks.yes' => 'Oui',
			'admin.manage.cats.showlinks.no' => 'Non',
			'admin.manage.cats.posts' => 'Articles',
			'admin.manage.cats.links' => 'Liens',
			'admin.manage.cats.action' => 'Action',
			'admin.manage.cats.edit' => 'Modifier',
			'admin.manage.cats.edit.confirm' => 'Modifier',
			'admin.manage.cats.edit.cancel' => 'Annuler',
			'admin.manage.cats.delete' => 'Supprimer',
			'admin.manage.cats.delete.message' => '&Ecirc;tes vous certain de vouloir modifier <em>%0</em>?',
			'admin.manage.cats.delete.confirm' => 'Oui',
			'admin.manage.cats.delete.cancel' => 'Non',
			'admin.manage.cats.new' => 'Cr&eacute;er une nouvelle cat&eacute;gorie',
			'admin.manage.cats.new.name' => 'Nom:',
			'admin.manage.cats.new.description' => 'Description:',
			'admin.manage.cats.new.showblog' => 'Nombre de liens &agrave; afficher dans Blog (Cat&eacute;gories de liens seulement, z&eacute;ro ou vide pour d&eacute;sactiver):',
			'admin.manage.cats.new.showlinks' => 'Afficher cette cat&eacute;gorie sur la page de liens (Cat&eacute;gories de liens seulement).',
			'admin.manage.cats.new.submit' => 'Cr&eacute;er la cat&eacute;gorie',
			'admin.manage.cats.new.submitlink' => 'Cr&eacute;er une cat&eacute;gories de liens',
			'admin.manage.cats.recalc' => 'Recalculer Tout',
			'admin.manage.cats.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.manage.cats.message.editsuccess' => 'La cat&eacute;gorie a &eacute;t&eacute; modifi&eacute;e.',
			'admin.manage.cats.message.editcancel' => 'Modification annul&eacute;e.',
			'admin.manage.cats.message.deletesuccess' => 'La cat&eacute;gorie a &eacute;t&eacute; supprim&eacute;e.',
			'admin.manage.cats.message.deletecancel' => 'Suppression annul&eacute;e.',
			'admin.manage.cats.message.newsuccess' => 'La cat&eacute;gorie a &eacute;t&eacute; cr&eacute;&eacute;.',
			
			'admin.manage.posts' => 'Gestion des Articles',
			'admin.manage.posts.id' => 'ID',
			'admin.manage.posts.title' => 'Titre',
			'admin.manage.posts.time' => 'Date',
			'admin.manage.posts.time.display' => '%0',
			'admin.manage.posts.author' => 'Auteur',
			'admin.manage.posts.cats' => 'Cat&eacute;gories',
			'admin.manage.posts.comments' => 'Commentaires',
			'admin.manage.posts.status' => 'Statut',
			'admin.manage.posts.status.draft' => 'Brouillon',
			'admin.manage.posts.status.delay' => 'Mettre en attente',
			'admin.manage.posts.status.both' => 'Brouillon | Mettre en attente',
			'admin.manage.posts.action' => 'Action',
			'admin.manage.posts.edit' => 'Modifier',
			'admin.manage.posts.delete' => 'Supprimer',
			'admin.manage.posts.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer <em>%0</em>?',
			'admin.manage.posts.delete.confirm' => 'Oui',
			'admin.manage.posts.delete.cancel' => 'Non',
			'admin.manage.posts.each' => 'Nombre d\'articles par pages:',
			'admin.manage.posts.each.submit' => 'Changer',
			'admin.manage.posts.recalc' => 'Recalculer les Commentaires',
			'admin.manage.posts.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.manage.posts.message.deletesuccess' => 'L\'article a &eacute;t&eacute; supprim&eacute;.',
			'admin.manage.posts.message.deletecancel' => 'Suppression annul&eacute;e.',
						
			'admin.manage.comments' => 'Gestion des Commentaires',
			'admin.manage.comments.id' => 'ID',
			'admin.manage.comments.post' => 'Article',
			'admin.manage.comments.name' => 'Nom',
			'admin.manage.comments.email' => 'Courriel',
			'admin.manage.comments.text' => 'Texte',
			'admin.manage.comments.time' => 'Date',
			'admin.manage.comments.time.display' => '%0',
			'admin.manage.comments.status' => 'Statut',
			'admin.manage.comments.status.moderated' => 'Attente d\'approbation',
			'admin.manage.comments.action' => 'Action',
			'admin.manage.comments.approve' => 'Approuver',
			'admin.manage.comments.edit' => 'Modifier',
			'admin.manage.comments.edit.name' => 'Nom:',
			'admin.manage.comments.edit.email' => 'Courriel:',
			'admin.manage.comments.edit.url' => 'URL:',
			'admin.manage.comments.edit.markup' => 'Balises &agrave; utiliser:',
			'admin.manage.comments.edit.markup.none' => '(X)HTML',
			'admin.manage.comments.edit.text' => 'Texte:',
			'admin.manage.comments.edit.preview' => 'Pr&eacute;visionner',
			'admin.manage.comments.edit.previewbox' => 'Pr&eacute;visionner',
			'admin.manage.comments.edit.submit' => 'Modifier',
			'admin.manage.comments.edit.cancel' => 'Annuler',
			'admin.manage.comments.delete' => 'Supprimer',
			'admin.manage.comments.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer ce commentaire ?',
			'admin.manage.comments.delete.confirm' => 'Oui',
			'admin.manage.comments.delete.cancel' => 'Non',
			'admin.manage.comments.each' => 'Nombre de COmmentaires par Page:',
			'admin.manage.comments.each.submit' => 'Changer',
			'admin.manage.comments.showtext' => 'Afficher le texte complet pour:',
			'admin.manage.comments.showtext.mod' => 'Commentaires en attente',
			'admin.manage.comments.showtext.all' => 'Tous les commentaires',
			'admin.manage.comments.showtext.none' => 'Ne pas afficher le texte complet',
			'admin.manage.comments.showtext.submit' => 'Changer',
			'admin.manage.comments.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.manage.comments.message.approve' => 'Le commentaire a &eacute;t&eacute; approuv&eacute;.',
			'admin.manage.comments.message.editsuccess' => 'Le commentaire a &eacute;t&eacute; modifi&eacute;.',
			'admin.manage.comments.message.editcancel' => 'Modification annul&eacute;e',
			'admin.manage.comments.message.deletesuccess' => 'Le commentaire a &eacute;t&eacute; supprim&eacute;.',
			'admin.manage.comments.message.deletecancel' => 'Suppression annul&eacute;e.',
			
			'admin.manage.pages' => 'Gestion des Pages',
			'admin.manage.pages.id' => 'ID',
			'admin.manage.pages.title' => 'Titres',
			'admin.manage.pages.url' => 'URL',
			'admin.manage.pages.action' => 'Action',
			'admin.manage.pages.edit' => 'Modifier',
			'admin.manage.pages.edit.confirm' => 'Modifier',
			'admin.manage.pages.edit.cancel' => 'Annuler',
			'admin.manage.pages.delete' => 'Supprimer',
			'admin.manage.pages.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer <em>%0</em>?',
			'admin.manage.pages.delete.confirm' => 'Oui',
			'admin.manage.pages.delete.cancel' => 'Non',
			'admin.manage.pages.up' => '&#8593;',
			'admin.manage.pages.down' => '&#8595;',
			'admin.manage.pages.show' => 'Montrer',
			'admin.manage.pages.hide' => 'Cacher',
			'admin.manage.pages.new' => 'Cr&eacute;er un item dans le menu de navigation',
			'admin.manage.pages.new.title' => 'Titre:',
			'admin.manage.pages.new.url' => 'URL (Laisser vide pour cr&eacute;er un s&eacute;parateur):',
			'admin.manage.pages.new.where' => 'Ins&eacute;rer apr&egrave;s:',
			'admin.manage.pages.where.top' => '(Haut)',
			'admin.manage.pages.where.separator' => '%0',
			'admin.manage.pages.where.link' => '%0',
			'admin.manage.pages.where.page' => '%0',
			'admin.manage.pages.new.submit' => 'Cr&eacute;er',
			'admin.manage.pages.error.database' => 'Erreur dans la base de donn&eacute;e.',
			'admin.manage.pages.message.editsuccess' => 'Cet item a &eacute;t&eacute; modifi&eacute;.',
			'admin.manage.pages.message.editcancel' => 'Modification annul&eacute;e.',
			'admin.manage.pages.message.deletesuccess' => 'Cet item a &eacute;t&eacute; supprim&eacute;.',
			'admin.manage.pages.message.deletecancel' => 'Suppression annul&eacute;e.',
			'admin.manage.pages.message.show' => 'La page a &eacute;t&eacute; ajout&eacute;e au menu.',
			'admin.manage.pages.message.hide' => 'La page a &eacute;t&eacute; retir&eacute;e du menu.',
			'admin.manage.pages.message.newentry' => 'L\'item a &eacute;t&eacute; cr&eacute;&eacute;.',
			
			'admin.manage.links' => 'Gestion des Liens',
			'admin.manage.links.id' => 'ID',
			'admin.manage.links.title' => 'Titre',
			'admin.manage.links.url' => 'URL',
			'admin.manage.links.time' => 'Date',
			'admin.manage.links.time.display' => '%0',
			'admin.manage.links.author' => 'Auteur',
			'admin.manage.links.cats' => 'Cat&eacute;gories',
			'admin.manage.links.status' => 'Statut',
			'admin.manage.links.status.sticky' => 'Prioritaire',
			'admin.manage.links.action' => 'Action',
			'admin.manage.links.edit' => 'Modifier',
			'admin.manage.links.delete' => 'Supprimer',
			'admin.manage.links.edit.now' => 'Maintenant',
			'admin.manage.links.edit.sticky' => 'Prioritaire',
			'admin.manage.links.edit.confirm' => 'Modifier',
			'admin.manage.links.edit.cancel' => 'Annuler',
			'admin.manage.links.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer <em>%0</em>?',
			'admin.manage.links.delete.confirm' => 'Oui',
			'admin.manage.links.delete.cancel' => 'Non',
			'admin.manage.links.each' => 'Nombre de liens par page:',
			'admin.manage.links.each.submit' => 'Changer',
			'admin.manage.links.new' => 'Cr&eacute;er un Nouveau Lien',
			'admin.manage.links.new.title' => 'Titre:',
			'admin.manage.links.new.url' => 'URL:',
			'admin.manage.links.new.cats' => 'Cat&eacute;gories:',
			'admin.manage.links.new.sticky' => 'Prioritaire',
			'admin.manage.links.new.submit' => 'Cr&eacute;er',
			'admin.manage.links.error.database' => 'Impossible d\'&eacute;crire dans la base de donn&eacute;e.',
			'admin.manage.links.message.createsuccess' => 'Le lien a &eacute;t&eacute; cr&eacute;&eacute;.',
			'admin.manage.links.message.editsuccess' => 'Le Liens a &eacute;t&eacute; modifi&eacute;.',
			'admin.manage.links.message.editcancel' => 'Modification annul&eacute;e.',
			'admin.manage.links.message.deletesuccess' => 'Le lien a &eacute;t&eacute; supprim&eacute;.',
			'admin.manage.links.message.deletecancel' => 'Suppression annul&eacute;e.',
			
			'admin.manage.files' => 'Gestion des Fichiers',
			'admin.manage.files.currentdir' => 'R&eacute;pertoire Actuel: <kbd>%0</kbd>',
			'admin.manage.files.filename' => 'Nom',
			'admin.manage.files.filesize' => 'Taille',
			'admin.manage.files.action' => 'Action',
			'admin.manage.files.rename' => 'Renommer',
			'admin.manage.files.rename.confirm' => 'Renommer',
			'admin.manage.files.rename.cancel' => 'Annuler',
			'admin.manage.files.delete' => 'Supprimer',
			'admin.manage.files.delete.message' => '&Ecirc;tes vous certain de vouloir supprimer <em>%0</em>?',
			'admin.manage.files.delete.confirm' => 'Oui',
			'admin.manage.files.delete.cancel' => 'Non',
			'admin.manage.files.upload' => 'T&eacute;l&eacute;charger',
			'admin.manage.files.upload.filename' => 'Nom du Fichier:',
			'admin.manage.files.upload.submit' => 'T&eacute;l&eacute;charger',
			'admin.manage.files.newdir' => 'Cr&eacute;er un Nouveau R&eacute;pertoire',
			'admin.manage.files.newdir.dirname' => 'Nom du R&eacute;pertoire:',
			'admin.manage.files.newdir.submit' => 'Cr&eacute;er',
			'admin.manage.files.message.newdirsuccess' => 'Le R&eacute;pertoire est cr&eacute;&eacute;.',
			'admin.manage.files.message.uploadsuccess' => 'Le Fichier est T&eacute;l&eacute;charg&eacute;.',
			'admin.manage.files.message.renamefilesuccess' => 'Fichier Renomm&eacute;.',
			'admin.manage.files.message.renamedirsuccess' => 'R&eacute;pertoire Renomm&eacute;.',
			'admin.manage.files.message.renamecancel' => 'Annulation.',
			'admin.manage.files.message.deletecancel' => 'Supression annul&eacute;e.',
			'admin.manage.files.message.deletedirsuccess' => 'R&eacute;pertoire supprim&eacute;.',
			'admin.manage.files.message.deletefilesuccess' => 'Fichier supprim&eacute;.',
			'admin.manage.files.error.dirname' => 'Nom de r&eacute;pertoire invalide.',
			'admin.manage.files.error.newdirfail' => 'Impossible de cr&eacute;er le r&eacute;pertoire.',
			'admin.manage.files.error.badfile' => 'Erreur de fichier. Assurez-vous que la taille du fichier ne d&eacute;passe pas '.ini_get('upload_max_filesize').'.',
			'admin.manage.files.error.uploadfail' => 'Impossible de t&eacute;l&eacute;charger le fichier',
			'admin.manage.files.error.badfilename' => 'Nom de fichier invalide.',
			'admin.manage.files.error.renamefilefail' => 'Impossible de renommer le ficher.',
			'admin.manage.files.error.baddirname' => 'Nom de r&eacute;pertoire invalide.',
			'admin.manage.files.error.renamedirfail' => 'Impossible de renommer le r&eacute;pertoire.',
			'admin.manage.files.error.deletefilefail' => 'Impossible de supprimer le fichier.',
			'admin.manage.files.error.deletedirfail' => 'Impossible de supprimer le r&eacute;pertoire. Assurez-vous qu\'il est vide.',
			'admin.manage.files.error.readdir' => 'Impossible de lire dans le r&eacute;pertoire.',
			
			'admin.write.posts' => '&Eacute;crire un Article',
			'admin.write.posts.edit' => 'Modifier l\'Article',
			'admin.write.posts.title' => 'Titre:',
			'admin.write.posts.markup' => 'Balises &agrave; utiliser:',
			'admin.write.posts.markup.none' => '(X)HTML',
			'admin.write.posts.cats' => 'Cat&eacute;gories',
			'admin.write.posts.time' => 'Date/Heure:',
			'admin.write.posts.time.now' => 'Date et heure actuelles',
			'admin.write.posts.comments' => 'Autoriser les commentaires',
			'admin.write.posts.draft' => 'Brouillon',
			'admin.write.posts.delay' => 'Afficher plus tard',
			'admin.write.posts.text' => 'Texte:',
			'admin.write.posts.preview' => 'Pr&eacute;visionner',
			'admin.write.posts.submit' => 'Soumettre',
			'admin.write.posts.previewbox' => 'Pr&eacute;visionner',
			'admin.write.posts.message.editsuccess' => 'Votre article a &eacute;t&eacute; modifi&eacute;.',
			'admin.write.posts.message.success' => 'Votre article a &eacute;t&eacute; ajout&eacute;.',
			'admin.write.posts.message.success.view' => '<a href="%0">Voir cet article</a>',
			'admin.write.posts.message.success.edit' => '<a href="%0">Modifier cet article</a>',
			'admin.write.posts.message.success.more' => '<a href="%0">&Eacute;crire un nouvel article</a>',
			'admin.write.posts.message.success.manage' => '<a href="%0">G&egrave;rer les articles</a>',
			'admin.write.posts.error.database' => 'Erreur de base de donn&eacute;e.',
			'admin.write.posts.error.permissions' => 'Vous n\'avez pas l\'autorisation de modifier cet article.',
			'admin.write.posts.error.notfound' => 'Article introuvable.',
			
			'admin.write.pages' => 'Composer une Page',
			'admin.write.pages.edit' => 'Modifier la Page',
			'admin.write.pages.title' => 'Titre:',
			'admin.write.pages.markup' => 'Balises &agrave; utiliser:',
			'admin.write.pages.markup.none' => '(X)HTML',
			'admin.write.pages.id' => 'ID:',
			'admin.write.pages.where' => 'Ins&eacute;rer apr&egrave;s:',
			'admin.write.pages.where.none' => '(Invisible)',
			'admin.write.pages.where.top' => '(Haut)',
			'admin.write.pages.where.separator' => '%0',
			'admin.write.pages.where.link' => '%0',
			'admin.write.pages.where.page' => '%0',
			'admin.write.pages.text' => 'Texte:',
			'admin.write.pages.preview' => 'Pr&eacute;visionner',
			'admin.write.pages.submit' => 'Soumettre',
			'admin.write.pages.previewbox' => 'Pr&eacute;visionner',
			'admin.write.pages.message.editsuccess' => 'Votre page a &eacute;t&eacute; modifi&eacute;e.',
			'admin.write.pages.message.success' => 'Votre page a &eacute;t&eacute; ajout&eacute;e.',
			'admin.write.pages.message.success.view' => '<a href="%0">Voir cette page</a>',
			'admin.write.pages.message.success.edit' => '<a href="%0">Modifier cette page</a>',
			'admin.write.pages.message.success.more' => '<a href="%0">Composer une autre page</a>',
			'admin.write.pages.message.success.manage' => '<a href="%0">G&egrave;rer les pages</a>',
			'admin.write.pages.error.database' => 'Erreur de base de donn&eacute;e.',
			'admin.write.pages.error.id' => 'ID d&eacute;j&agrave; utilis&eacute;e.',
			'admin.write.pages.error.notfound' => 'Page introuvable.',
			'admin.write.pages.error.noid' => 'Vous n\'avez pas sp&eacute;cifi&eacute; de ID.',
			
			'admin.stats.overall' => 'Statistiques G&eacute;n&eacute;rales',
			'admin.stats.overall.browsers' => 'Navigateurs',
			'admin.stats.overall.systems' => 'Sys. d\'explotation',
			'admin.stats.overall.posts' => 'Articles',
			'admin.stats.overall.pages' => 'Pages',
			'admin.stats.overall.total' => 'Total: %0 / %1',
			'admin.stats.overall.year' => 'Cette Ann&eacute;e: %0 / %1',
			'admin.stats.overall.month' => 'Mois Courrant: %0 / %1',
			'admin.stats.overall.day' => 'Aujourd\'hui: %0 / %1',
			'admin.stats.overall.hour' => 'Heure courrante: %0 / %1', 
			
			'admin.stats.graphs' => 'Graphique',
			'admin.stats.graphs.hours' => 'Heures:',
			'admin.stats.graphs.days' => 'Jours:',
			'admin.stats.graphs.months' => 'Mois:',
			'admin.stats.graphs.months.01' => 'Jan',
			'admin.stats.graphs.months.02' => 'F&eacute;v',
			'admin.stats.graphs.months.03' => 'Mar',
			'admin.stats.graphs.months.04' => 'Avr',
			'admin.stats.graphs.months.05' => 'Mai',
			'admin.stats.graphs.months.06' => 'Juin',
			'admin.stats.graphs.months.07' => 'Juil',
			'admin.stats.graphs.months.08' => 'Ao&ucirc;t',
			'admin.stats.graphs.months.09' => 'Sep',
			'admin.stats.graphs.months.10' => 'Oct',
			'admin.stats.graphs.months.11' => 'Nov',
			'admin.stats.graphs.months.12' => 'D&eacute;c',
			'admin.stats.graphs.years' => 'Ann&eacute;es:',
			
			'admin.stats.recent' => 'Visiteurs R&eacute;cents',
			'admin.stats.recent.time' => 'Date/Heure',
			'admin.stats.recent.time.display' => '%0, %1',
			'admin.stats.recent.ip' => 'IP',
			'admin.stats.recent.browser' => 'Navigateur',
			'admin.stats.recent.system' => 'Syst. d\'explotation',
			'admin.stats.recent.hits' => 'Visites',
			
			'admin.menu.home'             => 'Accueil',
			'admin.menu.plugins'          => 'Plugins',
			'admin.menu.themes'           => 'Th&ecirc;mes',
			'admin.menu.logout'           => 'D&eacute;connexion',
			'admin.menu.manage'           => 'Gestion',
			'admin.menu.manage.posts'       => 'Articles',
			'admin.menu.manage.pages'       => 'Pages',
			'admin.menu.manage.links'       => 'Liens',
			'admin.menu.manage.cats'        => 'Cat&eacute;gories',
			'admin.menu.manage.comments'    => 'Commentaires',
			'admin.menu.manage.users'       => 'Utilisateurs',
			'admin.menu.manage.files'       => 'Fichiers',
			'admin.menu.config'           => 'Configuration',
			'admin.menu.config.general'     => 'G&eacute;n&eacute;ral',
			'admin.menu.config.discussion'  => 'Discussion',
			'admin.menu.config.display'     => 'Affichage',
			'admin.menu.config.permissions' => 'Permissions',
			'admin.menu.write'            => '&Eacute;crire',
			'admin.menu.write.posts'        => 'Articles',
			'admin.menu.write.pages'        => 'Pages',
			'admin.menu.stats'            => 'Statistiques',
			'admin.menu.stats.overall'      => 'G&eacute;n&eacute;rales',
			'admin.menu.stats.graphs'       => 'Graphiques',
			'admin.menu.stats.recent'       => 'Visiteurs',
			
			'comment.email.moderated.subject' => 'Quelqu\'un a post&eacute; un commentaire sur votre article.',
			'comment.email.moderated' => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) a post&eacute; un commentaire sur votre article, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%5">Approuver</a> | <a href="%6">Modifier</a> | <a href="%7">Supprimer</a> ]</p>',
			'comment.email.approved.subject' => 'Quelqu\'un a post&eacute; un commentaire sur votre article.',
			'comment.email.approved'  => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) a post&eacute; un commentaire sur votre article, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%6">Modifier</a> | <a href="%7">Supprimer</a> ]</p>',
			
			// ---------------------------------------------------------------

			'theme.!default.post.nocomments' => 'Aucun commentaire',
			'theme.!default.post.onecomment' => '1 commentaire',
			'theme.!default.post.numcomments' => '%0 commentaires',
			
			'theme.!default.post.header' => 'Publi&eacute; par %0 le %1 &agrave; %2',
			'theme.!default.post.header.anon' => 'Post&eacute; le %0 &agrave; %1',
			
			'theme.!default.index.next' => 'Suite &#8594;',
			'theme.!default.index.prev' => '&#8592; Pr&eacute;c&eacute;dent',
			
			'theme.!default.page404' => '404: Page Introuvable',
			'theme.!default.page404.message' => 'La page que vous cherchez n\'existe pas.',
			
			'theme.!default.post404' => '404: Article Introuvable',
			'theme.!default.post404.message' => 'L\'article que vous cherchez n\'existe pas.',
			
			'theme.!default.nav' => 'Navigation',
			'theme.!default.nav.home' => 'Accueil',
			'theme.!default.nav.cats' => 'Categories',
			'theme.!default.nav.links' => 'Liens',
			'theme.!default.nav.archives' => 'Archives',
			'theme.!default.nav.menu' => 'Menu',
			'theme.!default.nav.archives.posts' => 'Articles',
			'theme.!default.nav.archives.links' => 'Liens',
			
			'theme.!default.linkback' => 'Ce BLOG est propuls&eacute; par <a href="http://www.fluffington.com/" style="color:inherit;text-decoration:inherit;">FLog</a>',
			
			'theme.!default.commentform' => 'Commentez cet article',
			'theme.!default.commentform.name' => 'Nom (obligatoire):',
			'theme.!default.commentform.email' => 'Courriel (obligatoire, ne sera jamais affich&eacute;):',
			'theme.!default.commentform.url' => 'Votre site Internet:',
			'theme.!default.commentform.markup' => 'Balises &agrave; utiliser:',
			'theme.!default.commentform.markup.none' => '(X)HTML',
			'theme.!default.commentform.text' => 'Texte:',
			'theme.!default.commentform.text.markup' => 'Texte (%0):',
			'theme.!default.commentform.preview' => 'Pr&eacute;visionner',
			'theme.!default.commentform.submit' => 'Soumettre',
			'theme.!default.commentform.previewbox' => 'Pr&eacute;visionner',
			'theme.!default.commentform.error.namemail' => 'Votre nom et votre adresse de courriel sont requis.',
			'theme.!default.commentform.error.anonymous' => 'Les visiteurs anonymes ne sont pas autoris&eacute;s &agrave; poster des commentaires.',
			'theme.!default.commentform.error.ip' => 'Votre commentaire a &eacute;t&eacute; bloqu&eacute;e car votre adresse IP a chang&eacute; depuis que vous avez ouvert ce formulaire.',
			'theme.!default.commentform.error.referrer' => 'Votre commentaire a &eacute;t&eacute; bloqu&eacute; car vous avez atteint ce formulaire &agrave; partir d\'une source non autoris&eacute;e.',
			'theme.!default.commentform.error.allowcomments' => 'Les commentaires ne sont pas autoris&eacute;s sur cet article.',
			'theme.!default.commentform.error.blocked' => 'Votre commentaire a &eacute;t&eacute; bloqu&eacute;.',
			'theme.!default.commentform.error.database' => 'Erreur de base de donn&eacute;e.',
			'theme.!default.commentform.error.maxsize' => 'Votre commentaire exc&egrave;de la taille autoris&eacute;e, qui est de %0 carat&egrave;res.',
			'theme.!default.commentform.message.moderated' => 'Votre commentaire est enregistr&eacute; et est en attente d\'approbation. Il sera affich&eacute; aussit&ocirc;t qu\'il aura &eacute;t&eacute; approuv&eacute;.',
			'theme.!default.commentform.message.posted' => 'Votre commentaire est enregistr&eacute; et affich&eacute;.',
			
			'theme.!default.error.database' => 'Erreur de Base de Donn&eacute;e.',
			'theme.!default.error.allowcomments' => 'Les commentaires ne sont pas autoris&eacute;s pour cet article.',
			'theme.!default.error.maxsize' => 'Ce commentaire d&eacute;passe la limite permise de %0 caract&egrave;res.',
			'theme.!default.error.anonymous' => 'Les visiteurs anonymes ne sont pas autoris&eacute;s &agrave; poster des commentaires.',
			'theme.!default.error.ip' => 'Votre commentaire a &eacute;t&eacute; bloqu&eacute;e car votre adresse IP a chang&eacute; depuis que vous avez ouvert ce formulaire. Si vous utilisez un proxy et que vous avez re&ccedil;u ce message par erreur, essayez de nouveau.',
			'theme.!default.error.referrer' => 'Votre commentaire a &eacute;t&eacute; bloqu&eacute; car vous avez atteint ce formulaire &agrave; partir d\'une source non autoris&eacute;e.',
			'theme.!default.error.nameemail' => 'Vous devez inscrire une adresse de courriel valide.',
			'theme.!default.message.moderated' => 'Votre commentaire est enregistr&eacute;. Il sera visible pour les autres visiteurs lorsque je l\'aurais r&eacute;vis&eacute; et accept&eacute;.',
			'theme.!default.message.posted' => 'Votre commentaire est enregistr&eacute;.',
			
			'theme.!default.archive.message' => 'Archive pour %0',
			'theme.!default.archive.message.cat' => '%1, archive pour %0',
			'theme.!default.archive.links.message' => 'Archive des liens pour %0',
			'theme.!default.archive.links.message.cat' => '%1, archive des liens pour %0',
			'theme.!default.archive.posts' => 'Archives des Articles',
			'theme.!default.archive.links' => 'Archives des Liens',
			'theme.!default.archive.view' => 'Voir',
			'theme.!default.archive.months.01' => 'Janvier',
			'theme.!default.archive.months.02' => 'F&eacute;vrier',
			'theme.!default.archive.months.03' => 'Mars',
			'theme.!default.archive.months.04' => 'Avril',
			'theme.!default.archive.months.05' => 'Mai',
			'theme.!default.archive.months.06' => 'Juin',
			'theme.!default.archive.months.07' => 'Juillet',
			'theme.!default.archive.months.08' => 'Ao&ucirc;t',
			'theme.!default.archive.months.09' => 'Septembre',
			'theme.!default.archive.months.10' => 'Octobre',
			'theme.!default.archive.months.11' => 'Novembre',
			'theme.!default.archive.months.12' => 'D&eacute;cembre',
			'theme.!default.archive.time.display' => '%1',

);

$GLOBALS['FLog_lang_list']['fr'] = 'Francais (MuscalBox)';

?>