<?php
/*
plugin-name: Deutsche &Uuml;bersetzung f&uuml;r FLog
plugin-url: http://www.ranger81.de/
plugin-version: 1.1.1
plugin-description: &Uuml;bersetzt den kompletten FLog auf Deutsch. Die aktuellste &Uuml;bersetzungs-Datei kann immer <a href="http://ranger81.homeip.net/rcblog/index.php?post=s1129573724">hier</a> heruntergeladen werden.
author-name: Tobias Link
author-url: http://www.ranger81.de/
*/

/*
		You can always download the latest translation-file under:
		http://ranger81.homeip.net/rcblog/index.php?post=s1129573724

		Thanks a lot Noah for RCBlog and FLog.
		I am saying "Thank you" with this translation for you!
*/



$GLOBALS['FLog_strings']['de'] = array(
			'admin.home'            => 'Startseite',
			'admin.home.version'    => 'Version: %0',
			'admin.home.posts'      => 'Beitr&auml;ge: %0',
			'admin.home.pages'      => 'Seiten: %0',
			'admin.home.comments'   => 'Kommentare: %0',
			'admin.home.links'      => 'Links: %0',
			'admin.home.cats'       => 'Kategorien: %0',
			'admin.home.users'      => 'Benutzer: %0',

			'admin.plugins'         => 'Plugins',
			'admin.plugins.name'    => 'Name',
			'admin.plugins.author'  => 'Autor',
			'admin.plugins.version' => 'Version',
			'admin.plugins.description' => 'Beschreibung',
			'admin.plugins.action'  => 'Aktion',
			'admin.plugins.enable'  => 'Aktivieren',
			'admin.plugins.disable' => 'Deaktivieren',
			
			'admin.themes' => 'Schemen',
			'admin.themes.name' => 'Name',
			'admin.themes.author' => 'Autor',
			'admin.themes.version' => 'Version',
			'admin.themes.description' => 'Beschreibung',
			'admin.themes.action' => 'Aktion',
			'admin.themes.select' => 'Ausw&auml;hlen',
			'admin.themes.default.name' => 'FLog Standard',
			'admin.themes.default.description' => 'FLog\'s Standard-Schema',
			
			'admin.logintext'       => 'Zur Zeit eingeloggt als <em>%0</em>. [<a href="%1">Ausloggen</a> | <a href="%2">Seite ansehen</a>]',
			'admin.logout'          => 'Ausloggen',
			
			'admin.login'           => 'Einloggen',
			'admin.login.fail'      => 'Falscher Benutzername oder Passwort!',
			'admin.login.logout'    => 'Sie wurden ausgeloggt.',
			'admin.login.username'  => 'Benutzer:',
			'admin.login.password'  => 'Passwort:',
			'admin.login.remember'  => 'In Cookie speichern',
			'admin.login.submit'    => 'Absenden',
			'admin.login.reset'     => 'Reset',
			
			'admin.config.general' => 'Allgemeine Konfiguration',
			'admin.config.general.blog' => 'Blog',
			'admin.config.general.blog.name' => 'Blog Name:',
			'admin.config.general.blog.tagline' => 'Slogan:',
			'admin.config.general.blog.footer' => 'Fu&szlig;zeile:',
			'admin.config.general.blog.language' => 'Sprache:',
			'admin.config.general.meta' => 'Meta',
			'admin.config.general.meta.description' => 'Beschreibung:',
			'admin.config.general.meta.author' => 'Autor:',
			'admin.config.general.meta.keywords' => 'Stichw&ouml;rter:',
			'admin.config.general.display' => 'Anzeige',
			'admin.config.general.display.postsort' => 'Sortierreihenfolge Beitr&auml;ge:',
			'admin.config.general.display.postsort.asc' => 'Aufsteigend',
			'admin.config.general.display.postsort.desc' => 'Absteigend',
			'admin.config.general.display.commentsort' => 'Sortierreihenfolge Kommentare:',
			'admin.config.general.display.commentsort.asc' => 'Aufsteigend',
			'admin.config.general.display.commentsort.desc' => 'Absteigend',
			'admin.config.general.display.numposts' => 'Anzahl der Beitr&auml;ge die auf einmal angezeigt werden:',
			'admin.config.general.display.feedposts' => 'Anzahl der Beitr&auml;ge in RSS -und Atom-Feeds:',
			'admin.config.general.time' => 'Datum/Zeit',
			'admin.config.general.time.now' => 'Aktuelle <acronym title="Coordinated Universal Time">UTC</acronym> ist: %0 %1.',
			'admin.config.general.time.offset' => 'Verschiebung von UTC (in Stunden):',
			'admin.config.general.time.dateformat' => 'Datumsformat (gleiches Format wie <a href="http://www.php.net/date">PHP\'s <code>date</code> Funktion</a>):',
			'admin.config.general.time.timeformat' => 'Zeitformat (wieder dasselbe wie <a href="http://www.php.net/date"><code>date</code></a>):',
			'admin.config.general.submit' => 'Absenden',
			'admin.config.general.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.config.general.message.success' => 'Konfiguration gespeichert.',
			
			'admin.config.display' => 'Anzeige Konfiguration',
			'admin.config.display.display' => 'Anzeige',
			'admin.config.display.display.postsort' => 'Sortierreihenfolge Beitr&auml;ge:',
			'admin.config.display.display.postsort.asc' => 'Aufsteigend',
			'admin.config.display.display.postsort.desc' => 'Absteigend',
			'admin.config.display.display.commentsort' => 'Sortierreihenfolge Kommentare:',
			'admin.config.display.display.commentsort.asc' => 'Aufsteigend',
			'admin.config.display.display.commentsort.desc' => 'Absteigend',
			'admin.config.display.display.linksort' => 'Sortierreihenfolge Links:',
			'admin.config.display.display.linksort.asc' => 'Aufsteigend',
			'admin.config.display.display.linksort.desc' => 'Absteigend',
			'admin.config.display.display.linktype' => 'Links Seite:',
			'admin.config.display.display.linktype.all' => 'Einzelne Seite',
			'admin.config.display.display.linktype.cats' => 'Kategorien',
			'admin.config.display.display.linktype.archive' => 'Archive',
			'admin.config.display.display.numposts' => 'Anzahl der Beitr&auml;ge die auf einmal angezeigt werden:',
			'admin.config.display.display.feedposts' => 'Anzahl der Beitr&auml;ge in RSS -und Atom-Feeds:',
			'admin.config.display.display.numlinks' => 'Anzahl der Beitr&auml;ge die auf einmal angezeigt werden:',
			'admin.config.display.display.feedlinks' => 'Anzahl der Beitr&auml;ge in RSS -und Atom-Feeds:',
			'admin.config.display.submit' => 'Absenden',
			'admin.config.display.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.config.display.message.success' => 'Konfiguration gespeichert.',
			
			'admin.config.discussion' => 'Kommentar Konfiguration',
			'admin.config.discussion.comments' => 'Kommentare',
			'admin.config.discussion.comments.markup' => 'Erkennung:',
			'admin.config.discussion.comments.markup.choice' => '(Benutzer hat die Wahl)',
			'admin.config.discussion.comments.markup.none' => '(X)HTML',
			'admin.config.discussion.comments.staletimeout' => 'Anzahl an Tagen, bis eine fade Diskussion geschlossen wird (Ziffer 0 oder das Feld leer lassen, um die Funktion zu deaktivieren):',
			'admin.config.discussion.comments.oldtimeout' => 'Anzahl an Tagen nach dem Post, bis eine Diskussion geschlossen wird (Ziffer 0 oder das Feld leer lassen, um die Funktion zu deaktivieren):',
			'admin.config.discussion.comments.anonymous' => 'Kommentare von anonymen Benutzern erlauben',
			'admin.config.discussion.comments.blockip' => 'Kommentare von inkonsistenten IPs blickieren',
			'admin.config.discussion.comments.blockreferrer' => 'Kommentare von falschen Referrers blockieren',
			'admin.config.discussion.comments.modall' => 'Alle Kommentare moderieren',
			'admin.config.discussion.comments.modrepeat' => 'Nur Kommentare von Postern moderieren, sie noch nicht einen akzeptierten Kommentar geschrieben haben',
			'admin.config.discussion.comments.emailmod' => 'Sende Mail an Beitrags-Autor wenn ein Kommentar moderiert ist',
			'admin.config.discussion.comments.emailall' => 'Sende Mail an Beitrags-Autor wenn ein Kommentar geschrieben wurde',
			'admin.config.discussion.comments.maxsize' => 'Maximale Gr&ouml;&szlig;e der Kommenate (in Bytes, Ziffer 0 oder das Feld leer lassen, um die Funktion zu deaktivieren):',
			'admin.config.discussion.submit' => 'Absenden',
			'admin.config.discussion.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.config.discussion.message.success' => 'Konfiguration gespeichert.',
			
			'admin.config.permissions' => 'Zugriffs Konfiguration',
			'admin.config.permissions.global' => 'Admin (Ziffer 0 oder das Feld leer lassen, um alle Benutzer zu erlauben)',
			'admin.config.permissions.global.plugins' => 'Aktiviere/Deaktiviere Plugins:',
			'admin.config.permissions.global.themes' => 'Schemen wechseln:',
			'admin.config.permissions.write' => 'Schreiben (Ziffer 0 oder das Feld leer lassen, um alle Benutzer zu erlauben)',
			'admin.config.permissions.write.posts' => 'Beitr&auml;ge schrieben:',
			'admin.config.permissions.write.pages' => 'Seiten schrieben:',
			'admin.config.permissions.manage' => 'Verwalten (Ziffer 0 oder das Feld leer lassen, um alle Benutzer zu erlauben)',
			'admin.config.permissions.manage.posts' => 'Beitr&auml;ge verwalten:',
			'admin.config.permissions.manage.pages' => 'Seiten verwalten:',
			'admin.config.permissions.manage.comments' => 'Kommentare verwalten:',
			'admin.config.permissions.manage.categories' => 'Kategorien verwalten:',
			'admin.config.permissions.manage.users' => 'Benutzer verwalten (Alle Benutzer k&ouml;nnen ihre eigenen Inforationen &auml;ndern):',
			'admin.config.permissions.manage.links' => 'Links verwalten:',
			'admin.config.permissions.manage.files' => 'Dateien verwalten:',
			'admin.config.permissions.config' => 'Konfiguration (Ziffer 0 oder das Feld leer lassen, um alle Benutzer zu erlauben)',
			'admin.config.permissions.config.general' => 'Allgemeine Konfiguration:',
			'admin.config.permissions.config.display' => 'Anzeige Konfiguration:',
			'admin.config.permissions.config.discussion' => 'Kommentar Konfiguration:',
			'admin.config.permissions.config.permissions' => 'Zugriffs Konfiguration:',
			'admin.config.permissions.submit' => 'Absenden',
			'admin.config.permissions.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.config.permissions.message.success' => 'Konfiguration gespeichert.',
			
			'admin.manage.users' => 'Benutzer verwalten',
			'admin.manage.users.id' => 'ID',
			'admin.manage.users.username' => 'Benutzername',
			'admin.manage.users.name' => 'Name',
			'admin.manage.users.url' => 'URL',
			'admin.manage.users.email' => 'E-mail',
			'admin.manage.users.rank' => 'Rang',
			'admin.manage.users.action' => 'Aktion',
			'admin.manage.users.edit' => '&auml;ndern',
			'admin.manage.users.edit.confirm' => '&auml;ndern',
			'admin.manage.users.edit.cancel' => 'Abbrechen',
			'admin.manage.users.delete' => 'L&ouml;schen',
			'admin.manage.users.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.users.delete.confirm' => 'Ja',
			'admin.manage.users.delete.cancel' => 'Nein',
			'admin.manage.users.new' => 'Neuen Benutzer anlegen',
			'admin.manage.users.new.username' => 'Benutzername:',
			'admin.manage.users.new.password' => 'Passwort (zweimal):',
			'admin.manage.users.new.rank' => 'Rang:',
			'admin.manage.users.new.submit' => 'Anlegen',
			'admin.manage.users.password' => 'Passwort &auml;ndern',
			'admin.manage.users.password.oldpassword' => 'OAltes Passwort:',
			'admin.manage.users.password.newpassword' => 'Neues Password (zweimal):',
			'admin.manage.users.password.submit' => '&auml;ndern',
			'admin.manage.users.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.users.error.setrank' => 'Sie k&ouml;nnen nicht einen Benutzer_Rang w&auml;hlen, der kleiner oder gleich ihrer ist.',
			'admin.manage.users.error.newrank' => 'Sie k&ouml;nnen nicht einen Benutzer anlegen mit einen kleineren oder gleichen Rang wie ihrem.',
			'admin.manage.users.error.usernametaken' => 'Der angegebene Benutzername existiert bereits.',
			'admin.manage.users.error.invalidusername' => 'Der angegebene Benutzername ist falsch. Benutzernamen m&uuml;ssen zwischen zwei (2) und sechzehn (16) Zeichen (inklusive) einem Kleinbuchstabe, Bindestrich oder Unterstrich (a&ndash;z, 0&ndash;9, -, _) bestehen.',
			'admin.manage.users.error.newpasswordmatch' => 'Die zwei eigebenen Passw&ouml;rter stimmen nicht &uuml;berein.',
			'admin.manage.users.error.wrongpassword' => 'Sie haben das falsche Passwort eingegeben',
			'admin.manage.users.error.changepasswordmatch' => 'Die zwei eigebenen Passw&ouml;rter stimmen nicht &uuml;berein.',
			'admin.manage.users.message.editsuccess' => 'Der Benutzer wurde ge&auml;ndert.',
			'admin.manage.users.message.editcancel' => '&auml;nderung abgebrochen.',
			'admin.manage.users.message.deletesuccess' => 'Der Benutzer wurde gel&ouml;scht.',
			'admin.manage.users.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			'admin.manage.users.message.newsuccess' => 'Der Benutzer wurde angelegt.',
			'admin.manage.users.message.passwordsuccess' => 'Ihr Passwort wurde ge&auml;ndert.',
			
			'admin.manage.cats' => 'Kategorien verwalten',
			'admin.manage.cats.id' => 'ID',
			'admin.manage.cats.name' => 'Name',
			'admin.manage.cats.description' => 'Beschreibung',
			'admin.manage.cats.showblog' => 'Beitrag',
			'admin.manage.cats.showlinks' => 'Seite',
			'admin.manage.cats.showlinks.yes' => 'Ja',
			'admin.manage.cats.showlinks.no' => 'Nein',
			'admin.manage.cats.posts' => 'Beitr&auml;ge',
			'admin.manage.cats.links' => 'Links',
			'admin.manage.cats.action' => 'Aktion',
			'admin.manage.cats.edit' => '&auml;ndern',
			'admin.manage.cats.edit.confirm' => '&auml;ndern',
			'admin.manage.cats.edit.cancel' => 'Abbrechen',
			'admin.manage.cats.delete' => 'L&ouml;schen',
			'admin.manage.cats.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.cats.delete.confirm' => 'Ja',
			'admin.manage.cats.delete.cancel' => 'Nein',
			'admin.manage.cats.new' => 'Neue Kategorie anlegen',
			'admin.manage.cats.new.name' => 'Name:',
			'admin.manage.cats.new.description' => 'Beschreibung:',
			'admin.manage.cats.new.showblog' => 'Anzahl an Links, die im BLog gezeigt werden (nur Kategorie-Links, Ziffer 0 oder das Feld leer lassen, um die Funktion zu deaktivieren):',
			'admin.manage.cats.new.showlinks' => 'Diese Kategorie in der Link-Seite anzeigen (nur Kategorie-Links).',
			'admin.manage.cats.new.submit' => 'Kategorie anlegen',
			'admin.manage.cats.new.submitlink' => 'Link-Kategorie anlegen',
			'admin.manage.cats.recalc' => 'Alle neuberechnen',
			'admin.manage.cats.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.cats.message.editsuccess' => 'Die Kategorie wurde ge&auml;ndert.',
			'admin.manage.cats.message.editcancel' => '&auml;nderung abgebrochen.',
			'admin.manage.cats.message.deletesuccess' => 'Die Kategorie wurde gel&ouml;scht.',
			'admin.manage.cats.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			'admin.manage.cats.message.newsuccess' => 'Die Kategorie wurde angelegt.',
			
			'admin.manage.posts' => 'Beitr&auml;ge verwalten',
			'admin.manage.posts.id' => 'ID',
			'admin.manage.posts.title' => 'Titel',
			'admin.manage.posts.time' => 'Datum',
			'admin.manage.posts.time.display' => '%0',
			'admin.manage.posts.author' => 'Autor',
			'admin.manage.posts.cats' => 'Kategorien',
			'admin.manage.posts.comments' => 'Kommentare',
			'admin.manage.posts.status' => 'Status',
			'admin.manage.posts.status.draft' => 'Vorlage',
			'admin.manage.posts.status.delay' => 'Versp&auml;tet',
			'admin.manage.posts.status.both' => 'Vorlage | Versp&auml;tet',
			'admin.manage.posts.action' => 'Aktion',
			'admin.manage.posts.edit' => '&auml;ndern',
			'admin.manage.posts.delete' => 'L&ouml;schen',
			'admin.manage.posts.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.posts.delete.confirm' => 'Ja',
			'admin.manage.posts.delete.cancel' => 'Nein',
			'admin.manage.posts.each' => 'Anzahl an Beitr&auml;gen pro Seite:',
			'admin.manage.posts.each.submit' => '&auml;ndern',
			'admin.manage.posts.recalc' => 'Kommentare neuberechnen',
			'admin.manage.posts.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.posts.message.deletesuccess' => 'Der Beitrg wurde gel&ouml;scht.',
			'admin.manage.posts.message.deletecancel' => 'L&ouml;schung abgebrochen.',
						
			'admin.manage.comments' => 'Kommentare verwalten',
			'admin.manage.comments.id' => 'ID',
			'admin.manage.comments.post' => 'Beitrag',
			'admin.manage.comments.name' => 'Name',
			'admin.manage.comments.email' => 'E-Mail',
			'admin.manage.comments.text' => 'Text',
			'admin.manage.comments.time' => 'Datum',
			'admin.manage.comments.time.display' => '%0',
			'admin.manage.comments.status' => 'Status',
			'admin.manage.comments.status.moderated' => 'moderiert',
			'admin.manage.comments.action' => 'Aktion',
			'admin.manage.comments.approve' => 'Akzeptieren',
			'admin.manage.comments.edit' => '&auml;ndern',
			'admin.manage.comments.edit.name' => 'Name:',
			'admin.manage.comments.edit.email' => 'E-Mail:',
			'admin.manage.comments.edit.url' => 'URL:',
			'admin.manage.comments.edit.markup' => 'Erkennung:',
			'admin.manage.comments.edit.markup.none' => '(X)HTML',
			'admin.manage.comments.edit.text' => 'Text:',
			'admin.manage.comments.edit.preview' => 'Vorschau',
			'admin.manage.comments.edit.previewbox' => 'Vorschau',
			'admin.manage.comments.edit.submit' => '&auml;ndern',
			'admin.manage.comments.edit.cancel' => 'Abbrechen',
			'admin.manage.comments.delete' => 'L&ouml;schen',
			'admin.manage.comments.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.comments.delete.confirm' => 'Ja',
			'admin.manage.comments.delete.cancel' => 'Nein',
			'admin.manage.comments.each' => 'Anzahl der Kommentare pro Seite:',
			'admin.manage.comments.each.submit' => '&auml;ndern',
			'admin.manage.comments.showtext' => 'Ganzen Text zeigen f&uuml;r:',
			'admin.manage.comments.showtext.mod' => 'moderierte Kommentare',
			'admin.manage.comments.showtext.all' => 'Alle Kommentare',
			'admin.manage.comments.showtext.none' => 'Nicht den ganzen Text anzeigen',
			'admin.manage.comments.showtext.submit' => '&auml;ndern',
			'admin.manage.comments.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.comments.message.approve' => 'Der Kommentar wurde akzeptiert.',
			'admin.manage.comments.message.editsuccess' => 'Der Kommentar wurde ge&auml;ndert.',
			'admin.manage.comments.message.editcancel' => '&auml;nderung abgebrochen',
			'admin.manage.comments.message.deletesuccess' => 'Der Kommentar wurde gel&ouml;scht.',
			'admin.manage.comments.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			
			'admin.manage.pages' => 'Seiten verwalten',
			'admin.manage.pages.id' => 'ID',
			'admin.manage.pages.title' => 'Titel',
			'admin.manage.pages.url' => 'URL',
			'admin.manage.pages.action' => 'Aktion',
			'admin.manage.pages.edit' => '&auml;ndern',
			'admin.manage.pages.edit.confirm' => '&auml;ndern',
			'admin.manage.pages.edit.cancel' => 'Abbrechen',
			'admin.manage.pages.delete' => 'L&ouml;schen',
			'admin.manage.pages.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.pages.delete.confirm' => 'Ja',
			'admin.manage.pages.delete.cancel' => 'Nein',
			'admin.manage.pages.up' => '&#8593;',
			'admin.manage.pages.down' => '&#8595;',
			'admin.manage.pages.show' => 'Zeigen',
			'admin.manage.pages.hide' => 'Verstecken',
			'admin.manage.pages.new' => 'Neuen Eintrag anlegen',
			'admin.manage.pages.new.title' => 'Titel:',
			'admin.manage.pages.new.url' => 'URL (leer lassen um Absatz zu erzeugen):',
			'admin.manage.pages.new.where' => 'Nach folgendem einsetzen:',
			'admin.manage.pages.where.top' => '(Oben)',
			'admin.manage.pages.where.separator' => '%0',
			'admin.manage.pages.where.link' => '%0',
			'admin.manage.pages.where.page' => '%0',
			'admin.manage.pages.new.submit' => 'Anlegen',
			'admin.manage.pages.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.pages.message.editsuccess' => 'Der Eintrag wurde ge&auml;ndert.',
			'admin.manage.pages.message.editcancel' => '&auml;nderung abgebrochen.',
			'admin.manage.pages.message.deletesuccess' => 'Der Eintrag wurde gel&ouml;scht.',
			'admin.manage.pages.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			'admin.manage.pages.message.show' => 'Die Seite wurde dem Men&uuml; hinzugef&uuml;gt.',
			'admin.manage.pages.message.hide' => 'Die Seite wurde vom Men&uuml; entfernt.',
			'admin.manage.pages.message.newentry' => 'Der Eintarg wurde angelegt.',
			
			'admin.manage.links' => 'Links verwalten',
			'admin.manage.links.id' => 'ID',
			'admin.manage.links.title' => 'Titel',
			'admin.manage.links.url' => 'URL',
			'admin.manage.links.time' => 'Datum',
			'admin.manage.links.time.display' => '%0',
			'admin.manage.links.author' => 'Autor',
			'admin.manage.links.cats' => 'Kategorien',
			'admin.manage.links.status' => 'Status',
			'admin.manage.links.status.sticky' => 'wichtig',
			'admin.manage.links.action' => 'Aktion',
			'admin.manage.links.edit' => '&auml;ndern',
			'admin.manage.links.delete' => 'L&ouml;schen',
			'admin.manage.links.edit.now' => 'Jetzt',
			'admin.manage.links.edit.sticky' => 'Wichtig',
			'admin.manage.links.edit.confirm' => '&auml;ndern',
			'admin.manage.links.edit.cancel' => 'Abbrechen',
			'admin.manage.links.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.links.delete.confirm' => 'Ja',
			'admin.manage.links.delete.cancel' => 'Nein',
			'admin.manage.links.each' => 'Anzahl an Link pro Seite:',
			'admin.manage.links.each.submit' => '&auml;ndern',
			'admin.manage.links.new' => 'Neuen Link anlegen',
			'admin.manage.links.new.title' => 'Titel:',
			'admin.manage.links.new.url' => 'URL:',
			'admin.manage.links.new.cats' => 'Kategorien:',
			'admin.manage.links.new.sticky' => 'Wichtig',
			'admin.manage.links.new.submit' => 'Anlegen',
			'admin.manage.links.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.manage.links.message.createsuccess' => 'Der Link wurde angelegt.',
			'admin.manage.links.message.editsuccess' => 'Der Link wurde ge&auml;ndert.',
			'admin.manage.links.message.editcancel' => '&auml;nderung abgebrochen.',
			'admin.manage.links.message.deletesuccess' => 'Der Link wurde gel&ouml;scht.',
			'admin.manage.links.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			
			'admin.manage.files' => 'Dateien verwalten',
			'admin.manage.files.currentdir' => 'Aktuelles Verzeichnis: <kbd>%0</kbd>',
			'admin.manage.files.filename' => 'Name',
			'admin.manage.files.filesize' => 'Gr&ouml;&szlig;e',
			'admin.manage.files.action' => 'Aktion',
			'admin.manage.files.rename' => 'Umbenennen',
			'admin.manage.files.rename.confirm' => 'Umbenennen',
			'admin.manage.files.rename.cancel' => 'Abbrechen',
			'admin.manage.files.delete' => 'L&ouml;schen',
			'admin.manage.files.delete.message' => 'M&ouml;chten sie wirklich <em>%0</em> l&ouml;schen?',
			'admin.manage.files.delete.confirm' => 'Ja',
			'admin.manage.files.delete.cancel' => 'Nein',
			'admin.manage.files.upload' => 'Hochladen',
			'admin.manage.files.upload.filename' => 'Dateiname:',
			'admin.manage.files.upload.submit' => 'Hochladen',
			'admin.manage.files.newdir' => 'Neues Verzeichnis anlegen',
			'admin.manage.files.newdir.dirname' => 'Verzeichnisname:',
			'admin.manage.files.newdir.submit' => 'Anlegen',
			'admin.manage.files.message.newdirsuccess' => 'Verzeichnis angelegt.',
			'admin.manage.files.message.uploadsuccess' => 'Datei hcohgeladen.',
			'admin.manage.files.message.renamefilesuccess' => 'Datei umbenannt.',
			'admin.manage.files.message.renamedirsuccess' => 'Verzeichnis umbenannt.',
			'admin.manage.files.message.renamecancel' => 'Umbenennung abgebrochen.',
			'admin.manage.files.message.deletecancel' => 'L&ouml;schung abgebrochen.',
			'admin.manage.files.message.deletedirsuccess' => 'Verzeichnis gel&ouml;scht.',
			'admin.manage.files.message.deletefilesuccess' => 'Datei gel&ouml;scht.',
			'admin.manage.files.error.dirname' => 'Falscher Verzeichnisname.',
			'admin.manage.files.error.newdirfail' => 'Konnte Verzeichnis nicht erstellen.',
			'admin.manage.files.error.badfile' => 'Dateifehler. Bitte sicherstellen, dass die Dateigr&ouml;&szlig;e der Datei kleiner ist als '.ini_get('upload_max_filesize').'.',
			'admin.manage.files.error.uploadfail' => 'Konnte Datei nicht hochladen',
			'admin.manage.files.error.badfilename' => 'Falscher Dateiname.',
			'admin.manage.files.error.renamefilefail' => 'Konnte Datei nicht umbenennen.',
			'admin.manage.files.error.baddirname' => 'Falscher Verzeichnisname.',
			'admin.manage.files.error.renamedirfail' => 'Konnte Verzeichnis nicht umbenennen.',
			'admin.manage.files.error.deletefilefail' => 'Konnte Datei nicht l&ouml;schen.',
			'admin.manage.files.error.deletedirfail' => 'Konnte Verzeichnis nicht l&ouml;schen. Bitte sicherstellen, dass Verzeichnis leer ist.',
			'admin.manage.files.error.readdir' => 'Kann Verzeichnisinhalt nicht lesen.',
			
			'admin.write.posts' => 'Beitr&auml;ge schrieben',
			'admin.write.posts.edit' => 'Beitrag &auml;ndern',
			'admin.write.posts.title' => 'Titel:',
			'admin.write.posts.markup' => 'Erkennung:',
			'admin.write.posts.markup.none' => '(X)HTML',
			'admin.write.posts.cats' => 'Kategorien',
			'admin.write.posts.time' => 'Datum/Zeit:',
			'admin.write.posts.time.now' => 'Auf Jetzt setzen',
			'admin.write.posts.comments' => 'Kommentare erlauben',
			'admin.write.posts.draft' => 'Entwurf',
			'admin.write.posts.delay' => 'Verz&ouml;gerter Beitrag',
			'admin.write.posts.text' => 'Text:',
			'admin.write.posts.preview' => 'Vorschau',
			'admin.write.posts.submit' => 'Absenden',
			'admin.write.posts.previewbox' => 'Vorschau',
			'admin.write.posts.message.editsuccess' => 'Ihr Beitrag wurde ge&auml;ndert.',
			'admin.write.posts.message.success' => 'Ihr Beitrag wurde hinzugef&uuml;gt.',
			'admin.write.posts.message.success.view' => '<a href="%0">Beitrag ansehen</a>',
			'admin.write.posts.message.success.edit' => '<a href="%0">Beitrag &auml;ndern</a>',
			'admin.write.posts.message.success.more' => '<a href="%0">Weiteren beitrag schrieben</a>',
			'admin.write.posts.message.success.manage' => '<a href="%0">Beitr&auml;ge verwalten</a>',
			'admin.write.posts.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.write.posts.error.permissions' => 'Sie haben nicht die Berechtigung diesen Beitrag zu &auml;ndern.',
			'admin.write.posts.error.notfound' => 'Beitrag nicht gefunden.',
			
			'admin.write.pages' => 'Seite schreiben',
			'admin.write.pages.edit' => 'Seite &auml;ndern',
			'admin.write.pages.title' => 'Titel:',
			'admin.write.pages.markup' => 'Erkennung:',
			'admin.write.pages.markup.none' => '(X)HTML',
			'admin.write.pages.id' => 'ID:',
			'admin.write.pages.where' => 'Nach folgendem einsetzen:',
			'admin.write.pages.where.none' => '(Unsichtbar)',
			'admin.write.pages.where.top' => '(Oben)',
			'admin.write.pages.where.separator' => '%0',
			'admin.write.pages.where.link' => '%0',
			'admin.write.pages.where.page' => '%0',
			'admin.write.pages.text' => 'Text:',
			'admin.write.pages.preview' => 'Vorschau',
			'admin.write.pages.submit' => 'Absenden',
			'admin.write.pages.previewbox' => 'Vorschau',
			'admin.write.pages.message.editsuccess' => 'Ihre Seite wurde ge&auml;ndert.',
			'admin.write.pages.message.success' => 'Ihre Seite wurde hinzugef&uuml;gt.',
			'admin.write.pages.message.success.view' => '<a href="%0">Seite ansehen</a>',
			'admin.write.pages.message.success.edit' => '<a href="%0">Seite &auml;ndern</a>',
			'admin.write.pages.message.success.more' => '<a href="%0">Weitere Seite schreiben</a>',
			'admin.write.pages.message.success.manage' => '<a href="%0">Seiten verwalten</a>',
			'admin.write.pages.error.database' => 'Kann nicht in Datenbank speichern.',
			'admin.write.pages.error.id' => 'ID bereits vergeben.',
			'admin.write.pages.error.notfound' => 'Seite nicht gefunden.',
			'admin.write.pages.error.noid' => 'Keine ID angegeben.',
			
			'admin.stats.overall' => 'Gesamte Statistiken',
			'admin.stats.overall.browsers' => 'Browser',
			'admin.stats.overall.systems' => 'OSs',
			'admin.stats.overall.posts' => 'Beitr&auml;ge',
			'admin.stats.overall.pages' => 'Seiten',
			'admin.stats.overall.total' => 'Gesamt: %0 / %1',
			'admin.stats.overall.year' => 'Dieses Jahr: %0 / %1',
			'admin.stats.overall.month' => 'Diesen Monat: %0 / %1',
			'admin.stats.overall.day' => 'Heute: %0 / %1',
			'admin.stats.overall.hour' => 'Diese Stunde: %0 / %1', 
			
			'admin.stats.graphs' => 'Grafische Statistiken',
			'admin.stats.graphs.hours' => 'Stunden:',
			'admin.stats.graphs.days' => 'Tage:',
			'admin.stats.graphs.months' => 'Monate:',
			'admin.stats.graphs.months.01' => 'Jan',
			'admin.stats.graphs.months.02' => 'Feb',
			'admin.stats.graphs.months.03' => 'M&auml;r',
			'admin.stats.graphs.months.04' => 'Apr',
			'admin.stats.graphs.months.05' => 'Mai',
			'admin.stats.graphs.months.06' => 'Jun',
			'admin.stats.graphs.months.07' => 'Jul',
			'admin.stats.graphs.months.08' => 'Aug',
			'admin.stats.graphs.months.09' => 'Sep',
			'admin.stats.graphs.months.10' => 'Okt',
			'admin.stats.graphs.months.11' => 'Nov',
			'admin.stats.graphs.months.12' => 'Dez',
			'admin.stats.graphs.years' => 'Jahre:',
			
			'admin.stats.recent' => 'Letzte Besucher',
			'admin.stats.recent.time' => 'Zeit',
			'admin.stats.recent.time.display' => '%0, %1',
			'admin.stats.recent.ip' => 'IP',
			'admin.stats.recent.browser' => 'Browser',
			'admin.stats.recent.system' => 'OS',
			'admin.stats.recent.hits' => 'Hits',
			
			'admin.menu.home'             => 'Startseite',
			'admin.menu.plugins'          => 'Plugins',
			'admin.menu.themes'           => 'Schemen',
			'admin.menu.logout'           => 'Ausloggen',
			'admin.menu.manage'           => 'Verwalten',
			'admin.menu.manage.posts'       => 'Beitr&auml;ge',
			'admin.menu.manage.pages'       => 'Seiten',
			'admin.menu.manage.links'       => 'Links',
			'admin.menu.manage.cats'        => 'Kategorien',
			'admin.menu.manage.comments'    => 'Kommentare',
			'admin.menu.manage.users'       => 'Benutzer',
			'admin.menu.manage.files'       => 'Dateien',
			'admin.menu.config'           => 'Konfiguration',
			'admin.menu.config.general'     => 'Allgemein',
			'admin.menu.config.discussion'  => 'Kommentare',
			'admin.menu.config.display'     => 'Anzeige',
			'admin.menu.config.permissions' => 'Zugriff',
			'admin.menu.write'            => 'Schreiben',
			'admin.menu.write.posts'        => 'Beitr&auml;ge',
			'admin.menu.write.pages'        => 'Seiten',
			'admin.menu.stats'            => 'Statistiken',
			'admin.menu.stats.overall'      => 'Gesamt',
			'admin.menu.stats.graphs'       => 'Grafisch',
			'admin.menu.stats.recent'       => 'Besucher',
			
			'comment.email.moderated.subject' => 'Jemand hat ihren Beitrag kommentiert.',
			'comment.email.moderated' => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) hat ihren Beitrag kommentiert, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%5">Akzeptieren</a> | <a href="%6">&auml;ndern</a> | <a href="%7">L&ouml;schen</a> ]</p>',
			'comment.email.approved.subject' => 'Jemand hat ihren Beitrag kommentiert.',
			'comment.email.approved'  => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) hat ihren Beitrag kommentiert, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%6">&auml;ndern</a> | <a href="%7">L&ouml;schen</a> ]</p>',
			
			// ---------------------------------------------------------------

			'theme.!default.post.nocomments' => 'Keine Kommentare',
			'theme.!default.post.onecomment' => '1 Kommentar',
			'theme.!default.post.numcomments' => '%0 Kommentare',
			
			'theme.!default.post.header' => 'Geschrieben von %0 am %1 um %2',
			'theme.!default.post.header.anon' => 'Geschrieben am %0 um %1',
			
			'theme.!default.index.next' => 'N&auml;chste &#8594;',
			'theme.!default.index.prev' => '&#8592; Vorherige',
			
			'theme.!default.page404' => '404: Seite nicht gefunden',
			'theme.!default.page404.message' => 'Die angeforderte Seite wurde nicht gefunden.',
			
			'theme.!default.post404' => '404: Beitrag nicht gefunden',
			'theme.!default.post404.message' => 'Der angeforderte Post wurde nicht gefunden.',
			
			'theme.!default.nav' => 'Navigation',
			'theme.!default.nav.home' => 'Startseite',
			'theme.!default.nav.cats' => 'Kategorien',
			'theme.!default.nav.links' => 'Links',
			'theme.!default.nav.archives' => 'Archive',
			'theme.!default.nav.archives.posts' => 'Beitr&auml;ge',
			'theme.!default.nav.archives.links' => 'Links',
			
			'theme.!default.linkback' => 'Powered by <a href="http://www.fluffington.com/" style="color:inherit;text-decoration:inherit;">FLog</a><br/>Deutsche &Uuml;bersetzung von <a href="http://www.ranger81.de/" style="color:inherit;text-decoration:inherit;">ranger81</a>',
			
			'theme.!default.commentform' => 'Kommentare f&uuml;r diesen Beitrag',
			'theme.!default.commentform.name' => 'Name (erforderlich):',
			'theme.!default.commentform.email' => 'E-mail (erforderlich, wird niemals angezeigt):',
			'theme.!default.commentform.url' => 'URL:',
			'theme.!default.commentform.markup' => 'Erkennung:',
			'theme.!default.commentform.markup.none' => '(X)HTML',
			'theme.!default.commentform.text' => 'Text:',
			'theme.!default.commentform.text.markup' => 'Text (%0):',
			'theme.!default.commentform.preview' => 'Vorschau',
			'theme.!default.commentform.submit' => 'Absenden',
			'theme.!default.commentform.previewbox' => 'Vorschau',
			'theme.!default.commentform.error.namemail' => 'Ihr Name und ihre E-Mail Adresse sind erfordelrich.',
			'theme.!default.commentform.error.anonymous' => 'Anonyme Benutzer d&uuml;rfen keine Kommentare schreiben.',
			'theme.!default.commentform.error.ip' => 'Ihr Kommentar wurde geblockt, da ihre jetzige IP von der IP abweicht, die das Formular aufgerufen hat. Wenn sie hinter einem Proxy sitzen und sie erhalten diese Nachricht, versuchen sie es erneut.',
			'theme.!default.commentform.error.referrer' => 'Ihr Kommentar wurde geblockt, da sie einen falschen Rreferrer haben.',
			'theme.!default.commentform.error.allowcomments' => 'Dieser Beitrag erlaubt keine Kommentare.',
			'theme.!default.commentform.error.blocked' => 'Ihr Kommentar wurde blockiert.',
			'theme.!default.commentform.error.database' => 'Kann nicht in Datenbank speichern.',
			'theme.!default.commentform.error.maxsize' => 'Ihr Kommentar &uuml;berschreitet die maximale Anzahl an Zeichen (%0 Zeichen).',
			'theme.!default.commentform.message.moderated' => 'Ihr Kommentar wurde in den moderierten Status geschaltet, er wird sichtbar, sobald ein Moderator ihn akzeptiert.',
			'theme.!default.commentform.message.posted' => 'Ihr Kommentar wurde geschrieben.',
			
			'theme.!default.error.database' => 'Kann nicht in Datenbank speichern.',
			'theme.!default.error.allowcomments' => 'Dieser Beitrag erlaubt keine Kommentare.',
			'theme.!default.error.maxsize' => 'Ihr Kommentar &uuml;berschreitet die maximale Anzahl an Bytes (%0 bytes).',
			'theme.!default.error.anonymous' => 'Anonyme Benutzer d&uuml;rfen keine Kommentare schreiben.',
			'theme.!default.error.ip' => 'Ihr Kommentar wurde geblockt, da ihre jetzige IP von der IP abweicht, die das Formular aufgerufen hat. Wenn sie hinter einem Proxy sitzen und sie erhalten diese Nachricht, versuchen sie es erneut.',
			'theme.!default.error.referrer' => 'Ihr Kommentar wurde geblockt, da sie einen falschen Rreferrer haben.',
			'theme.!default.error.nameemail' => 'Sie m&uuml;ssen einen Namen und eine g&uuml;ltige E-Mail Adresse angeben.',
			'theme.!default.message.moderated' => 'Ihr Kommentar wurde in den moderierten Status geschaltet, er wird sichtbar, sobald ein Moderator ihn akzeptiert.',
			'theme.!default.message.posted' => 'Ihr Kommentar wurde geschrieben.',
			
			'theme.!default.archive.message' => 'Archiv f&uuml;r %0',
			'theme.!default.archive.message.cat' => '%1, Archiv f&uuml;r %0',
			'theme.!default.archive.links.message' => 'Link Archiv f&uuml;r %0',
			'theme.!default.archive.links.message.cat' => '%1, Link Archiv f&uuml;r %0',
			'theme.!default.archive.posts' => 'Beitrags-Archiv',
			'theme.!default.archive.links' => 'Link Archiv',
			'theme.!default.archive.view' => 'anzeigen',
			'theme.!default.archive.months.01' => 'Januar',
			'theme.!default.archive.months.02' => 'Februar',
			'theme.!default.archive.months.03' => 'M&auml;rz',
			'theme.!default.archive.months.04' => 'April',
			'theme.!default.archive.months.05' => 'Mai',
			'theme.!default.archive.months.06' => 'Juni',
			'theme.!default.archive.months.07' => 'Juli',
			'theme.!default.archive.months.08' => 'August',
			'theme.!default.archive.months.09' => 'September',
			'theme.!default.archive.months.10' => 'Oktober',
			'theme.!default.archive.months.11' => 'November',
			'theme.!default.archive.months.12' => 'Dezember',
			'theme.!default.archive.time.display' => '%1',

	);

$GLOBALS['FLog_lang_list']['de'] = 'Deutsch (ranger81)';

?>
