<?php
/*
plugin-name: Język polski
plugin-url: http://www.xom.webd.pl
plugin-version: 1.1.1
plugin-description: Polska lokalizacja dla Flog 1.1.0
author-name: Xom
author-url: http://www.xom.webd.pl
*/

$GLOBALS['FLog_strings']['pl'] = array(
			'admin.home'            => 'Start',
			'admin.home.version'    => 'Wersja: %0',
			'admin.home.posts'      => 'Posty: %0',
			'admin.home.pages'      => 'Strony: %0',
			'admin.home.comments'   => 'Komentarze: %0',
			'admin.home.links'      => 'Odnośniki: %0',
			'admin.home.cats'       => 'Kategorie: %0',
			'admin.home.users'      => 'Użytkownicy: %0',

			'admin.plugins'         => 'Wtyczki',
			'admin.plugins.name'    => 'Nazwa',
			'admin.plugins.author'  => 'Autor',
			'admin.plugins.version' => 'Wersja',
			'admin.plugins.description' => 'Opis',
			'admin.plugins.action'  => 'Akcja',
			'admin.plugins.enable'  => 'Włącz',
			'admin.plugins.disable' => 'Wyłącz',
			
			'admin.themes' => 'Tematy',
			'admin.themes.name' => 'Nazwa',
			'admin.themes.author' => 'Autor',
			'admin.themes.version' => 'Wersja',
			'admin.themes.description' => 'Opis',
			'admin.themes.action' => 'Akcja',
			'admin.themes.select' => 'Wybierz',
			'admin.themes.default.name' => 'Domyślny dla FLog',
			'admin.themes.default.description' => 'Domyslny dla FLog',
			
			'admin.logintext'       => 'Aktualnie zalogowany jako <em>%0</em>. [<a href="%1">Wyloguj</a> | <a href="%2">Przeglądaj</a>]',
			'admin.logout'          => 'Wyloguj',
			
			'admin.login'           => 'Zaloguj',
			'admin.login.fail'      => 'Błędna nazwa uzytkownika lub hasło.',
			'admin.login.logout'    => 'Zostałeś wylogowany.',
			'admin.login.username'  => 'Nazwa użytkownika:',
			'admin.login.password'  => 'Hasło:',
			'admin.login.remember'  => 'Zapamiętaj mnie',
			'admin.login.submit'    => 'Wyślij',
			'admin.login.reset'     => 'Wyczyść',
			
			'admin.config.general' => 'Konfiguracja ogólna',
			'admin.config.general.blog' => 'Blog',
			'admin.config.general.blog.name' => 'Nazwa Bloga:',
			'admin.config.general.blog.tagline' => 'Motto:',
			'admin.config.general.blog.footer' => 'Stopka:',
			'admin.config.general.blog.language' => 'Język:',
			'admin.config.general.meta' => 'Meta',
			'admin.config.general.meta.description' => 'Opis:',
			'admin.config.general.meta.author' => 'Autor:',
			'admin.config.general.meta.keywords' => 'Słowa kluczowe:',
			'admin.config.general.display' => 'Widok',
			'admin.config.general.display.postsort' => 'Sposób sortowania postów:',
			'admin.config.general.display.postsort.asc' => 'Rosnąco',
			'admin.config.general.display.postsort.desc' => 'Malejąco',
			'admin.config.general.display.commentsort' => 'Sposób sortowania komentarzy:',
			'admin.config.general.display.commentsort.asc' => 'Rosnąco',
			'admin.config.general.display.commentsort.desc' => 'Malejąco',
			'admin.config.general.display.numposts' => 'Ilość postów wyświetlanych jednocześnie:',
			'admin.config.general.display.feedposts' => 'Ilość postów wyświetlanych jednocześnie w kanałach RSS i Atom:',
			'admin.config.general.time' => 'Data/Czas',
			'admin.config.general.time.now' => 'Aktualny czas <acronym title="Coordinated Universal Time">UTC</acronym> to: %0 %1.',
			'admin.config.general.time.offset' => 'Różnica do UTC (w godzinach):',
			'admin.config.general.time.dateformat' => 'Format daty (taki sam jak <a href="http://www.php.net/date">funkcji <code>date</code> w PHP</a>):',
			'admin.config.general.time.timeformat' => 'Format czasu (taki sam jak <a href="http://www.php.net/date">funkcji <code>date</code> w PHP</a>):',
			'admin.config.general.submit' => 'Wyślij',
			'admin.config.general.error.database' => 'Nie można zapisać do bazy!',
			'admin.config.general.message.success' => 'Konfiguracja zapisana.',
			
			'admin.config.display' => 'Konfiguracja widoku',
			'admin.config.display.display' => 'Widok',
			'admin.config.display.display.postsort' => 'Sposób sortowania postów:',
			'admin.config.display.display.postsort.asc' => 'Rosnąco',
			'admin.config.display.display.postsort.desc' => 'Malejąco',
			'admin.config.display.display.commentsort' => 'Sposób sortowania komentarzy:',
			'admin.config.display.display.commentsort.asc' => 'Rosnąco',
			'admin.config.display.display.commentsort.desc' => 'Malejąco',
			'admin.config.display.display.linksort' => 'Sposób sortowania odnośników:',
			'admin.config.display.display.linksort.asc' => 'Rosnąco',
			'admin.config.display.display.linksort.desc' => 'Malejąco',
			'admin.config.display.display.linktype' => 'Strona odnośników:',
			'admin.config.display.display.linktype.all' => 'Osobna strona',
			'admin.config.display.display.linktype.cats' => 'Kategorie',
			'admin.config.display.display.linktype.archive' => 'Archiwum',
			'admin.config.display.display.numposts' => 'Ilość postów wyświetlanych jednocześnie:',
			'admin.config.display.display.feedposts' => 'Ilość postów wyświetlanych jednocześnie w kanałach RSS i Atom:',
			'admin.config.display.display.numlinks' => 'Ilość odnośników wyświetlanych jednocześnie:',
			'admin.config.display.display.feedlinks' => 'Ilość odnośników wyświetlanych jednocześnie w kanałach RSS i Atom:',
			'admin.config.display.submit' => 'Wyślij',
			'admin.config.display.error.database' => 'Nie można zapisać do bazy!',
			'admin.config.display.message.success' => 'Konfiguracja zapisana.',
			
			'admin.config.discussion' => 'Konfiguracja komentarzy',
			'admin.config.discussion.comments' => 'Komentarze',
			'admin.config.discussion.comments.markup' => 'Markup:',
			'admin.config.discussion.comments.markup.choice' => '(Pozwól wybrać użytkownikowi)',
			'admin.config.discussion.comments.markup.none' => '(X)HTML',
			'admin.config.discussion.comments.staletimeout' => 'Ilość dni od ostatniego komentarza, po których komentowanie zostanie zablokowane (zero lub puste by wyłączyć):',
			'admin.config.discussion.comments.oldtimeout' => 'Ilość dni od publikicji postu, po których komentowanie zostanie zablokowane (zero lub puste by wyłączyć):',
			'admin.config.discussion.comments.anonymous' => 'Zezwalaj na komentarze od anonimowych użytkowników',
			'admin.config.discussion.comments.blockip' => 'Blokuj komentarze z niewłaściwych adresów IP',
			'admin.config.discussion.comments.blockreferrer' => 'Blokuj komentarze ze złych referentów',
			'admin.config.discussion.comments.modall' => 'Moderuj wszystkie komentarze',
			'admin.config.discussion.comments.modrepeat' => 'Moderuj komentarze od użytkowników nie mających żadnych zaakceptowanych komentarzy',
			'admin.config.discussion.comments.emailmod' => 'Powiadom e-mailem autora moderowanego komentarza',
			'admin.config.discussion.comments.emailall' => 'Powiadom e-mailem autora zawsze gdy zostanie opublikowany komentarz',
			'admin.config.discussion.comments.maxsize' => 'Maksymalna wielkość komentarza (w znakach, zero lub puste by wyłączyć):',
			'admin.config.discussion.submit' => 'Wyślij',
			'admin.config.discussion.error.database' => 'Nie można zapisać do bazy!',
			'admin.config.discussion.message.success' => 'Konfiguracja zapisana.',
			
			'admin.config.permissions' => 'Konfiguracja uprawnień',
			'admin.config.permissions.global' => 'Admin (zero lub puste by zezwalać wszystkim użytkownikom)',
			'admin.config.permissions.global.plugins' => 'Włączanie/Wyłączanie Wtyczek:',
			'admin.config.permissions.global.themes' => 'Zmiana Tematów:',
			'admin.config.permissions.write' => 'Publikowanie (zero lub puste by zezwalać wszystkim użytkownikom)',
			'admin.config.permissions.write.posts' => 'Publikownaie postów:',
			'admin.config.permissions.write.pages' => 'Publikownie stron:',
			'admin.config.permissions.manage' => 'Manage (zero lub puste by zezwalać wszystkim użytkownikom)',
			'admin.config.permissions.manage.posts' => 'Zarządzanie postami:',
			'admin.config.permissions.manage.pages' => 'Zarządzanie stronami:',
			'admin.config.permissions.manage.comments' => 'Zarządzanie komentarzami:',
			'admin.config.permissions.manage.categories' => 'Zarządzanie kategoriami:',
			'admin.config.permissions.manage.users' => 'Zarządzanie użytkownikami (wszyscy użytkownicy mogą zmieniać własne dane):',
			'admin.config.permissions.manage.links' => 'Zarządzanie odnośnikami:',
			'admin.config.permissions.manage.files' => 'Zarządzanie plikami:',
			'admin.config.permissions.config' => 'Konfiguracja (zero lub puste by zezwalać wszystkim użytkownikom)',
			'admin.config.permissions.config.general' => 'Konfiguracja ogólna:',
			'admin.config.permissions.config.display' => 'Konfiguracja widoku:',
			'admin.config.permissions.config.discussion' => 'Konfiguracja komentarzy:',
			'admin.config.permissions.config.permissions' => 'Konfiguracja uprawnień:',
			'admin.config.permissions.submit' => 'Wyślij',
			'admin.config.permissions.error.database' => 'Nie można zapisać do bazy!',
			'admin.config.permissions.message.success' => 'Konfiguracja zapisana.',
			
			'admin.manage.users' => 'Zarządzanie użytkownikami',
			'admin.manage.users.id' => 'ID',
			'admin.manage.users.username' => 'Nazwa użytkownika',
			'admin.manage.users.name' => 'Nazwa',
			'admin.manage.users.url' => 'URL',
			'admin.manage.users.email' => 'E-mail',
			'admin.manage.users.rank' => 'Pozycja',
			'admin.manage.users.action' => 'Akcja',
			'admin.manage.users.edit' => 'Edytuj',
			'admin.manage.users.edit.confirm' => 'Edytuj',
			'admin.manage.users.edit.cancel' => 'Anuluj',
			'admin.manage.users.delete' => 'Usuń',
			'admin.manage.users.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.users.delete.confirm' => 'Tak',
			'admin.manage.users.delete.cancel' => 'Nie',
			'admin.manage.users.new' => 'Utwórz nowego użytkownika',
			'admin.manage.users.new.username' => 'Nazwa użytkownika:',
			'admin.manage.users.new.password' => 'Hasło (dwukrotnie):',
			'admin.manage.users.new.rank' => 'Pozycja:',
			'admin.manage.users.new.submit' => 'Utwórz',
			'admin.manage.users.password' => 'Zmień Hasło',
			'admin.manage.users.password.oldpassword' => 'Stare Hasło:',
			'admin.manage.users.password.newpassword' => 'Nowe Hasło (dwukrotnie):',
			'admin.manage.users.password.submit' => 'Zmień',
			'admin.manage.users.error.database' => 'Nie można zapisać do bazy!',
			'admin.manage.users.error.setrank' => 'Nie możesz nadać użytkwnikowi uprawnień wyższych lub równych tobie.',
			'admin.manage.users.error.newrank' => 'Nie możesz utworzyć uzytkownika z wyższymi uprawnieniami niż własne.',
			'admin.manage.users.error.usernametaken' => 'Wybrana nazwa użytkownika jest juz zajęta.',
			'admin.manage.users.error.invalidusername' => 'Błędna nazwa użytkownika. Nazwa użytkownika nie może być krótsza niż 2 i nie dłuższa niż 16 znaków oraz musi się składac tylko z małych liter, cyfr, myślników lub podkreślników (a–z, 0–9, -, _).',
			'admin.manage.users.error.newpasswordmatch' => 'Podane hasła nie są zgodne.',
			'admin.manage.users.error.wrongpassword' => 'Podałeś niewłaściwe hasło',
			'admin.manage.users.error.changepasswordmatch' => 'Podane nowe hasła nie są zgodne..',
			'admin.manage.users.message.editsuccess' => 'Użytkownik został zmieniony.',
			'admin.manage.users.message.editcancel' => 'Edycja anulowana.',
			'admin.manage.users.message.deletesuccess' => 'Użytkownik został usunięty.',
			'admin.manage.users.message.deletecancel' => 'Usuwanie anulowano.',
			'admin.manage.users.message.newsuccess' => 'Użytkownik został utworzony.',
			'admin.manage.users.message.passwordsuccess' => 'Twoje hasło zostało zmienione.',
			
			'admin.manage.cats' => 'Zarządzanie Kategoriami',
			'admin.manage.cats.id' => 'ID',
			'admin.manage.cats.name' => 'Nazwa',
			'admin.manage.cats.description' => 'Opis',
			'admin.manage.cats.showblog' => 'Blog',
			'admin.manage.cats.showlinks' => 'Strona',
			'admin.manage.cats.showlinks.yes' => 'Tak',
			'admin.manage.cats.showlinks.no' => 'Nie',
			'admin.manage.cats.posts' => 'Posty',
			'admin.manage.cats.links' => 'Odnośniki',
			'admin.manage.cats.action' => 'Akcja',
			'admin.manage.cats.edit' => 'Edytuj',
			'admin.manage.cats.edit.confirm' => 'Edytuj',
			'admin.manage.cats.edit.cancel' => 'Anuluj',
			'admin.manage.cats.delete' => 'Usuń',
			'admin.manage.cats.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.cats.delete.confirm' => 'Tak',
			'admin.manage.cats.delete.cancel' => 'Nie',
			'admin.manage.cats.new' => 'Utwórz nową kategorię',
			'admin.manage.cats.new.name' => 'Nazwa:',
			'admin.manage.cats.new.description' => 'Opis:',
			'admin.manage.cats.new.showblog' => 'Ilość odnośników pokazywanych w Blogu (tylko linki do kategorii, zero lub puste by wyłączyć):',
			'admin.manage.cats.new.showlinks' => 'Pokazuj tą kategorię na stronie odnośników (tylko linki do kategorii).',
			'admin.manage.cats.new.submit' => 'Utwórz kategorię',
			'admin.manage.cats.new.submitlink' => 'Utwórz kategorię odnośników',
			'admin.manage.cats.recalc' => 'Przelicz wszystko',
			'admin.manage.cats.error.database' => 'Nie można zapisać do bazy!',
			'admin.manage.cats.message.editsuccess' => 'Kategoria została zmieniona.',
			'admin.manage.cats.message.editcancel' => 'Edycja anulowana.',
			'admin.manage.cats.message.deletesuccess' => 'Kategoria została usunięta.',
			'admin.manage.cats.message.deletecancel' => 'Usuwanie anulowano.',
			'admin.manage.cats.message.newsuccess' => 'Kategoria została utworzona.',
			
			'admin.manage.posts' => 'Zarządzanie postami',
			'admin.manage.posts.id' => 'ID',
			'admin.manage.posts.title' => 'Tytuł',
			'admin.manage.posts.time' => 'Data',
			'admin.manage.posts.time.display' => '%0',
			'admin.manage.posts.author' => 'Autor',
			'admin.manage.posts.cats' => 'Kategorie',
			'admin.manage.posts.comments' => 'Komentarze',
			'admin.manage.posts.status' => 'Status',
			'admin.manage.posts.status.draft' => 'szkic',
			'admin.manage.posts.status.delay' => 'opóźnienie',
			'admin.manage.posts.status.both' => 'szkic | opóźnienie',
			'admin.manage.posts.action' => 'Akcja',
			'admin.manage.posts.edit' => 'Edytuj',
			'admin.manage.posts.delete' => 'Usuń',
			'admin.manage.posts.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.posts.delete.confirm' => 'Tak',
			'admin.manage.posts.delete.cancel' => 'Nie',
			'admin.manage.posts.each' => 'Ilość postów na stronie:',
			'admin.manage.posts.each.submit' => 'Zmień',
			'admin.manage.posts.recalc' => 'Przelicz komentarze',
			'admin.manage.posts.error.database' => 'Nie można zapisać do bazy!',
			'admin.manage.posts.message.deletesuccess' => 'Post został usunięty.',
			'admin.manage.posts.message.deletecancel' => 'Usuwanie anulowano.',
						
			'admin.manage.comments' => 'Zarządzanie komentarzami',
			'admin.manage.comments.id' => 'ID',
			'admin.manage.comments.post' => 'Post',
			'admin.manage.comments.name' => 'Nazwa',
			'admin.manage.comments.email' => 'E-mail',
			'admin.manage.comments.text' => 'Tekst',
			'admin.manage.comments.time' => 'Data',
			'admin.manage.comments.time.display' => '%0',
			'admin.manage.comments.status' => 'Status',
			'admin.manage.comments.status.moderated' => 'moderowany',
			'admin.manage.comments.action' => 'Akcja',
			'admin.manage.comments.approve' => 'Zatwierdź',
			'admin.manage.comments.edit' => 'Edytuj',
			'admin.manage.comments.edit.name' => 'Nazwa:',
			'admin.manage.comments.edit.email' => 'E-mail:',
			'admin.manage.comments.edit.url' => 'URL:',
			'admin.manage.comments.edit.markup' => 'Markup:',
			'admin.manage.comments.edit.markup.none' => '(X)HTML',
			'admin.manage.comments.edit.text' => 'Tekst:',
			'admin.manage.comments.edit.preview' => 'Podgląd',
			'admin.manage.comments.edit.previewbox' => 'Podgląd',
			'admin.manage.comments.edit.submit' => 'Edytuj',
			'admin.manage.comments.edit.cancel' => 'Anuluj',
			'admin.manage.comments.delete' => 'Usuń',
			'admin.manage.comments.delete.message' => 'Czy jestes pewien, że chcesz usunąć ten komentarz?',
			'admin.manage.comments.delete.confirm' => 'Tak',
			'admin.manage.comments.delete.cancel' => 'Nie',
			'admin.manage.comments.each' => 'Ilość komentarzy na stronie:',
			'admin.manage.comments.each.submit' => 'Zmień',
			'admin.manage.comments.showtext' => 'Pokaż pełny tekst do:',
			'admin.manage.comments.showtext.mod' => 'moderowane komentarze',
			'admin.manage.comments.showtext.all' => 'wszystkie komentarze',
			'admin.manage.comments.showtext.none' => 'nie pokazuj pełnego tekstu',
			'admin.manage.comments.showtext.submit' => 'Zmień',
			'admin.manage.comments.error.database' => 'Nie można zapisać do bazy!',
			'admin.manage.comments.message.approve' => 'Komentarz został zatwierdzony.',
			'admin.manage.comments.message.editsuccess' => 'Komentarz sotał zmieniony.',
			'admin.manage.comments.message.editcancel' => 'Edycja anulowana',
			'admin.manage.comments.message.deletesuccess' => 'Komentarz został usunięty.',
			'admin.manage.comments.message.deletecancel' => 'Usuwanie anulowano.',
			
			'admin.manage.pages' => 'Zarządzanie Stronami',
			'admin.manage.pages.id' => 'ID',
			'admin.manage.pages.title' => 'Tytuł',
			'admin.manage.pages.url' => 'URL',
			'admin.manage.pages.action' => 'Akcja',
			'admin.manage.pages.edit' => 'Edytuj',
			'admin.manage.pages.edit.confirm' => 'Edytuj',
			'admin.manage.pages.edit.cancel' => 'Anuluj',
			'admin.manage.pages.delete' => 'Usuń',
			'admin.manage.pages.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.pages.delete.confirm' => 'Tak',
			'admin.manage.pages.delete.cancel' => 'Nie',
			'admin.manage.pages.up' => '↑',
			'admin.manage.pages.down' => '↓',
			'admin.manage.pages.show' => 'Pokaż',
			'admin.manage.pages.hide' => 'Ukryj',
			'admin.manage.pages.new' => 'Utwórz nowy wpis',
			'admin.manage.pages.new.title' => 'Tytuł:',
			'admin.manage.pages.new.url' => 'URL (pozostaw puste by wstawić odstęp):',
			'admin.manage.pages.new.where' => 'Wstaw po:',
			'admin.manage.pages.where.top' => '(Góra)',
			'admin.manage.pages.where.separator' => '%0',
			'admin.manage.pages.where.link' => '%0',
			'admin.manage.pages.where.page' => '%0',
			'admin.manage.pages.new.submit' => 'Utwórz',
			'admin.manage.pages.error.database' => 'Błąd bazy danych..',
			'admin.manage.pages.message.editsuccess' => 'Wpis został zmieniony.',
			'admin.manage.pages.message.editcancel' => 'Edycja anulowana.',
			'admin.manage.pages.message.deletesuccess' => 'Wpis został usunięty.',
			'admin.manage.pages.message.deletecancel' => 'Usuwanie anulowano.',
			'admin.manage.pages.message.show' => 'Strona została dodana do menu.',
			'admin.manage.pages.message.hide' => 'Strona została usunięta z menu.',
			'admin.manage.pages.message.newentry' => 'Wpis został utworzony.',
			
			'admin.manage.links' => 'Zarządzaj Odnośnikami',
			'admin.manage.links.id' => 'ID',
			'admin.manage.links.title' => 'Tytuł',
			'admin.manage.links.url' => 'URL',
			'admin.manage.links.time' => 'Data',
			'admin.manage.links.time.display' => '%0',
			'admin.manage.links.author' => 'Autor',
			'admin.manage.links.cats' => 'Kategorie',
			'admin.manage.links.status' => 'Status',
			'admin.manage.links.status.sticky' => 'Przyklejony',
			'admin.manage.links.action' => 'Akcja',
			'admin.manage.links.edit' => 'Edytuj',
			'admin.manage.links.delete' => 'Usuń',
			'admin.manage.links.edit.now' => 'Teraz',
			'admin.manage.links.edit.sticky' => 'Przyklejony',
			'admin.manage.links.edit.confirm' => 'Edytuj',
			'admin.manage.links.edit.cancel' => 'Anuluj',
			'admin.manage.links.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.links.delete.confirm' => 'Tak',
			'admin.manage.links.delete.cancel' => 'Nie',
			'admin.manage.links.each' => 'Ilość odnośników na stronie:',
			'admin.manage.links.each.submit' => 'Zmień',
			'admin.manage.links.new' => 'Utwórz nowy odnośnik',
			'admin.manage.links.new.title' => 'Tytuł:',
			'admin.manage.links.new.url' => 'URL:',
			'admin.manage.links.new.cats' => 'Kategorie:',
			'admin.manage.links.new.sticky' => 'Przyklejony',
			'admin.manage.links.new.submit' => 'Utwórz',
			'admin.manage.links.error.database' => 'Nie można zapisać do bazy!',
			'admin.manage.links.message.createsuccess' => 'Odnośnik został utworzony.',
			'admin.manage.links.message.editsuccess' => 'Odnośnik zostasł zmieniony.',
			'admin.manage.links.message.editcancel' => 'Edycja anulowana.',
			'admin.manage.links.message.deletesuccess' => 'Odnośnik został usunięty.',
			'admin.manage.links.message.deletecancel' => 'Usuwanie anulowano.',
			
			'admin.manage.files' => 'Zarządzanie plikami',
			'admin.manage.files.currentdir' => 'Aktualny katalog: <kbd>%0</kbd>',
			'admin.manage.files.filename' => 'Nazwa',
			'admin.manage.files.filesize' => 'Wielkość',
			'admin.manage.files.action' => 'Akcja',
			'admin.manage.files.rename' => 'Zmień nazwę',
			'admin.manage.files.rename.confirm' => 'Zmięń nazwę',
			'admin.manage.files.rename.cancel' => 'Anuluj',
			'admin.manage.files.delete' => 'Usuń',
			'admin.manage.files.delete.message' => 'Czy jestes pewien, że chcesz usunąć <em>%0</em>?',
			'admin.manage.files.delete.confirm' => 'Tak',
			'admin.manage.files.delete.cancel' => 'Nie',
			'admin.manage.files.upload' => 'Załaduj',
			'admin.manage.files.upload.filename' => 'Nazwa pliku:',
			'admin.manage.files.upload.submit' => 'Załaduj',
			'admin.manage.files.newdir' => 'Utwórz nowy katalog',
			'admin.manage.files.newdir.dirname' => 'Nazwa katalogu:',
			'admin.manage.files.newdir.submit' => 'Utwórz',
			'admin.manage.files.message.newdirsuccess' => 'Katalog został utworzony.',
			'admin.manage.files.message.uploadsuccess' => 'Plik został załadowany.',
			'admin.manage.files.message.renamefilesuccess' => 'Nazwa pliku została zmieniona.',
			'admin.manage.files.message.renamedirsuccess' => 'Nazwa katalogu została zmieniona.',
			'admin.manage.files.message.renamecancel' => 'Zamiana nazwy została anulowana.',
			'admin.manage.files.message.deletecancel' => 'Usunięcie zostało anulowane.',
			'admin.manage.files.message.deletedirsuccess' => 'Katalog został usunięty.',
			'admin.manage.files.message.deletefilesuccess' => 'Plik został usunięty.',
			'admin.manage.files.error.dirname' => 'Błędna nazwa katalogu.',
			'admin.manage.files.error.newdirfail' => 'Nie można utworzyć katalogu.',
			'admin.manage.files.error.badfile' => 'Błąd pliku. Upewnij sie, że wielkość pliku jest nie większa niż '.ini_get('upload_max_filesize').'.',
			'admin.manage.files.error.uploadfail' => 'Nie można załadować pliku',
			'admin.manage.files.error.badfilename' => 'Błedna nazwa pliku.',
			'admin.manage.files.error.renamefilefail' => 'Nie można zmienić nazwy pliku.',
			'admin.manage.files.error.baddirname' => 'Błedna nazwa katalogu.',
			'admin.manage.files.error.renamedirfail' => 'Nie można zmienić nazwy katalogu.',
			'admin.manage.files.error.deletefilefail' => 'Nie można usunąć pliku.',
			'admin.manage.files.error.deletedirfail' => 'Nie można usunąć katalogu. Upewnij się, czy jest pusty.',
			'admin.manage.files.error.readdir' => 'Nie można oczytać zawartości katalogu.',
			
			'admin.write.posts' => 'Publikuj posty',
			'admin.write.posts.edit' => 'Edytuj Post',
			'admin.write.posts.title' => 'Tytuł:',
			'admin.write.posts.markup' => 'Markup:',
			'admin.write.posts.markup.none' => '(X)HTML',
			'admin.write.posts.cats' => 'Kategorie',
			'admin.write.posts.time' => 'Data/Czas:',
			'admin.write.posts.time.now' => 'Ustaw aktualny',
			'admin.write.posts.comments' => 'Zazwól na komentarze',
			'admin.write.posts.draft' => 'Szkic',
			'admin.write.posts.delay' => 'Opóźnij publikację',
			'admin.write.posts.text' => 'Tekst:',
			'admin.write.posts.preview' => 'Podgląd',
			'admin.write.posts.submit' => 'Wyślij',
			'admin.write.posts.previewbox' => 'Podgląd',
			'admin.write.posts.message.editsuccess' => 'Twój post został zmieniony.',
			'admin.write.posts.message.success' => 'Twój post został dodany.',
			'admin.write.posts.message.success.view' => '<a href="%0">Pokaż tego posta</a>',
			'admin.write.posts.message.success.edit' => '<a href="%0">Edytuj tego posta</a>',
			'admin.write.posts.message.success.more' => '<a href="%0">Publikuj kolejnego posta</a>',
			'admin.write.posts.message.success.manage' => '<a href="%0">Zarządzaj postami</a>',
			'admin.write.posts.error.database' => 'Błąd bazy danych..',
			'admin.write.posts.error.permissions' => 'Nie masz uprawnień na edycję tego postu.',
			'admin.write.posts.error.notfound' => 'Nie znaleziono postu.',
			
			'admin.write.pages' => 'Publikuj strony',
			'admin.write.pages.edit' => 'Edytuj stronę',
			'admin.write.pages.title' => 'Tytuł:',
			'admin.write.pages.markup' => 'Markup:',
			'admin.write.pages.markup.none' => '(X)HTML',
			'admin.write.pages.id' => 'ID:',
			'admin.write.pages.where' => 'Wstaw po:',
			'admin.write.pages.where.none' => '(Niewidzialna)',
			'admin.write.pages.where.top' => '(Góra)',
			'admin.write.pages.where.separator' => '%0',
			'admin.write.pages.where.link' => '%0',
			'admin.write.pages.where.page' => '%0',
			'admin.write.pages.text' => 'Tekst:',
			'admin.write.pages.preview' => 'Podgląd',
			'admin.write.pages.submit' => 'Wyślij',
			'admin.write.pages.previewbox' => 'Podgląd',
			'admin.write.pages.message.editsuccess' => 'Twoja strona została zmieniona.',
			'admin.write.pages.message.success' => 'Twoja strona zsotała dodana.',
			'admin.write.pages.message.success.view' => '<a href="%0">Pokaż tą stronę</a>',
			'admin.write.pages.message.success.edit' => '<a href="%0">Edytuj tą stronę</a>',
			'admin.write.pages.message.success.more' => '<a href="%0">Publikuj kolejną stronę</a>',
			'admin.write.pages.message.success.manage' => '<a href="%0">Zarządzaj stronami</a>',
			'admin.write.pages.error.database' => 'Błąd bazy danych..',
			'admin.write.pages.error.id' => 'To ID jest już użyte.',
			'admin.write.pages.error.notfound' => 'Strona nie została znaleziona.',
			'admin.write.pages.error.noid' => 'Nie określiłeś ID.',
			
			'admin.stats.overall' => 'Statystyki ogólne',
			'admin.stats.overall.browsers' => 'Przeglądarka',
			'admin.stats.overall.systems' => 'System',
			'admin.stats.overall.posts' => 'Posty',
			'admin.stats.overall.pages' => 'Strony',
			'admin.stats.overall.total' => 'W sumie: %0 / %1',
			'admin.stats.overall.year' => 'Ten rok: %0 / %1',
			'admin.stats.overall.month' => 'Ten miesiąc: %0 / %1',
			'admin.stats.overall.day' => 'Dzisiaj: %0 / %1',
			'admin.stats.overall.hour' => 'Ta godzina: %0 / %1', 
			
			'admin.stats.graphs' => 'Statystyki graficzne',
			'admin.stats.graphs.hours' => 'Godziny:',
			'admin.stats.graphs.days' => 'Dni:',
			'admin.stats.graphs.months' => 'Miesiące:',
			'admin.stats.graphs.months.01' => 'Sty',
			'admin.stats.graphs.months.02' => 'Lut',
			'admin.stats.graphs.months.03' => 'Mar',
			'admin.stats.graphs.months.04' => 'Kwi',
			'admin.stats.graphs.months.05' => 'Maj',
			'admin.stats.graphs.months.06' => 'Cze',
			'admin.stats.graphs.months.07' => 'Lip',
			'admin.stats.graphs.months.08' => 'Sie',
			'admin.stats.graphs.months.09' => 'Wrz',
			'admin.stats.graphs.months.10' => 'Paź',
			'admin.stats.graphs.months.11' => 'Lis',
			'admin.stats.graphs.months.12' => 'Gru',
			'admin.stats.graphs.years' => 'Lata:',
			
			'admin.stats.recent' => 'Ostatni odwiedzający',
			'admin.stats.recent.time' => 'Czas',
			'admin.stats.recent.time.display' => '%0, %1',
			'admin.stats.recent.ip' => 'IP',
			'admin.stats.recent.browser' => 'Przeglądarka',
			'admin.stats.recent.system' => 'System',
			'admin.stats.recent.hits' => 'Odwiedzin',
			
			'admin.menu.home'             => 'Start',
			'admin.menu.plugins'          => 'Wtyczki',
			'admin.menu.themes'           => 'Tematy',
			'admin.menu.logout'           => 'Wyloguj',
			'admin.menu.manage'           => 'Zarządzaj',
			'admin.menu.manage.posts'       => 'Posty',
			'admin.menu.manage.pages'       => 'Strony',
			'admin.menu.manage.links'       => 'Odnośniki',
			'admin.menu.manage.cats'        => 'Kategorie',
			'admin.menu.manage.comments'    => 'Komentarze',
			'admin.menu.manage.users'       => 'Użytkownicy',
			'admin.menu.manage.files'       => 'Pliki',
			'admin.menu.config'           => 'Konfiguracja',
			'admin.menu.config.general'     => 'Ogólnie',
			'admin.menu.config.discussion'  => 'Komentarze',
			'admin.menu.config.display'     => 'Widok',
			'admin.menu.config.permissions' => 'Uprawnienia',
			'admin.menu.write'            => 'Publikuj',
			'admin.menu.write.posts'        => 'Posty',
			'admin.menu.write.pages'        => 'Strony',
			'admin.menu.stats'            => 'Statystyki',
			'admin.menu.stats.overall'      => 'Sumaryczne',
			'admin.menu.stats.graphs'       => 'Wykresy',
			'admin.menu.stats.recent'       => 'Odwiedziny',
			
			'comment.email.moderated.subject' => 'Ktoś dodał komentarz do Twojego postu.',
			'comment.email.moderated' => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) dodał komentarz do Twojego postu, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%5">Zatwierdź</a> | <a href="%6">Edytuj</a> | <a href="%7">Usuń</a> ]</p>',
			'comment.email.approved.subject' => 'Ktoś dodał komentarz do Twojego postu.',
			'comment.email.approved'  => '<p><a href="%1">%0</a> (<a href="mailto:%2">%2</a>) dodał komentarz do Twojego postu, <em><a href="%3">%4</a></em>:</p><blockquote>%8</blockquote><p>[ <a href="%6">Edytuj</a> | <a href="%7">Usuń</a> ]</p>',
			
			// ---------------------------------------------------------------

			'theme.!default.post.nocomments' => 'Brak komentarzy',
			'theme.!default.post.onecomment' => 'Komentarz: 1',
			'theme.!default.post.numcomments' => 'Komentarzy: %0',
			
			'theme.!default.post.header' => 'Wysłany przez %0 on %1 at %2',
			'theme.!default.post.header.anon' => 'Posted on %0 at %1',
			
			'theme.!default.index.next' => 'Następny →',
			'theme.!default.index.prev' => '← Poprzedni',
			
			'theme.!default.page404' => '404: Strona nie została znaleziona',
			'theme.!default.page404.message' => 'Strona, której szukasz nie istnieje.',
			
			'theme.!default.post404' => '404: Strona nie została znaleziona',
			'theme.!default.post404.message' => 'Strona, której szukasz nie istnieje.',
			
			'theme.!default.nav' => 'Nawigacja',
			'theme.!default.nav.home' => 'Start',
			'theme.!default.nav.cats' => 'Kategorie',
			'theme.!default.nav.links' => 'Odnośniki',
			'theme.!default.nav.archives' => 'Archiwa',
			'theme.!default.nav.archives.posts' => 'Posty',
			'theme.!default.nav.archives.links' => 'Odnośniki',
			
			'theme.!default.linkback' => 'Oparte na <a href="http://www.fluffington.com/" style="color:inherit;text-decoration:inherit;">FLog</a>',
			
			'theme.!default.commentform' => 'Comment on This Post',
			'theme.!default.commentform.name' => 'Nazwa (wymagana):',
			'theme.!default.commentform.email' => 'E-mail (wymagany, nie wyświetlany):',
			'theme.!default.commentform.url' => 'URL:',
			'theme.!default.commentform.markup' => 'Markup:',
			'theme.!default.commentform.markup.none' => '(X)HTML',
			'theme.!default.commentform.text' => 'Tekst:',
			'theme.!default.commentform.text.markup' => 'Tekst (%0):',
			'theme.!default.commentform.preview' => 'Podgląd',
			'theme.!default.commentform.submit' => 'Wyślij',
			'theme.!default.commentform.previewbox' => 'Podgląd',
			'theme.!default.commentform.error.namemail' => 'Wymagane jest Twoje imię i adres e-mail.',
			'theme.!default.commentform.error.anonymous' => 'Anonimowi użytkownicy nie mogą publikować komentarzy.',
			'theme.!default.commentform.error.ip' => 'Twoj komentarz został zablokowany ponieważ Twój adres IP jest różny od tego, z którego zarządana formularza.',
			'theme.!default.commentform.error.referrer' => 'Twój komentarz został zablokowany z powodu błędnego referenta.',
			'theme.!default.commentform.error.allowcomments' => 'Tego postu nie można komentować.',
			'theme.!default.commentform.error.blocked' => 'Twój komentarz sotał zablokowany.',
			'theme.!default.commentform.error.database' => 'Błąd bazy.',
			'theme.!default.commentform.error.maxsize' => 'Twój komentarz jest zbyt długi. Maksymalna ilość znaków to %0 .',
			'theme.!default.commentform.message.moderated' => 'Twój komentarz będzie moderowany. Pojawi się po zatwierdzeniu przez moderatora.',
			'theme.!default.commentform.message.posted' => 'Twój komentarz został opublikowany',
			
			'theme.!default.error.database' => 'Błąd bazy.',
			'theme.!default.error.allowcomments' => 'Tego postu nie można komentować.',
			'theme.!default.error.maxsize' => 'Twój komentarz przekroczył dopuszczalny rozmiar %0 znaków.',
			'theme.!default.error.anonymous' => 'Anonimowi użytkownicy nie mogą publikować komentarzy.',
			'theme.!default.error.ip' => 'Twoj komentarz został zablokowany ponieważ Twój adres IP jest różny od tego, z którego zarządana formularza. Jeśli używasz serwera proxy i otrzymałeś ten komunikat na stronię błedu to możesz próbować ponownie.',
			'theme.!default.error.referrer' => 'Twój komentarz został zablokowany z powodu błędnego referenta.',
			'theme.!default.error.nameemail' => 'Wymagane jest Twoje imię i adres e-mail.',
			'theme.!default.message.moderated' => 'Twój komentarz będzie moderowany. Pojawi się po zatwierdzeniu przez moderatora.',
			'theme.!default.message.posted' => 'Twój komentarz został opublikowany',
			
			'theme.!default.archive.message' => 'Archiwum dla %0',
			'theme.!default.archive.message.cat' => '%1, archiwum dla %0',
			'theme.!default.archive.links.message' => 'Archiwum odnośników dla %0',
			'theme.!default.archive.links.message.cat' => '%1, archiwum odnośników dla %0',
			'theme.!default.archive.posts' => 'Archiwum postów',
			'theme.!default.archive.links' => 'Archiwum odnośników',
			'theme.!default.archive.view' => 'pokaż',
			'theme.!default.archive.months.01' => 'Styczeń',
			'theme.!default.archive.months.02' => 'Luty',
			'theme.!default.archive.months.03' => 'Marzec',
			'theme.!default.archive.months.04' => 'Kwiecień',
			'theme.!default.archive.months.05' => 'Maj',
			'theme.!default.archive.months.06' => 'Czerwiec',
			'theme.!default.archive.months.07' => 'Lipiec',
			'theme.!default.archive.months.08' => 'Sierpień',
			'theme.!default.archive.months.09' => 'Wrzesień',
			'theme.!default.archive.months.10' => 'Październik',
			'theme.!default.archive.months.11' => 'Listopad',
			'theme.!default.archive.months.12' => 'Grudzień',
			'theme.!default.archive.time.display' => '%1',

		);
		
$GLOBALS['FLog_lang_list']['pl'] = 'Polski (Xom)';

?>