<?php
print "<table class='maintable'>";
print "<tr class='headline'><td>Main Variables</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='editvars.php'>Edit main Vars</a><br>";
print "<li><A href='ban.php'>Ban IP</a><br>";
print "<li><A href='unban.php'>Unban IP</a><br>";
print "<li><A href='../index.php'>Admin Browsing(editing comments and entries)</a>";
print "</td></tr></table><br><br>";
print "<table class='maintable'>";
print "<tr class='headline'><td>Profile/Picture</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='picture.php'>Change/edit profile Pic</a><br>";
print "<li><A href='profile.php'>Change Profile</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'>";
print "<tr class='headline'><td>Category management</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='addcat.php'>Add Category</a><br>";
print "<li><A href='editcats.php'>Edit/Delete Category</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'>";
print "<tr class='headline'><td>Resume</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='resume.php'>Add/Edit Resume</a>";
print "</td></tr></table><br><br>";
print "<table class='maintable'>";
print "<tr class='headline'><td>GuestBook Controls</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='../guestbook/index.php'>Admin Browsing</a><br>";
print "<li><A href='searchgb.php'>Search</a><br>";
print "<li><A href='gbprune.php'>Prune</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'><tr class='headline'><td>Blog Control</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><A href='addarticle.php'>Add Entry</a><br>";
print "<li><A href='../index.php'>Edit/Delete Entries</a><br>";
print "<li><A href='pruneentries.php'>Prune Entries</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'><tr class='headline'><td>Poll Control(only 1 may run at a time)</td></tr>";
print "<tr class='mainrow'><td>";
print "<li><a href='addpoll.php'>Add Poll</a><br>";
print "<li><A href='deletepoll.php'>Delete Poll</a><br>";
print "<li><A href='addchoice.php'>Add Poll Choice</a><br>";
print "<li><A href='delchoice.php'>Delete Poll Choice</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'><tr class='headline'><td>Edit Calendar</td></tr>";
print "<tr class='mainrow'><td>";
print "<A href='calen.php'>Edit Calendar</a><br>";
print "<A href='flushcal.php'>Flush Calendar</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'><tr class='headline'><td>Photo Album</td></tr>";
print "<tr class='mainrow'><td>";
print "<A href='addphoto.php'>Add photo</a><br>";
print "<a href='deletephoto.php'>Delete Photo</a><br>";
print "</td></tr></table><br><br>";
print "<table class='maintable'><tr class='headline'><td>Unique blocks</td></tr>";
print "<tr class='mainrow'><td>";
print "<A href='uleft.php'>Edit Right block</a><br>";
print "<A href='right.php'>Edit Left Block</a><br>";
print "</td></tr></table>";
