<h2>SimplyBibTeX Help</h2>
<h3>About</h3>
SimplyBibTeX is a very simple but extremly flexible publishing system for BibTeX files. It allows to store manage, comment and link a bibliographic database.

<h3>Find Something?</h3>
You need to enter the field you searching for in the search request. 
e.g.:
<code>year=1997</code> will return all entries from year 1997 or 
<code>year=97</code>will return entries from the years 1797 997 or 2097 

<h3>Features</h3>
- BibTeX Parser
- XHTML Viewer (validating XHTML 1.0 and CSS)
- Feeds with autodetection
- RSS 2.0 Feeds per Database (validating)
- Atom Feeds per Database (validating for most databases)
- per item linking
- uploading in separate directory
- store meta data per database (comments, whatever you want)
- search the database

<h3>Requirements</h3>
- PHP 4.x or 5.x


