CREATE TABLE state (
  state_prefix char(2) NOT NULL default '',
  state_name varchar(30) NOT NULL default '',
  PRIMARY KEY  (state_prefix)
) TYPE=MyISAM;


INSERT INTO state VALUES ('AL', 'ALABAMA');
INSERT INTO state VALUES ('AK', 'ALASKA');
INSERT INTO state VALUES ('AS', 'AMERICAN SAMOA');
INSERT INTO state VALUES ('AZ', 'ARIZONA');
INSERT INTO state VALUES ('AR', 'ARKANSAS');
INSERT INTO state VALUES ('CA', 'CALIFORNIA');
INSERT INTO state VALUES ('CO', 'COLORADO');
INSERT INTO state VALUES ('CT', 'CONNECTICUT');
INSERT INTO state VALUES ('DE', 'DELAWARE');
INSERT INTO state VALUES ('DC', 'DISTRICT OF COLUMBIA');
INSERT INTO state VALUES ('FM', 'FEDERATED STATES OF MICRONESIA');
INSERT INTO state VALUES ('FL', 'FLORIDA');
INSERT INTO state VALUES ('GA', 'GEORGIA');
INSERT INTO state VALUES ('GU', 'GUAM');
INSERT INTO state VALUES ('HI', 'HAWAII');
INSERT INTO state VALUES ('ID', 'IDAHO');
INSERT INTO state VALUES ('IL', 'ILLINOIS');
INSERT INTO state VALUES ('IN', 'INDIANA');
INSERT INTO state VALUES ('IA', 'IOWA');
INSERT INTO state VALUES ('KS', 'KANSAS');
INSERT INTO state VALUES ('KY', 'KENTUCKY');
INSERT INTO state VALUES ('LA', 'LOUISIANA');
INSERT INTO state VALUES ('ME', 'MAINE');
INSERT INTO state VALUES ('MH', 'MARSHALL ISLANDS');
INSERT INTO state VALUES ('MD', 'MARYLAND');
INSERT INTO state VALUES ('MA', 'MASSACHUSETTS');
INSERT INTO state VALUES ('MI', 'MICHIGAN');
INSERT INTO state VALUES ('MN', 'MINNESOTA');
INSERT INTO state VALUES ('MS', 'MISSISSIPPI');
INSERT INTO state VALUES ('MO', 'MISSOURI');
INSERT INTO state VALUES ('MT', 'MONTANA');
INSERT INTO state VALUES ('NE', 'NEBRASKA');
INSERT INTO state VALUES ('NV', 'NEVADA');
INSERT INTO state VALUES ('NH', 'NEW HAMPSHIRE');
INSERT INTO state VALUES ('NJ', 'NEW JERSEY');
INSERT INTO state VALUES ('NM', 'NEW MEXICO');
INSERT INTO state VALUES ('NY', 'NEW YORK');
INSERT INTO state VALUES ('NC', 'NORTH CAROLINA');
INSERT INTO state VALUES ('ND', 'NORTH DAKOTA');
INSERT INTO state VALUES ('MP', 'NORTHERN MARIANA ISLANDS');
INSERT INTO state VALUES ('OH', 'OHIO');
INSERT INTO state VALUES ('OK', 'OKLAHOMA');
INSERT INTO state VALUES ('OR', 'OREGON');
INSERT INTO state VALUES ('PW', 'PALAU');
INSERT INTO state VALUES ('PA', 'PENNSYLVANIA');
INSERT INTO state VALUES ('PR', 'PUERTO RICO');
INSERT INTO state VALUES ('RI', 'RHODE ISLAND');
INSERT INTO state VALUES ('SC', 'SOUTH CAROLINA');
INSERT INTO state VALUES ('SD', 'SOUTH DAKOTA');
INSERT INTO state VALUES ('TN', 'TENNESSEE');
INSERT INTO state VALUES ('TX', 'TEXAS');
INSERT INTO state VALUES ('UT', 'UTAH');
INSERT INTO state VALUES ('VT', 'VERMONT');
INSERT INTO state VALUES ('VI', 'VIRGIN ISLANDS');
INSERT INTO state VALUES ('VA', 'VIRGINIA');
INSERT INTO state VALUES ('WA', 'WASHINGTON');
INSERT INTO state VALUES ('WV', 'WEST VIRGINIA');
INSERT INTO state VALUES ('WI', 'WISCONSIN');
INSERT INTO state VALUES ('WY', 'WYOMING');
        
