// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
theme_style_select : '-- ñéâð&aring;ð&aring;ú --',
theme_code_desc : 'òø&aring;ê àú ÷&aring;ã &auml;-HTML',
theme_code_title : 'ò&aring;øê ÷&aring;ã HTML',
theme_code_wordwrap : 'âìéùú ù&aring;ø&aring;ú',
theme_sub_desc : 'ëúá úçúé',
theme_sup_desc : 'ëúá òéìé',
theme_hr_desc : '&auml;ëðñ ÷&aring; à&aring;ô÷é',
theme_removeformat_desc : '&auml;ñø òé&ouml;&aring;á',
theme_custom1_desc : '&auml;úéà&aring;ø ùìê ëàï',
insert_image_border : 'âá&aring;ì',
insert_image_dimensions : 'îéîãéí',
insert_image_vspace : 'çìì àðëé',
insert_image_hspace : 'çìì à&aring;ô÷é',
insert_image_align : 'ééù&aring;ø',
insert_image_align_default : 'áøéøú îçãì',
insert_image_align_baseline : 'ì÷&aring; &auml;áñéñ',
insert_image_align_top : 'ìîòì&auml;',
insert_image_align_middle : 'ìàî&ouml;ò',
insert_image_align_bottom : 'ìîè&auml;',
insert_image_align_texttop : 'ìøàù &auml;è÷ñè',
insert_image_align_absmiddle : 'ìàî&ouml;ò î&aring;çìè',
insert_image_align_absbottom : 'ì÷&ouml;&auml; úçú&aring;ï î&aring;çìè',
insert_image_align_left : 'ìùîàì',
insert_image_align_right : 'ìéîéï',
theme_font_size : 'â&aring;ãì â&aring;ôï',
theme_fontdefault : '-- îùôçú â&aring;ôðéí --',
theme_block : '-- òé&ouml;&aring;á --',
theme_paragraph : 'ôñ÷&auml;',
theme_div : '÷èò',
theme_address : 'ëú&aring;áú',
theme_pre : 'îò&aring;&ouml;á îøàù',
theme_h1 : 'ë&aring;úøú 1',
theme_h2 : 'ë&aring;úøú 2',
theme_h3 : 'ë&aring;úøú 3',
theme_h4 : 'ë&aring;úøú 4',
theme_h5 : 'ë&aring;úøú 5',
theme_h6 : 'ë&aring;úøú 6',
theme_colorpicker_title : 'áçø &ouml;áò',
theme_colorpicker_apply : '&auml;çì',
theme_forecolor_desc : 'áçø &ouml;áò è÷ñè',
theme_backcolor_desc : 'áçø &ouml;áò ø÷ò',
theme_charmap_title : 'áçø ú&aring; îé&aring;çã',
theme_charmap_desc : '&auml;ëðñ ú&aring; îé&aring;çã',
theme_visualaid_desc : '&auml;çìó î&ouml;á ÷&aring;&aring;éí îðçéí/øëéáéí áìúé-ðøàéí',
insert_anchor_title : '&auml;ëðñ/òø&aring;ê ò&aring;âï',
insert_anchor_name : 'ùí &auml;ò&aring;âï',
theme_anchor_desc : '&auml;ëðñ/òø&aring;ê ò&aring;âï',
theme_insert_link_titlefield : 'ë&aring;úøú',
theme_clipboard_msg : 'ôò&aring;ì&aring;ú &auml;òú÷&auml;/âæéø&auml;/&auml;ãá÷&auml; àéðï ðúîë&aring;ú úçú Mozilla &aring;-Firefox.\n&auml;àí áø&ouml;&aring;ðê ì÷áì îéãò ð&aring;ñó à&aring;ã&aring;ú ð&aring;ùà æ&auml;?',
theme_path : 'ðúéá',
cut_desc : 'âæ&aring;ø',
copy_desc : '&auml;òú÷',
paste_desc : '&auml;ãá÷',
link_list : 'øùéîú ÷éù&aring;øéí',
image_list : 'øùéîú úî&aring;ð&aring;ú',
browse : 'ñééø',
image_props_desc : 'îàôééðé úî&aring;ð&auml;',
newdocument_desc : 'îñîê çãù',
class_name : 'îçì÷&auml;',
newdocument : '&auml;àí àú&auml; áè&aring;ç ùáø&ouml;&aring;ðê ìð÷&aring;ú àú ëì &auml;ú&aring;ëï?'
});
