<?
  $sm[':))'] = $sm[':-))'] = $sm[':D'] = $sm[':-D'] = 'biggrin.gif';
  $sm[':)'] = $sm[':-)'] = 'smile.gif';
  $sm[';)'] = $sm[';-)'] = 'wink.gif';
  $sm[':/'] = $sm[':-/'] = 'unsure.gif';
  $sm[':['] = $sm[':-['] = $sm[':('] = $sm[':-('] = 'sad.gif';
  $sm[':P'] = $sm[':-P'] = 'tongue.gif';
  $sm[':o'] = $sm[':-o'] = 'surprised.gif';
  $sm[':x'] = $sm[':-x'] = 'angry.gif';
  $sm[':|'] = $sm[':-|'] = 'neutral.gif';
  $sm['->'] = $sm['=>'] = $sm['-&gt;'] = $sm['=&gt;'] = 'arrow.gif';

  $sm[':blush:'] = 'blush.gif';
  $sm[':confused:'] = 'confused.gif';
  $sm[':cool:'] = 'cool.gif';
  $sm[':cry:'] = 'cry.gif';
  $sm[':eek:'] = 'eek.gif';
  $sm[':evil:'] = 'evil.gif';
  $sm[':exclaim:'] = 'exclaim.gif';
  $sm[':glad:'] = 'glad.gif';
  $sm[':idea:'] = 'idea.gif';
  $sm[':lol:'] = 'lol.gif';
  $sm[':naughty:'] = 'naughty.gif';
  $sm[':question:'] = 'question.gif';
  $sm[':roll:'] = 'rollseyes.gif';
  $sm[':smirk:'] = 'smirk.gif';
  $sm[':tired:'] = 'tired.gif';
  $sm[':zonked:'] = 'zonked.gif';
?>
