<?php
//DynaCal V1.1.0  by Liquid Frog. Copyright (c) 2004 Liquid Frog - www.liquidfrog.com
$path_to_script = "http://www.yoursite.com/calendar_directory"; //Path to the calendar script e.g. http://yoursite.com/calendar - no trailing slash
$page_background_color = "#C0C0C0";// The overall color of both the item page and the iframe if an iframe is used on your main page
$Sun = "Su";  //The days of the week - e.g. Mn, Mon, Monday etc or non English values
$Mon = "Mo";
$Tue = "Tu";
$Wed = "We";
$Thu = "Th";
$Fri = "Fr";
$Sat = "Sa";
$Jan = "Jan";  //The months of the year   - e.g. Jn, Jan, January etc or non English values
$Feb = "Feb";
$Mar = "Mar";
$Apr = "Apr";
$May = "May";
$Jun = "Jun";
$Jul = "Jul";
$Aug = "Aug";
$Sep = "Sep";
$Oct = "Oct";
$Nov = "Nov";
$Dec = "Dec";
$item_heading_border = "1";//Show a border for the item popup window? Values are 0 for off or 1 -> whatever you want for thickness
$item_heading_border_color = "#808080";//The color of the border if $item_heading__border set to 1 or greater
$item_message = "Item: ";//The message to show in the calendar popup window
$item_heading_font = "verdana";// The font to use in the calendar popup window
$item_heading_font_size = "2"; // The heading font size to use in the calendar popup window
$item_heading_font_color = "#000000";//The heading font color to use in the calendar popup window
$item_heading_background_color = "#808080";//The background color of the popup heading
$item_text_background_color = "#C0C0C0";//Color of the background when displaying text in the calendar popup window
$item_text_font = "verdana";//Font to use for text in the calendar popup window
$item_text_font_size = "2";//Size of font to use for text in the calendar popup window
$item_text_font_color = "#FFFFFF";//Font color to use for text in the calendar popup window
$cal_border = "0";//Show a calendar border? Values are 0 for off or 1 -> whatever you want for thickness
$cal_border_color = "#008000";//The color of the border if $cal_border set to 1 or greater
$cal_cell_spacing = "0";//Enter a value 1 or greater if you want to use cell spacing. Has the effect of "buttonising" if using a value of 4 or more
$month_bg_color = "#C0FFC0";//The color of the background at the top of the calendar behind Month, Year
$day_font = "verdana";// The font to use for Mon, Tue, Wed etc
$day_font_size = "1";//  The font size to use for Mon, Tue, Wed etc
$day_font_color = "white";// The font color to use for Mon, Tue, Wed etc
$day_background_color = "#79F579";// Color of the days background  Mon, Tues Wed etc
$today_hilite_color = "#40FF40";//The highlight color to use for "Today"
$today_hilite_font_color = "black";//The font color to use for "Today"
$daily_date_font = "arial";//The font for each date in the calendar
$daily_date_font_size = "2";//The font size for each date in the calendar
$daily_date_font_color = "#00C000";  //The font color for each date in the calendar
$daily_date_background_color = "#E8FEE8";//The background color for each date in the calendar
$month_year_heading_font = "verdana";//The font for the calendar heading - month, year
$month_year_heading_font_size = "2";//The size of the calendar heading font
$month_year_heading_font_color ="#000000";//The color of the calendar heading font
$use_image = "no";//Use an image or a button if there is information for this day? Set to yes to use image or no to use button
$button_height = "14";//If using a button, define the height of it here
$button_width = "19"; //If using a button, define the width of it here
$button_hilite_color = "#79F579"; //Button highlight color
$button_text_color = "#E8FEE8";//The color of the text on the button
$change_month_label = "Change Months";// The label to show next to the month change buttons
$change_month_label_font  = "verdana"; //Font to use for the change month label text - NOT AVAILABLE IN VERSION WITH LIQUID FROG LINK
$change_month_label_font_color  ="#000000";//Font color to use for the change month label text - NOT AVAILABLE IN VERSION WITH LIQUID FROG LINK
$change_month_label_font_size = "1";//Font size to use for the change month label text - NOT AVAILABLE IN VERSION WITH LIQUID FROG LINK
$month_on_label = "Next month"; // The label for the Next month button
$month_back_label = "Previous month";  // The label for the Previous month button
$username = "demo";// The username for admin
$password = "demo";//The password for admin
?>