<?php
session_start();
include("../languages/default.php");
include("languages/default.php");
include "connect.inc";
echo "<head><title>$block_preferences_title</title>";
echo "<link rel='stylesheet' href='$style' type='text/css'>";
?>
<script>
<!-- Begin
function goTocustomURL() { window.location = "blocks.php?op=edit_custom_block"; }
//  End -->
</script>
<script>
<!-- Begin
function goTocustomcentURL() { window.location = "blocks.php?op=edit_custom_centre_block"; }
//  End -->
</script>
</head>
<?php
$getprefs="SELECT * from CC_prefs";
$getprefs2=mysql_query($getprefs) or die($no_preferences_error);
$getprefs3=mysql_fetch_array($getprefs2);
$cadmin=$_SESSION['cadmin'];
$getadmin="SELECT * from CC_admin where username='$cadmin'";
$getadmin2=mysql_query($getadmin) or die($no_admin_error);
$getadmin3=mysql_fetch_array($getadmin2);
if($getadmin3['status']==3)
{
 include "index.php";
 echo "<br><br>";
   if(isset($_POST['submit']))
   {
          $profile_block_label=$_POST['profile_block_label'];
          $login_block_label=$_POST['login_block_label'];
          $sidebanners_block_label=$_POST['sidebanners_block_label'];
          $newsletter_block_label=$_POST['newsletter_block_label'];
          $net_radio_block_label=$_POST['net_radio_block_label'];
          $donation_block_label=$_POST['donation_block_label'];
          $poll_block_label=$_POST['poll_block_label'];
          $sponsored_links_block_label=$_POST['sponsored_links_block_label'];
          $search_acronyms_block_label=$_POST['search_acronyms_block_label'];
          $google_adsense_block_label=$_POST['google_adsense_block_label'];
          $random_headlines_block_label=$_POST['random_headlines_block_label'];
          $archives_block_label=$_POST['archives_block_label'];
          $general_block_label=$_POST['general_block_label'];
          $monthly_archives_block_label=$_POST['monthly_archives_block_label'];
          $ran_pics_block_label=$_POST['ran_pics_block_label'];
          $search_archives_block_label=$_POST['search_archives_block_label'];
          $visitors_online_block_label=$_POST['visitors_online_block_label'];
          $admin_link_block_label=$_POST['admin_link_block_label'];
          $gallery_block_label=$_POST['gallery_block_label'];
          $user_right_bottom_block_label=$_POST['user_right_bottom_block_label'];
          $user_left_top_block_label=$_POST['user_left_top_block_label'];
          $user_right_top_block_label=$_POST['user_right_top_block_label'];
          $weblinks_label=$_POST['weblinks_label'];
          $ranquotes_block_label=$_POST['ranquotes_block_label'];
          $newsreader_block_label=$_POST['newsreader_block_label'];
          $menu_block_label=$_POST['menu_block_label'];
          $download_block_label=$_POST['download_block_label'];
          $shout_block_label=$_POST['shout_block_label'];
          $scroller_block_label=$_POST['scroller_block_label'];
          $calendar_block_label=$_POST['calendar_block_label'];
          $custom_block1_label=$_POST['custom_block1_label'];
          $custom_block2_label=$_POST['custom_block2_label'];
          $custom_block3_label=$_POST['custom_block3_label'];
          $custom_block4_label=$_POST['custom_block4_label'];
          $custom_block5_label=$_POST['custom_block5_label'];
          $custom_block6_label=$_POST['custom_block6_label'];
          $custom_top_center_block_label=$_POST['custom_top_center_block_label'];
          $google_search_block_label=$_POST['google_search_block_label'];
          $custom_bottom_center_block_label=$_POST['custom_bottom_center_block_label'];
          $last5_class1_posts_label=$_POST['last5_class1_posts_label'];
          $last5_bb2_posts_label=$_POST['last5_bb2_posts_label'];
          $show_last_phorum_label=$_POST['show_last_phorum_label'];
          // ~ Old values to update CC_blocks - not very elegant but it works ~ will probably update this in the next version//
          $old_last5_class1_posts_label=$_POST['old_last5_class1_posts_label'];
          $old_last5_bb2_posts_label=$_POST['old_last5_bb2_posts_label'];
          $old_show_last_phorum_label=$_POST['old_show_last_phorum_label'];
          $old_scroller_block_label=$_POST['old_scroller_block_label'];
          $old_menu_block_label=$_POST['old_menu_block_label'];
          $old_newsreader_block_label=$_POST['old_newsreader_block_label'];
          $old_google_adsense_block_label=$_POST['old_google_adsense_block_label'];
          $old_profile_block_label=$_POST['old_profile_block_label'];
          $old_random_headlines_block_label=$_POST['old_random_headlines_block_label'];
          $old_shout_block_label=$_POST['old_shout_block_label'];
          $old_ranquotes_block_label=$_POST['old_ranquotes_block_label'];
          $old_monthly_archives_block_label=$_POST['old_monthly_archives_block_label'];
          $old_visitors_online_block_label=$_POST['old_visitors_online_block_label'];
          $old_menu_block_label=$_POST['old_menu_block_label'];
          $old_search_archives_block_label=$_POST['old_search_archives_block_label'];
          $old_gallery_block_label=$_POST['old_gallery_block_label'];
          $old_download_block_label=$_POST['old_download_block_label'];
          $old_admin_link_block_label=$_POST['old_admin_link_block_label'];
          $old_general_block_label=$_POST['old_general_block_label'];
          $old_ran_pics_block_label=$_POST['old_ran_pics_block_label'];
          $old_custom_block1_label=$_POST['old_custom_block1_label'];
          $old_custom_block2_label=$_POST['old_custom_block2_label'];
          $old_custom_block3_label=$_POST['old_custom_block3_label'];
          $old_custom_block4_label=$_POST['old_custom_block4_label'];
          $old_custom_block5_label=$_POST['old_custom_block5_label'];
          $old_custom_block6_label=$_POST['old_custom_block6_label'];
          $old_weblinks_label=$_POST['old_weblinks_label'];
          $old_calendar_block_label=$_POST['old_calendar_block_label'];
          $old_custom_bottom_center_block_label=$_POST['old_custom_bottom_center_block_label'];
          $old_custom_top_center_block_label=$_POST['old_custom_top_center_block_label'];
          $old_google_search_block_label=$_POST['old_google_search_block_label'];
          $editblocknames="UPDATE CC_block_names SET newsreader_block_label='$newsreader_block_label',show_last_phorum_label='$show_last_phorum_label',last5_bb2_posts_label='$last5_bb2_posts_label',last5_class1_posts_label='$last5_class1_posts_label',login_block_label='$login_block_label',search_acronyms_block_label='$search_acronyms_block_label',sponsored_links_block_label='$sponsored_links_block_label',poll_block_label='$poll_block_label',donation_block_label='$donation_block_label',net_radio_block_label='$net_radio_block_label',newsletter_block_label='$newsletter_block_label',sidebanners_block_label='$sidebanners_block_label',google_search_block_label='$google_search_block_label',google_adsense_block_label='$google_adsense_block_label',random_headlines_block_label='$random_headlines_block_label',general_block_label='$general_block_label',custom_bottom_center_block_label='$custom_bottom_center_block_label',custom_top_center_block_label='$custom_top_center_block_label',custom_block6_label='$custom_block6_label',custom_block5_label='$custom_block5_label',custom_block4_label='$custom_block4_label',custom_block3_label='$custom_block3_label',custom_block2_label='$custom_block2_label',calendar_block_label='$calendar_block_label',scroller_block_label='$scroller_block_label',shout_block_label='$shout_block_label',download_block_label='$download_block_label',menu_block_label='$menu_block_label', ranquotes_block_label='$ranquotes_block_label', gallery_block_label='$gallery_block_label', weblinks_label='$weblinks_label',custom_block1_label = '$custom_block1_label', admin_link_block_label = '$admin_link_block_label',visitors_online_block_label = '$visitors_online_block_label', search_archives_block_label ='$search_archives_block_label', ran_pics_block_label='$ran_pics_block_label',profile_block_label='$profile_block_label', archives_block_label='$archives_block_label',monthly_archives_block_label='$monthly_archives_block_label'";

          mysql_query($editblocknames) or die ($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_last5_class1_posts_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$last5_class1_posts_label' WHERE id = '$id'";
          mysql_query($editblocknames) or die ($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_last5_bb2_posts_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$last5_bb2_posts_label' WHERE id = '$id'";
          mysql_query($editblocknames) or die ($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_newsreader_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$newsreader_block_label' WHERE id = '$id'";
          mysql_query($editblocknames) or die ($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$show_last_phorum_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$show_last_phorum_label' WHERE id = '$id'";
          mysql_query($editblocknames) or die ($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_google_adsense_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$google_adsense_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_newsletter_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$newsletter_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_donation_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$donation_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_search_acronyms_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$search_acronyms_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_net_radio_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$net_radio_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_sidebanners_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$sidebanners_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_poll_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$poll_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_sponsored_links_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$sponsored_links_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_general_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$general_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_random_headlines_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$old_random_headlines_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_top_center_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_top_center_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_bottom_center_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_bottom_center_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_scroller_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$scroller_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_profile_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$profile_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_shout_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$shout_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_ranquotes_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$ranquotes_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_monthly_archives_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$monthly_archives_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_visitors_online_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$visitors_online_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_menu_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$menu_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_search_archives_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$search_archives_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_gallery_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$gallery_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_download_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$download_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_admin_link_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$admin_link_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_ran_pics_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$ran_pics_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block1_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block1_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_weblinks_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$weblinks_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block2_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block2_label' WHERE id = '$id'";

          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block3_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block3_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block4_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block4_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_login_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];

          $editblocknames2="UPDATE CC_blocks SET label = '$login_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block5_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block5_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_custom_block6_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$custom_block6_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die($unable_to_save_preferences_error);
          $getstuff="SELECT * from CC_blocks where label = '$old_calendar_block_label'";
          $getstuff2=mysql_query($getstuff) or die($unable_to_save_preferences_error);
          $getstuff3=mysql_fetch_array($getstuff2);
          $id = $getstuff3['id'];
          $editblocknames2="UPDATE CC_blocks SET label = '$calendar_block_label' WHERE id = '$id'";
          mysql_query($editblocknames2) or die ($unable_to_save_preferences_error);
          echo $preferences_saved_label;
          echo "<br><b>$page_auto_refresh</b>";
          echo "<meta http-equiv='refresh' content='0;URL=blocks.php'>";
   }else{
      echo "<table border='0' cellspacing='3' width='100%' style='border-collapse: collapse; border: 1px solid $getprefs3[blockbordercolor]'>";
      echo "<tr bgcolor=$getprefs3[block_heading_background_color]><td colspan='4'><left>";
      echo "<font face='verdana' size='1' color='#FFFFFF'><$getprefs3[block_heading_font_decoration]>$edit_side_blocks_label</b></center></td></tr>";
      $getprefs="SELECT * from CC_block_names";
      $getprefs2=mysql_query($getprefs) or die($no_preferences_error);
      $getprefs3=mysql_fetch_array($getprefs2);
      echo "<tr><td width='100%' colspan='4'><p align = 'center'><br><br></td></tr>";
      echo "<tr><td width= '30%'>";
      echo "<b>$item_label</b>";
      echo "<td width= '70%'>";
      echo "<b>$current_settings_label</b>";
      echo "<tr><td width= '30%'>";
      echo "<form action='blocks.php' method='post'>";
      echo $archives_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='archives_block_label' size='30' value='$getprefs3[archives_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $calendar_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='calendar_block_label' size='30' value='$getprefs3[calendar_block_label]'>";
      echo "<input type='hidden' name='old_calendar_block_label' size='30' value='$getprefs3[calendar_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block1_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_block1_label' size='30' value='$getprefs3[custom_block1_label]'>";
      echo "<input type='hidden' name='old_custom_block1_label' size='30' value='$getprefs3[custom_block1_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block2_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_block2_label' size='30' value='$getprefs3[custom_block2_label]'>";
      echo "<input type='hidden' name='old_custom_block2_label' size='30' value='$getprefs3[custom_block2_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block3_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_block3_label' size='30' value='$getprefs3[custom_block3_label]'>";
      echo "<input type='hidden' name='old_custom_block3_label' size='30' value='$getprefs3[custom_block3_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block4_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_block4_label' size='30' value='$getprefs3[custom_block4_label]'>";
      echo "<input type='hidden' name='old_custom_block4_label' size='30' value='$getprefs3[custom_block4_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block5_name_label;
      echo "<td width= '70%'>";

      echo "<input type='text' name='custom_block5_label' size='30' value='$getprefs3[custom_block5_label]'>";
      echo "<input type='hidden' name='old_custom_block5_label' size='30' value='$getprefs3[custom_block5_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_block6_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_block6_label' size='30' value='$getprefs3[custom_block6_label]'>";
      echo "<input type='hidden' name='old_custom_block6_label' size='30' value='$getprefs3[custom_block6_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_top_center_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_top_center_block_label' size='30' value='$getprefs3[custom_top_center_block_label]'>";
      echo "<input type='hidden' name='old_custom_top_center_block_label' size='30' value='$getprefs3[custom_top_center_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $custom_bottom_center_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='custom_bottom_center_block_label' size='30' value='$getprefs3[custom_bottom_center_block_label]'>";
      echo "<input type='hidden' name='old_custom_bottom_center_block_label' size='30' value='$getprefs3[custom_bottom_center_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $donation_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='donation_block_label' size='30' value='$getprefs3[donation_block_label]'>";
      echo "<input type='hidden' name='old_donation_block_label' size='30' value='$getprefs3[donation_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $download_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='download_block_label' size='30' value='$getprefs3[download_block_label]'>";
      echo "<input type='hidden' name='old_download_block_label' size='30' value='$getprefs3[download_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $gallery_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='gallery_block_label' size='30' value='$getprefs3[gallery_block_label]'>";
      echo "<input type='hidden' name='old_gallery_block_label' size='30' value='$getprefs3[gallery_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $general_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='general_block_label' size='30' value='$getprefs3[general_block_label]'>";
      echo "<input type='hidden' name='old_general_block_label' size='30' value='$getprefs3[general_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $adsense_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='google_adsense_block_label' size='30' value='$getprefs3[google_adsense_block_label]'>";
      echo "<input type='hidden' name='old_google_adsense_block_label' size='30' value='$getprefs3[google_adsense_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $googlesearch_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='google_search_block_label' size='30' value='$getprefs3[google_search_block_label]'>";
      echo "<input type='hidden' name='old_google_search_block_label' size='30' value='$getprefs3[google_search_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $admin_link_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='admin_link_block_label' size='30' value='$getprefs3[admin_link_block_label]'>";
      echo "<input type='hidden' name='old_admin_link_block_label' size='30' value='$getprefs3[admin_link_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $login_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='login_block_label' size='30' value='$getprefs3[login_block_label]'>";
      echo "<input type='hidden' name='old_login_block_label' size='30' value='$getprefs3[login_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $menu_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='menu_block_label' size='30' value='$getprefs3[menu_block_label]'>";
      echo "<input type='hidden' name='old_menu_block_label' size='30' value='$getprefs3[menu_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $monthly_archives_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='monthly_archives_block_label' size='30' value='$getprefs3[monthly_archives_block_label]'>";
      echo "<input type='hidden' name='old_monthly_archives_block_label' size='30' value='$getprefs3[monthly_archives_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $net_radio_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='net_radio_block_label' size='30' value='$getprefs3[net_radio_block_label]'>";
      echo "<input type='hidden' name='old_net_radio_block_label' size='30' value='$getprefs3[net_radio_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $newsletter_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='newsletter_block_label' size='30' value='$getprefs3[newsletter_block_label]'>";
      echo "<input type='hidden' name='old_newsletter_block_label' size='30' value='$getprefs3[newsletter_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $poll_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='poll_block_label' size='30' value='$getprefs3[poll_block_label]'>";
      echo "<input type='hidden' name='old_poll_block_label' size='30' value='$getprefs3[poll_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $newsreader_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='newsreader_block_label' size='30' value='$getprefs3[newsreader_block_label]'>";
      echo "<input type='hidden' name='old_newsreader_block_label' size='30' value='$getprefs3[newsreader_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $profile_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='profile_block_label' size='30' value='$getprefs3[profile_block_label]'>";
      echo "<input type='hidden' name='old_profile_block_label' size='30' value='$getprefs3[profile_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $randheadlines_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='random_headlines_block_label' size='30' value='$getprefs3[random_headlines_block_label]'>";
      echo "<input type='hidden' name='old_random_headlines_block_label' size='30' value='$getprefs3[random_headlines_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $random_picture_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='ran_pics_block_label' size='30' value='$getprefs3[ran_pics_block_label]'>";
      echo "<input type='hidden' name='old_ran_pics_block_label' size='30' value='$getprefs3[ran_pics_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $ranquotes_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='ranquotes_block_label' size='30' value='$getprefs3[ranquotes_block_label]'>";
      echo "<input type='hidden' name='old_ranquotes_block_label' size='30' value='$getprefs3[ranquotes_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $scroller_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='scroller_block_label' size='30' value='$getprefs3[scroller_block_label]' >";
      echo "<input type='hidden' name='old_scroller_block_label' size='30' value='$getprefs3[scroller_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $search_acronyms_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='search_acronyms_block_label' size='30' value='$getprefs3[search_acronyms_block_label]'>";
      echo "<input type='hidden' name='old_search_acronyms_block_label' size='30' value='$getprefs3[search_acronyms_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo "<tr><td width= '30%'>";
      echo $search_archives_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='search_archives_block_label' size='30' value='$getprefs3[search_archives_block_label]'>";
      echo "<input type='hidden' name='old_search_archives_block_label' size='30' value='$getprefs3[search_archives_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $shout_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='shout_block_label' size='30' value='$getprefs3[shout_block_label]'>";
      echo "<input type='hidden' name='old_shout_block_label' size='30' value='$getprefs3[shout_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $sidebanners_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='sidebanners_block_label' size='30' value='$getprefs3[sidebanners_block_label]'>";
      echo "<input type='hidden' name='old_sidebanners_block_label' size='30' value='$getprefs3[sidebanners_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $sponsored_links_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='sponsored_links_block_label' size='30' value='$getprefs3[sponsored_links_block_label]'>";
      echo "<input type='hidden' name='old_sponsored_links_block_label' size='30' value='$getprefs3[sponsored_links_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $visitors_online_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='visitors_online_block_label' size='30' value='$getprefs3[visitors_online_block_label]'>";
      echo "<input type='hidden' name='old_visitors_online_block_label' size='30' value='$getprefs3[visitors_online_block_label]'>";
      echo "<tr><td width= '30%'>";
      echo $weblinks_block_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='weblinks_label' size='30' value='$getprefs3[weblinks_label]'>";
      echo "<input type='hidden' name='old_weblinks_label' size='30' value='$getprefs3[weblinks_label]'>";
      echo "<tr><td width= '30%'>";
      echo $last5_class1_posts_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='last5_class1_posts_label' size='30' value='$getprefs3[last5_class1_posts_label]'>";
      echo "<input type='hidden' name='old_last5_class1_posts_label' size='30' value='$getprefs3[last5_class1_posts_label]'>";
      echo "<tr><td width= '30%'>";
      echo $last5_bb2_posts_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='last5_bb2_posts_label' size='30' value='$getprefs3[last5_bb2_posts_label]'>";
      echo "<input type='hidden' name='old_last5_bb2_posts_label' size='30' value='$getprefs3[last5_bb2_posts_label]'>";
      echo "<tr><td width= '30%'>";
      echo $show_last_phorum_name_label;
      echo "<td width= '70%'>";
      echo "<input type='text' name='show_last_phorum_label' size='30' value='$getprefs3[show_last_phorum_label]'>";
      echo "<input type='hidden' name='old_weblinks_label' size='30' value='$getprefs3[show_last_phorum_label]'>";
      echo "<tr><td width= '30%'>";
      echo "<td width= '70%'>";
      echo "<input type='submit' name='submit' value='Save' class = 'buttons'></form>";
      echo "<tr><td width= '100%'colspan='2'>";
      echo "<input type=button value='$edit_custom_block_button_label' class = 'buttons' onClick='goTocustomURL()'><br><br>";
      echo "<input type=button value='$edit_custom_center_block_button_label' class = 'buttons' onClick='goTocustomcentURL()'><br><br>";
      echo "</tr></table>";
   }
   echo "</td></tr></table>";
switch( $_GET[ "op" ] )
{

case "edit_custom_block":
echo "<br><br><table width = '100%' border = '1'><tr><td valign = 'top'>";
$res = @mysql_query("SELECT * FROM CC_custom_blocks");
$error_msg .= mysql_error();
$i = '0';
while($row = mysql_fetch_array($res))
{
$i++;
if ($i== '4'){
echo "<tr><td valign = 'top'>";
}
  $content = $row[customblock];
  $content = stripslashes($content);
  echo "<b>$block_id_num_label-> $i </b><td valign = 'top'>$content<td valign = 'top'>";
}
echo "</tr></td></table>";
$res = @mysql_query("SELECT customid FROM CC_custom_blocks");
echo "<form action='editcustomblock.php' method='post'>";
echo "<p><center><label><b>$select_block_to_edit_label - </b>";
echo "<select name='theid'>";
while($row = mysql_fetch_array($res))
{
        echo "<option value=\"" . $row[ "customid" ] . "\">" . $row[ "customid" ] . "</option>\n";
}
echo "</select>";
echo "</label></p>";
echo "<p><center><input type='submit' value='$edit_this_admin_button_label' class = 'buttons'/></p>";
echo "</form>";
break;

case "edit_custom_centre_block":
echo "<br><br><table width = '100%' border = '1'><tr><td valign = 'top'>";
$res = @mysql_query("SELECT * FROM CC_custom_centre_blocks");
$error_msg .= mysql_error();
$i = '0';
while($row = mysql_fetch_array($res))
{
   $i++;
   if ($i== '4'){
     echo "<tr><td valign = 'top'>";
   }
  $content = $row[customblock];
  $content = stripslashes($content);
  echo "<b>$block_id_num_label-> $i </b><td valign = 'top'>$content<td valign = 'top'>";
}
echo "</tr></td></table>";
$res = @mysql_query("SELECT customid FROM CC_custom_centre_blocks");
echo "<form action='editcustomcentreblock.php' method='post'>";
echo "<p><center><label><b>$select_block_to_edit_label - </b>";
echo "<select name='theid'>";
while($row = mysql_fetch_array($res))
{
        echo "<option value=\"" . $row[ "customid" ] . "\">" . $row[ "customid" ] . "</option>\n";
}
echo "</select>";
echo "</label></p>";
echo "<p><center><input type='submit' value='$edit_this_admin_button_label' class = 'buttons'/></p>";
echo "</form>";
break;
}
}else{
  echo $no_login_error;
  include "index.php";
}
?>