<?php
session_start();

// NOTE* this page is unencrytped. You may change the purchase value of the add on blocks if you like, but don't expect to receive the blocks if you do!
include "languages/default.php";
include "../languages/default.php";
?>
<head><title>Purchase Clever Copy add ons</title>
<?php
echo "<link rel='stylesheet' href='$style' type='text/css'></head>";
include "connect.inc";
$cadmin=$_SESSION['cadmin'];
$getadmin="SELECT * from CC_admin where username='$cadmin'";
$getadmin2=mysql_query($getadmin) or die($no_admin_error);
$getadmin3=mysql_fetch_array($getadmin2);
if($getadmin3['status']==3)
{
  include "index.php";
  echo "<table border='1' cellspacing='3' width='100%' style='border-collapse: collapse; border: 1px solid $getprefs3[blockbordercolor]'>";
  echo "<tr bgcolor=$getprefs3[block_heading_background_color]><td colspan = '8'><left>";
  echo "<font face=$getprefs3[block_heading_font_face] size=$getprefs3[block_heading_font_size] color=$getprefs3[block_heading_font_color]><$getprefs3[block_heading_font_decoration]>Purchase add ons</font></b></td></tr>";
  echo "<tr><td valign = 'top'colspan = '8'>";
  echo "<b>You may purchase any add on using either your credit card via Esellerates' secure server or PayPal. All add on blocks are a blanket price of $9.99<br>If you wish to purchase a license to run Clever Copy WITHOUT a link, this is available for just $15.00</b><hr>";
  echo "<tr><td valign = 'top' colspan = '8'>";
  echo "<b>PayPal<br><br></b>";
  echo "<tr><td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Banner Manager $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Banner Manager'>";
  echo "<input type='hidden' name='item_number' value='Banner Manager'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</td>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Event Calendar $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Event Calendar'>";
  echo "<input type='hidden' name='item_number' value='Event Calendar'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</td><br>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Web Link Exchange $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Web Link Exchange'>";
  echo "<input type='hidden' name='item_number' value='Web Link Exchange'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</td><br>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Google Ads & Search $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Google Ads & Search'>";
  echo "<input type='hidden' name='item_number' value='Google Ads & Search'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</tr></td><br>";
  echo "<tr><td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Poll Manager $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Poll Manager'>";
  echo "<input type='hidden' name='item_number' value='Poll Manager'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</td>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Pay Per Click $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Pay Per Click'>";
  echo "<input type='hidden' name='item_number' value='Pay Per Click'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</td><br>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Shout Box $9.99<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Shout Box'>";
  echo "<input type='hidden' name='item_number' value='Shout Box'>";
  echo "<input type='hidden' name='amount' value='9.99'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</tr></td><br>";
  echo "<td valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "Link Removal $15.00<td valign = 'top'>";
  echo "<input type='image' src='https://www.paypal.com/en_GB/i/btn/x-click-but22.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='add' value='1'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='hidden' name='item_name' value='Clever Copy link removal'>";
  echo "<input type='hidden' name='item_number' value='Clever Copy link removal'>";
  echo "<input type='hidden' name='amount' value='15.00'>";
  echo "<input type='hidden' name='no_shipping' value='1'>";
  echo "<input type='hidden' name='currency_code' value='USD'>";
  echo "</form>";
  echo "</tr></td><br>";
  echo "<tr><td  colspan = '8' valign = 'top'>";
  echo "<form target='paypal' action='https://www.paypal.com/cgi-bin/webscr' method='post'>";
  echo "<input type='hidden' name='cmd' value='_cart'>";
  echo "<input type='hidden' name='business' value='magusperde.cc@gmail.com'>";
  echo "<input type='image' src='https://www.paypal.com/en_US/i/btn/view_cart_03.gif' border='0' name='submit' alt='Make payments with PayPal - it's fast, free and secure!'>";
  echo "<input type='hidden' name='display' value='1'>";
  echo "</form>";
  echo "</tr></td><br>";
  echo "<tr><td valign = 'top' colspan = '8'><br><hr><br>";
  echo "<tr><td valign = 'top' colspan = '8'><b>Visit our Esellerate shop to purchase directly with a credit card or just browse the store</b>";
  echo "<tr><td valign = 'top' colspan = '8'>Click <a href='http://store.eSellerate.net/s.aspx?s=STR5208920976' target='_new'>HERE</a>";
  echo "</tr></td></table><br>";
}else{
  echo $no_login_error;
  include "index.php";
}
?>