<?php
/*
##############################################
DO NOT EDIT THIS FILE UNLESS YOU HAVE A BACKUP
##############################################
*/
@include "config.php";

$data= "ad.txt"; 
@$data1 = fopen($data, "r") or printf ("\\\\ <!-- cannot open ad file -->"); 
@$done = fread($data1, filesize ($data)) or printf ("\\\\ <!-- cannot read ad file -->");
@fclose ($data1);

@$ads = explode("\n", $done);
@srand((float)microtime() * 1000000);
@shuffle($ads);

if(isset($_GET['type']) && $_GET['type'] == "js")
{
    @header("Content-type: text/plain");
    @header("Cache-Control: no-store, no-cache,");
    @header("Pragma: no-cache");
    $i = 1;
    $num = 0;
    while($i <= 11)
    {
        @$ad = explode(":|~split~:", $ads[$i]);
        if(isset($ad[0]) && isset($ad[1]))
        {
            $adurl =  rtrim($ad[2],"\n");
            $adbanner =  rtrim($ad[1],"\n");
            print "ad".$num."url    = '".$phpclickfile."?id=".$adurl."';\n";
            print "ad".$num."banner = '".$adbanner."';\n\n";
        }
        else
        {
            print "ad".$num."url    = '$default_ad_url';\n";
            print "ad".$num."banner = '$default_ad_banner';\n\n";
        }
        $i++;
        $num++;
    }
}
elseif(isset($_GET['type']) && $_GET['type'] == "iframe")
{
    @header("Content-type: text/html");
    @header("Cache-Control: no-store, no-cache,");
    @header("Pragma: no-cache");
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> \n";
    print "<html lang=\"en\"> \n";
    print "  <head> \n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\"> \n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"> \n";
    print "    <meta name=\"robots\" content=\"noindex,follow\"> \n";
    print "  </head> \n";
    print "  <body bgcolor=\"#FFFFFF\"> \n";

    $i = 1;
    @$ad = explode(":|~split~:", $ads[$i]);
    if(isset($ad[0]) && isset($ad[1]))
    {
        $adurl =  rtrim($ad[2],"\n");
        $adbanner =  rtrim($ad[1],"\n");
        print "   <a href=\"".$phpclickfile."?id=".$adurl."\"> \n";
        print "   <img src=\"".$adbanner."\" width=\"468\" height=\"60\" alt=\"\" border=\"0\"> \n";
        print "   </a> \n";
    }
    else
    {
        print "   <a href=\"".$default_ad_url."\"> \n";
        print "   <img src=\"".$default_ad_banner."\" width=\"468\" height=\"60\" alt=\"\" border=\"0\"> \n";
        print "   </a> \n";
    }
    print "  </body> \n";
    print "</html> \n";
}
else
{
    @header("Content-type: text/html");
    @header("Cache-Control: no-store, no-cache,");
    @header("Pragma: no-cache");
    print "\\\\ <!-- no type specifid -->";
}
?>