<?php
/*
##############################################
DO NOT EDIT THIS FILE UNLESS YOU HAVE A BACKUP
##############################################
*/
include "config.php";
session_start();

$adfile = "ad.txt";
@$handle = fopen($adfile, "r") or print "         <br><br><font size=\"3\"><b>Sorry cannot open ad file</b></font>\n";
@$contents = fread($handle, filesize($adfile)) or print "         <br><br><font size=\"3\"><b>Sorry cannot read ad file</b></font>\n";
@$ads = explode("\n", $contents) or print "         <br><br><font size=\"3\"><b>Sorry cannot seperate ad file contents</b></font>\n";
@$numads = count($ads, COUNT_RECURSIVE) or print "         <br><br><font size=\"3\"><b>Sorry cannot read count ads</b></font>\n";
$i = 1;
@fclose($handle) or printf ('<center><font size=3 color="#000000"><b>Sorry cannot close ad file</b></font></center>');

if(isset($_SESSION['password']) && isset($_SESSION['username']) && @crypt($password, $_SESSION['password']) == $_SESSION['password'] && @crypt($username, $_SESSION['username']) == $_SESSION['username'])
{
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\n";
    print "<!---            Simple PHP banner ad rotator             --->\n";
    print "<!---                                                     --->\n";
    print "<!---          Copyright (C) 2005 Sam J. Clarke           --->\n";
    print "<!--- (admin@free-php.org.uk  http://www.free-php.org.uk) --->\n";
    print "<!---                                                     --->\n";
    print "<!---  This script is 100% you can give it away for free  --->\n";
    print "<!---  but you CANNOT SELL IT without written permission  --->\n";
    print "<!---  from the Copyright holder.                         --->\n";
    print "<!---                                                     --->\n";
    print "<!--- If you have any questions about this script please  --->\n";
    print "<!--- feel free to email us at admin@free-php.org.uk      --->\n\n";
    print "<html lang=\"en\">\n";
    print "  <head>\n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n";
    print "    <meta name=\"robots\" content=\"noindex,follow\">\n";
    print "    <title>Banner Ad Rotator Admin</title>\n";
    print "    <style type=\"text/css\">\n";
    print "    <!--\n";
    print "    a.one:link {\n";
    print "      color: #0000ff\n";
    print "    }\n";
    print "    a.one:visited {\n";
    print "      color: #0000ff\n";
    print "    }\n";
    print "    a.one:hover {\n";
    print "      background: #E3E3E3\n";
    print "    }\n";
    print "    input#one {\n";
    print "      background-color: white;\n";
    print "      font-family: arial, verdana, sans-serif;\n";
    print "      font-weight: bold;\n";
    print "      font-size: 12pt;\n";
    print "    }\n";
    print "    textarea#one {\n";
    print "      background-color: white;\n";
    print "      font-family: arial, verdana, sans-serif;\n";
    print "      font-weight: bold;\n";
    print "      font-size: 12pt;\n";
    print "    }\n";
    print "    -->\n";
    print "    </style>\n";
    print "  </head>\n";
    print "  <body bgcolor=\"#388E8E\" vlink=\"#0000ff\" alink=\"#0000ff\" link=\"#0000ff\" text=\"#000000\">\n\n";
    print "    <table width=\"100%\" border=\"0\" bgcolor=\"#388E8E\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n";
    print "      <tr>\n";
    print "        <td width=\"20%\" align=\"right\" valign=\"top\" bgcolor=\"#388E8E\"><br><br><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=current\">Current Banner Ads</a><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=new_ad\">Add Banner Ad</a><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=del_ad\">Delete Banner Ad</a><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=code\">Banner Ad code</a><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=error\">Report Error | Leave Feedback</a><br><br>\n";
    print "         <a class=\"one\" href=\"admin.php?action=logout\">Logout</a><br><br>\n";
    print "        </td>\n";
    print "        <td width=\"80%\" align=\"center\" valign=\"top\" bgcolor=\"#388E8E\">\n";

    if(isset($_GET['action']) && $_GET['action'] == "current")
    {
        print "        <h1><u>Current Banner Ads In Rotator</u></h1><br><br>\n";
        for($i=1;$i <= $numads && isset($ads[$i]);$i++)
        {
            if(!empty($ads[$i]))
            {
                @$adinrotation = explode(":|~split~:", $ads[$i]);
                print "         <center><b><font size=\"3\" color=\"#FFFFFF\">\n";
                print "         AD URL: <font size=\"3\" color=\"#000000\">\n";
                print "         $adinrotation[0] </font>\n";
                print "         <br>BANNER URL:\n";
                print "         <font size=\"3\" color=\"#000000\"> $adinrotation[1] </font>\n";
                print "         <br>BANNER ID:\n";
                print "         <font size=\"3\" color=\"#000000\"> $adinrotation[2] </font>\n";
                print "         <br>BANNER CLICKS:\n";
                print "         </font><font size=3 color=\"#000000\"> $adinrotation[3] \n";
                print "         </font><br><br><br></b></center>\n\n";
            }
            else
            {
            }
        }
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "logout")
    {
        @session_destroy() or print "        <center><font size=\"3\" color=\"#000000\"><b>Sorry cannot log you out</b></font></center>";
        print "        <center><font size=\"4\" color=\"#000000\"><b>Your are logged out</b></font></center>";
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "error")
    {
        print "        <h1><u>Report Error | Leave Feedback</u></h1><br><br>\n";
        print "        <font size=\"4\"><b>Report error:</b></font><br><br>\n";
        print "        <font size=\"3\">\n";
        print "        If you have found an error please email<br> \n";
        print "        us at admin@free-php.org.uk or tell us by<br>\n";
        print "        leaving feedback</font>\n";
        print "        <br><br><br>\n";
        print "        <font size=\"4\"><b>Feedback</b></font><br><br>\n";
        print "        <form method=\"post\" action=\"http://free-php.org.uk/send.php\">\n";
        print "        Name:<br><input id=\"one\" name=\"name\" type=\"text\" size=\"30\"><br><br>\n";
        print "        Email:<br><input id=\"one\" name=\"email\" type=\"text\" size=\"30\">\n";
        print "        <input name=\"subject\" type=\"hidden\" size=\"30\" value=\"PHP BANNER AD ROTATOR\"><br><br>\n";
        print "        Message:<br><textarea id=\"one\" name=\"msg\" cols=\"32\" rows=\"6\"></textarea><br><br>\n";
        print "        <input id=\"one\" type=\"reset\" value=\"Reset\">&nbsp;<input id=\"one\" type=\"submit\" value=\"Send\">\n";
        print "        </form>\n";
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "new_ad")
    {
        print "        <h1><u>Add New Banner Ad</u></h1><br><br>\n";
        print "         <form action=\"admin.php?action=view\" method=\"post\">\n";
        print "         <font size=2 color=\"#FFFFFF\"><b>AD URL</font><br>\n";
        print "         <input id=\"one\" type=\"text\" name=\"url\" value=\"http://\" size=\"30\"><br>\n";
        print "         <font size=2 color=\"#FFFFFF\">AD BANNER URL</font><br>\n";
        print "         <input id=\"one\" type=\"text\" name=\"burl\" size=\"30\"><br>\n";
        print "         <font size=2 color=\"#FFFFFF\">AD BANNER ID must be unique</b></font><br>\n";
        print "         <input id=\"one\" type=\"text\" name=\"id\" size=\"30\"><br>\n";
        print "         <input id=\"one\" type=\"submit\" name=\"ADD\" value=\"ADD\">\n";
        print "         </form>\n";
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "view")
    {
        if(isset($_POST['url']) && isset($_POST['burl']) && isset($_POST['id']))
        {
            $url = $_POST['url'];
            $title = $_POST['burl'];
            $id = $_POST['id'];
            print "        <h1><u>Add New Banner Ad</u></h1><br><br>\n";
            print "         <font size=\"3\">url: ".$url."<br>\n";
            print "         banner url: ".$title."<br>\n";
            print "         banner id: ".$id."<br>\n";
            print "         <b>Warning once you click ADD AD this ad will start to be rotated</b></font><br><br>\n";
            print "         <form action=\"admin.php?action=new\" method=\"post\">\n";
            print "         <input id=\"one\" type=\"hidden\" name=\"url\" value=\"".$url."\">\n";
            print "         <input id=\"one\" type=\"hidden\" name=\"burl\" value=\"".$title."\">\n";
            print "         <input id=\"one\" type=\"hidden\" name=\"id\" value=\"".$id."\">\n";
            print "         <input id=\"one\" type=\"submit\" name=\"submit\" value=\"ADD AD\">\n";
            print "         </form>\n";
        }
        else
        {
                    print "         <br><br><font size=3><b>Sorry cannot get what you entered</b></font>\n";
        }
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "new")
    {
        print "        <h1><u>Add New Banner Ad</u></h1><br><br>\n";
        if(isset($_POST['url']) && isset($_POST['burl']) && isset($_POST['id']))
        {
             $url = $_POST['url'];
             $title = $_POST['burl'];
             $id = $_POST['id'];
             @$fp = fopen("ad.txt", "a") or print "         <br><br><font size=\"3\"><b>Sorry cannot open file</b></font>\n";
             @fwrite($fp, "\n");
             @fwrite($fp, $url.':|~split~:'.$title.':|~split~:'.$id.':|~split~:0:|~split~:') or print "         <br><br><font size=\"3\"><b>Sorry cannot write to file</b></font>\n";
             @fclose($fp) or print "         <br><br><font size=\"3\"><b>Sorry cannot close file</b></font>\n";
             print "         <br><br><br><font size=\"4\"><b>Your Ad Has Been Added<br>\n";
        }
        else
        {
             print "         <br><br><font size=3><b>Sorry cannot get what you entered</b></font>\n";
        }
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "del_ad")
    {
        print "        <h1><u>Delete Banner Ad</u></h1><br><br>\n";
        for($i=1;$i <= $numads && isset($ads[$i]);$i++)
        {
            if(!empty($ads[$i]))
            {
                @$adinrotation = explode(":|~split~:", $ads[$i]);
                print "         <b><font size=\"3\" color=\"#FFFFFF\">\n";
                print "         AD URL: <font size=\"3\" color=\"#000000\">\n";
                print "         $adinrotation[0] </font>\n";
                print "         <br>BANNER URL:\n";
                print "         <font size=\"3\" color=\"#000000\"> $adinrotation[1] </font>\n";
                print "         <br>BANNER ID:\n";
                print "         <font size=\"3\" color=\"#000000\"> $adinrotation[2] </font>\n";
                print "         <br>BANNER CLICKS:\n";
                print "         </font><font size=3 color=\"#000000\"> $adinrotation[3] </font></b>\n";
                print "         <form action=\"admin.php?action=delete\" method=\"post\">\n";
                print "         <input type=\"hidden\" name=\"adtodel\" value=\"".$i."\">\n";
                print "         <input id=\"one\" type=\"submit\" name=\"Delete\" value=\"Delete\">\n";
                print "         </form><br><br><br>\n\n";
            }
            else
            {
            }
        }
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "delete")
    {
        print "        <h1><u>Delete Banner Ad</u></h1><br><br>\n";
        if(isset($_POST['adtodel']))
        {
        @$addelnum = $_POST['adtodel'] or print "        <font size=3><b>Sorry cannot get ad to delete</b></font></center>\n";
        @$fp = fopen("ad.txt", "w") or print "        <font size=3><b>Sorry cannot open file</b></font></center>\n";
        for($i=1;$i <= $numads && isset($ads[$i]);$i++)
        {
                if(!empty($ads[$i]))
                {
                    if($i == $addelnum)
                    {
                    }
                    else
                    {
                    @fwrite($fp, "\n") or print "        <font size=3><b>Sorry cannot write to file</b></font></center>\n";
                    $ad =  rtrim($ads[$i],"\n"); 
                    @fwrite($fp, $ads[$i]) or print "        <font size=3><b>Sorry cannot write to file</b></font></center>\n";
                    }
                }
                else
                {
                }
            }
            @fclose($fp) or print "        <font size=3><b>Sorry cannot close file</b></font>\n";
            print "        <font size=5><b>The ads was deleted</b></font>\n";
        }
        else
        {
            print "        <font size=4><b>Sorry Cannot find ad you wanted to delete</b></font>\n";
        }
    }
    elseif(isset($_GET['action']) && $_GET['action'] == "code")
    {
        print "        <h1><u>Delete Banner Ad</u></h1><br><br>\n";
        print "        <font size=4><b>Iframe Ad html code: </b></font><br><br>\n";
        print "        <iframe src=\"".$adphpfile."?type=iframe\" width=\"469\" height=\"61\" scrolling=\"no\" marginwidth=\"0\" marginheight=\"0\" frameborder=\"0\">\n";
        print "        [Your user agent does not support frames or is currently configured\n";
        print "         not to display frames.]</iframe><br><br>\n";
        print "<textarea cols=\"60\" rows=\"5\">\n";
        print "&lt;iframe src=\"".$adphpfile."?type=iframe\" width=\"469\" height=\"61\" scrolling=\"no\" marginwidth=\"0\" marginheight=\"0\" frameborder=\"0\"&gt;\n";
        print "[Your user agent does not support frames or is currently configured\n";
        print "not to display frames.]&lt;/iframe&gt;</textarea>\n";
        print "        <font size=4><b><b>Make your own ad code: </b></font><br><br>\n";
        print "        <table width=\"100%\" border=\"0\" summary=\"ad code\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n";
        print "         <tr>\n";
        print "          <td width=\"50%\" align=\"center\">\n";
        print "           <SCRIPT type=\"text/javascript\" src=\"".$adphpfile."?type=js\">\n";
        print "           </script>\n";
        print "           <SCRIPT type=\"text/javascript\">\n";
        print "           <!--\n";
        print "           document.write('<a href=\"'+ad0url+'\">');\n";
        print "           document.write('<img src=\"'+ad0banner+'\" width=\"468\" height=\"60\" alt=\"\" border=\"0\"');\n";
        print "           document.write('</a>');\n";
        print "           //-->\n";
        print "           </script>\n";
        print "          </td>\n";
        print "         </tr>\n";
        print "         <tr>\n";
        print "          <td width=\"50%\" align=\"center\" valign=\"center\">\n";
        print "           <font face=\"arial\" size=3>\n";
        print "           Copy the code below and put it between the &lt;HEAD&gt; and the &lt;/HEAD&gt; tags of your document.\n";
        print "           </font><br>\n";
        print "           <textarea cols=\"35\" rows=\"5\">\n";
        print "&lt;SCRIPT type=\"text/javascript\" src=\"".$adphpfile."?type=js\"&gt;\n";
        print "&lt;/script&gt;</textarea><br><br>\n";
        print "           <font face=\"arial\" size=3>\n";
        print "           Then put this between the &lt;BODY&gt; and the &lt;/BODY&gt; tags where you have selected.\n";
        print "           </font><br>\n";
        print "           <textarea cols=\"35\" rows=\"5\">\n";
        print "&lt;SCRIPT type=\"text/javascript\"&gt;\n";
        print "&lt;!--\n";
        print "document.write('&lt;a href=\"'+ad0url+'\"&gt;');\n";
        print "document.write('&lt;img src=\"'+ad0banner+'\" width=\"468\" height=\"60\" alt=\"\" border=\"0\"');\n";
        print "document.write('&lt;/a&gt;');\n";
        print "//--&gt;\n";
        print "&lt;/script&gt;</textarea><br>\n";
        print "           <font face=\"arial\" size=2>\n";
        print "           to have more than one ad keep changing these<br>\n";
        print "           \"ad0url\" \"ad0banner\" <br><br>eg.<br>\n";
        print "           \"ad1url\" \"ad1banner\" <br>\n";
        print "           \"ad2url\" \"ad2banner\" <br><br>\n";
        print "           you can have a maximum of 11 ads.\n";
        print "           </font>\n";
        print "          </td>\n";
        print "         </tr>\n";
        print "        </table>\n";
    }
    else
    {
        print "        <h1><u>Welcome to your php banner rotator</u></h1><br><br>\n";
        print "          <IFRAME src=\"http://www.free-php.org.uk/scripts/banner_ad_rotator.html\" width=\"400\" height=\"300\"\n";
        print "                     scrolling=\"auto\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\">\n";
        print "          [Your user agent does not support frames or is currently configured\n";
        print "          not to display frames. However, you may visit\n";
        print "          <a class=\"one\" href=\"http://www.free-php.org.uk/scripts/banner_ad_rotator.html\" target=\"_blank\">the related document.</A>]\n";
        print "          </IFRAME>\n";
    }

    print "        </td>\n";
    print "      </tr>\n";
    print "    </table>\n";
    print "    <center><br><br><img src=\"php-power-white.PNG\" border=\"0\" alt=\"[powered by php]\">\n";
    print "    <br><font size=\"2\" color=\"#000000\">\n";
    print "    Copyright &copy; 2005 free-php.org.uk.<br>All Rights Reserved.\n";
    print "    <br><a class=\"one\" href=\"http://www.free-php.org.uk/\" target=\"_blank\">www.free-php.org.uk</a>\n";
    print "    </font></center>\n";
    print "  </body>\n";
    print "</html>";
}
elseif(isset($_GET['action']) && $_GET['action'] == "login")
{
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\n";
    print "<!---            Simple PHP banner ad rotator             --->\n";
    print "<!---                                                     --->\n";
    print "<!---          Copyright (C) 2005 Sam J. Clarke           --->\n";
    print "<!--- (admin@free-php.org.uk  http://www.free-php.org.uk) --->\n";
    print "<!---                                                     --->\n";
    print "<!---  This script is 100% you can give it away for free  --->\n";
    print "<!---  but you CANNOT SELL IT without written permission  --->\n";
    print "<!---  from the Copyright holder.                         --->\n";
    print "<!---                                                     --->\n";
    print "<!--- If you have any questions about this script please  --->\n";
    print "<!--- feel free to email us at admin@free-php.org.uk      --->\n\n";
    print "<html lang=\"en\">\n";
    print "  <head>\n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n";
    print "    <meta name=\"robots\" content=\"noindex,follow\">\n";
    print "    <title>Banner Ad Rotator Admin</title>\n";
    print "    <style type=\"text/css\">\n";
    print "    <!--\n";
    print "    a.one:link {\n";
    print "    color: #0000ff\n";
    print "    }\n";
    print "    a.one:visited {\n";
    print "    color: #0000ff\n";
    print "    }\n";
    print "    a.one:hover {\n";
    print "    background: #E3E3E3\n";
    print "    }\n";
    print "    -->\n";
    print "    </style>\n";
    print "  </head>\n";
    print "  <body bgcolor=\"#388E8E\" vlink=\"#0000ff\" alink=\"#0000ff\" link=\"#0000ff\" text=\"#000000\">\n\n";
    if (isset($_POST['pass']) && isset($_POST['user']) && $_POST['pass'] == $password && $_POST['user'] == $username)
    {
        @$_SESSION['username'] = crypt($_POST['user']) or printf ('<center><font size=3 color="#FF0000"><b>Sorry cannot set your username</b></font></center>');
        @$_SESSION['password'] = crypt($_POST['pass']) or printf ('<center><font size=3 color="#FF0000"><b>Sorry cannot set your password</b></font></center>');
        if(isset($_SESSION['username']) && isset($_SESSION['password']))
        {
            print "    <table width=\"100%\" border=\"0\" bgcolor=\"#388E8E\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n";
            print "      <tr>\n";
            print "        <td width=\"20%\" align=\"right\" valign=\"top\" bgcolor=\"#388E8E\"><br><br><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=current\">Current Banner Ads</a><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=new_ad\">Add Banner Ad</a><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=del_ad\">Delete Banner Ad</a><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=code\">Banner Ad code</a><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=error\">Report Error | Leave Feedback</a><br><br>\n";
            print "         <a class=\"one\" href=\"admin.php?action=logout\">Logout</a><br><br>\n";
            print "        </td>\n";
            print "        <td width=\"80%\" align=\"center\" valign=\"top\" bgcolor=\"#388E8E\">\n";
            print "        <h1><u>Welcome to your php banner rotator</u></h1><br><br>\n";
            print "          <IFRAME src=\"http://www.free-php.org.uk/scripts/banner_ad_rotator.html\" width=\"400\" height=\"300\"\n";
            print "                     scrolling=\"auto\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\">\n";
            print "          [Your user agent does not support frames or is currently configured\n";
            print "          not to display frames. However, you may visit\n";
            print "          <a class=\"one\" href=\"http://www.free-php.org.uk/scripts/banner_ad_rotator.html\" target=\"_blank\">the related document.</A>]\n";
            print "          </IFRAME>\n";
            print "        </td>\n";
            print "      </tr>\n";
            print "    </table>\n";
        }
        else
        {
            print "    <center>\n";
            print "    <font size=\"3\" color=\"#FFFFFF\"><b>Sorry cannot set your username/password</b></font>\n";
            print "    </center>\n";
        }
    }
    else
    {
        print "    <center>\n";
        print "    <font size=\"5\" color=\"#FFFFFF\"><b>Sorry Wrong Username/Password</b></font>\n";
        print "    </center>\n";
    }
    print "    <center><br><br><img src=\"php-power-white.PNG\" border=\"0\" alt=\"[powered by php]\">\n";
    print "    <br><font size=\"2\" color=\"#000000\">\n";
    print "    Copyright &copy; 2005 free-php.org.uk.<br>All Rights Reserved.\n";
    print "    <br><a class=\"one\" href=\"http://www.free-php.org.uk/\" target=\"_blank\">www.free-php.org.uk</a>\n";
    print "    </font></center>\n";
    print "  </body>\n";
    print "</html>";
}
else
{
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n\n";
    print "<!---            Simple PHP banner ad rotator             --->\n";
    print "<!---                                                     --->\n";
    print "<!---          Copyright (C) 2005 Sam J. Clarke           --->\n";
    print "<!--- (admin@free-php.org.uk  http://www.free-php.org.uk) --->\n";
    print "<!---                                                     --->\n";
    print "<!---  This script is 100% you can give it away for free  --->\n";
    print "<!---  but you CANNOT SELL IT without written permission  --->\n";
    print "<!---  from the Copyright holder.                         --->\n";
    print "<!---                                                     --->\n";
    print "<!--- If you have any questions about this script please  --->\n";
    print "<!--- feel free to email us at admin@free-php.org.uk      --->\n\n";
    print "<html lang=\"en\">\n";
    print "  <head>\n";
    print "    <title>Banner Ad Rotator Admin</title>\n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n";
    print "    <meta name=\"robots\" content=\"noindex,follow\">\n";
    print "    <style type=\"text/css\">\n";
    print "    <!--\n";
    print "    INPUT {\n";
    print "    background-color: white;\n";
    print "    font-family: arial, verdana, sans-serif;\n";
    print "    font-weight: bold;\n";
    print "    font-size: 12pt;\n";
    print "    }\n";
    print "    a.one:link {\n";
    print "    color: #0000ff";
    print "    }\n";
    print "    a.one:visited {\n";
    print "    color: #0000ff\n";
    print "    }\n";
    print "    a.one:hover {\n";
    print "    background: #E3E3E3\n";
    print "    }\n";
    print "    -->\n";
    print "    </style>\n";
    print "  </head>\n";
    print "  <body bgcolor=\"#388E8E\" vlink=\"#0000ff\" alink=\"#0000ff\" link=\"#0000ff\" text=\"#000000\">\n";
    print "    <center>\n";
    print "    <h1><u>Banner Ad Rotator Admin</u></h1><br><br>\n";
    print "    <table width=\"250\" border=\"1\" bgcolor=\"#388E8E\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n";
    print "      <tr>\n";
    print "        <td width=\"100%\" align=\"center\" valign=\"top\" bgcolor=\"#388E8E\">\n";
    print "          <font size=\"5\" color=\"#FFFFFF\"><b>Login</b></font>\n";
    print "          <form action=\"admin.php?action=login\" method=\"post\">\n";
    print "           <font size=\"3\" color=\"#FFFFFF\"><b>USERNAME: </b></font>\n";   
    print "           <input type=\"text\" name=\"user\" value=\"\" size=\"20\"><br>\n";
    print "           <font size=\"3\" color=\"#FFFFFF\"><b>PASSWORD: </b></font>\n";
    print "           <input type=\"password\" name=\"pass\" value=\"\" size=\"20\"><br>\n";
    print "           <input type=\"submit\" name=\"Login\" value=\"Login\">\n";
    print "          </form>\n";
    print "        </td>\n";
    print "      </tr>\n";
    print "    </table>\n";
    print "    <br><br><img src=\"php-power-white.PNG\" border=\"0\" alt=\"[powered by php]\">\n";
    print "    <br><font size=\"2\" color=\"#000000\">\n";
    print "    Copyright &copy; 2005 free-php.org.uk.<br>All Rights Reserved.\n";
    print "    <br><a class=\"one\" href=\"http://www.free-php.org.uk/\" target=\"_blank\">www.free-php.org.uk</a>\n";
    print "    </font></center>\n";
    print "  </body>\n";
    print "</html>";
}