<?php
/*
##############################################
DO NOT EDIT THIS FILE UNLESS YOU HAVE A BACKUP
##############################################
*/
include "config.php";
@$data= "ad.txt"; 
@$data1 = fopen($data, "r") or die("cannot open ad file"); 
@$done = fread($data1, filesize ($data)) or die("cannot read ad file");
@fclose ($data1) or die("cannot close ad file");
@$ads = explode("\n", $done);
@$numads = count($ads, COUNT_RECURSIVE);

if(isset($_GET['id']) && !empty($_GET['id']))
{
     for($i=1;$i<=$numads && isset($ads[$i]);$i++)
     {
          @$ad = explode(":|~split~:", $ads[$i]);
          @$fad =  rtrim($ads[$i],"\n");
          if(isset($ad[2]) && $_GET['id'] == $ad[2])
          {
               @$newnum = $ad[3]+1;
               @$url = $ad[0];
               $ads[$i] = ''.$ad[0].':|~split~:'.$ad[1].':|~split~:'.$ad[2].':|~split~:'.$newnum.':|~split~:';
          }
          else
          {
          }
     }

     @$fp = fopen($data, "w") or die("cannot open ad file");
     for($i=1;$i<=$numads && isset($ads[$i]);$i++)
     {
          @$fad =  rtrim($ads[$i],"\n");
          @fwrite($fp, "\n");
          @fwrite($fp, $fad);
     }
     @fclose($fp);

    @header("Location: ".$url."");
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> \n";
    print "<html lang=\"en\"> \n";
    print "  <head> \n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\"> \n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"> \n";
    print "    <meta name=\"robots\" content=\"noindex,follow\"> \n";
    print "    <meta HTTP-EQUIV=Refresh CONTENT=\"0; URL=".$url."\"> ";
    print "  </head> \n";
    print "  <body bgcolor=\"#FFFFFF\" vlink=\"#FF0000\" alink=\"#FF0000\" link=\"#FF0000\" text=\"#000000\"> \n";
    print "    <h1>You are now being redirected</h1> \n";
    print "    <h4>If you are not redirected <a herf=\"".$url."\">Click Here</a></h4> \n";
    print "  </body> \n";
    print "</html> \n";
}
else
{
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> \n";
    print "<html lang=\"en\"> \n";
    print "  <head> \n";
    print "    <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\"> \n";
    print "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"> \n";
    print "    <meta name=\"robots\" content=\"noindex,follow\"> \n";
    print "  </head> \n";
    print "  <body bgcolor=\"#FFFFFF\" vlink=\"#FF0000\" alink=\"#FF0000\" link=\"#FF0000\" text=\"#000000\"> \n";
    print "  </body> \n";
    print "</html> \n";
}
?>