<html><head><title><?php echo $getprefs3[title]; ?></title>
<link rel="stylesheet" href="<?php echo $style; ?>" type="text/css">
</head>
<?php
include "languages/default.php";
$default_url = $getprefs3[siteaddress];
$path_to_script = $default_url;
function do_email($to_name,$to_email,$from_name,$from_email,$url,$added_message,$ip){
include "languages/default.php";
$message = "$from_name $sent_mail_message\n\n$url\n\n";
if ($added_message != ""){
   $message = $message . "$from_name $also_added_message_label\n$added_message\n\n";
}
$message = $message . "======================================================================================================\nThis email was generated by the free 'Send to a friend' PHP script by Liquid Frog Software.\nVisit http://www.liquidfrog.com to download this and many other free scripts.";
if(!mail("$to_email","From $from_name - $to_name, $sent_subject_message_heading","$message","From:$from_email")){
   return FALSE;
}else{
   return TRUE;
}
}
function check_mail($email_address){
if (eregi("^[a-z0-9]+([-_\.]?[a-z0-9])+@[a-z0-9]+([-_\.]?[a-z0-9])+\.[a-z]{2,4}", $email_address)) {
   return TRUE;
}else{
   return FALSE;
}
}
function sendtofriend_form($to_name,$to_email,$from_name,$from_email,$url,$added_message){
global $path_to_script;
include "languages/default.php";
$ip_addy = getenv("REMOTE_ADDR");
echo"<br><br>$abuse_prevention_label'$ip_addy'";
echo"<form action='$path_to_script/sendtofriend.php' method='post'>";
echo"<input type='hidden' name='make_mail' value='do_it'>";
echo"<input type='hidden' name='url' value='$url'>";
echo"$friends_name_label<br><input type='text' name='to_name' value='$to_name' size='50'><br><br>";
echo"$friends_mail_address_label<br><input type='text' name='to_email' value='$to_email' size='50'><br><br>";
echo"$your_name_label<br><input type='text' name='from_name' value='$from_name' size='50'><br><br>";
echo"$your_mail_addy_label<br><input type='text' name='from_email' value='$from_email' size='50'><br><br>";
echo"$any_other_message_label<br><textarea name='added_message' cols='54' rows='5'>$added_message</textarea><br><br>";
echo"<input type='submit' value='$send_button_label' class = 'buttons'>";
echo"</form>";
}
?>